CREATE TABLE [dbo].[FBIssue_IFR](
	[FBIssue_ID] [int] NOT NULL,
	[FBIssueRECID] [varchar](50) NULL,
	[FBIssuePrevRECID] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[FBIssue_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO