CREATE TABLE [extract_riskman].[FRM_BATCH](
	[BatchID] [int] NOT NULL,
	[RecordID] [int] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[SavedBy] [varchar](50) NOT NULL,
 CONSTRAINT [PK_FRM_BATCH] PRIMARY KEY CLUSTERED 
(
	[BatchID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO