//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_dim()
        {
            this.debtor_fact = new HashSet<debtor_fact>();
        }
    
        public int account_key { get; set; }
        public string account_name { get; set; }
        public string account_number { get; set; }
        public string entity { get; set; }
        public string debtor { get; set; }
        public string costing { get; set; }
        public string activity_account { get; set; }
        public string natural_account { get; set; }
        public string chart_name { get; set; }
        public string short_description { get; set; }
        public string post_name { get; set; }
        public string pay_name { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public string address_line_3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string telephone { get; set; }
        public string abn { get; set; }
        public string contact_name { get; set; }
        public string contact_details { get; set; }
        public string bank_name { get; set; }
        public string bsb_code { get; set; }
        public string bank_account { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<int> payment_term_days { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debtor_fact> debtor_fact { get; set; }
    }
}
