//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_finance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DWHBEntities3 : DbContext
    {
        public DWHBEntities3()
            : base("name=DWHBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_dim> account_dim { get; set; }
        public virtual DbSet<accounting_period_dim> accounting_period_dim { get; set; }
        public virtual DbSet<cost_centre_dim> cost_centre_dim { get; set; }
        public virtual DbSet<date_dim> date_dim { get; set; }
        public virtual DbSet<debtor_fact> debtor_fact { get; set; }
        public virtual DbSet<ledger_dim> ledger_dim { get; set; }
        public virtual DbSet<portfolio_dim> portfolio_dim { get; set; }
        public virtual DbSet<program_dim> program_dim { get; set; }
        public virtual DbSet<service_stream_dim> service_stream_dim { get; set; }
    }
}
