CREATE TABLE [extract_kypera].[PropertyStructure_Block](
	[Company] [int] NOT NULL,
	[District] [varchar](3) NOT NULL,
	[Scheme] [varchar](3) NOT NULL,
	[ParentBlock] [varchar](13) NULL,
	[Code] [varchar](13) NOT NULL,
	[Name] [varchar](50) NULL,
	[Number] [varchar](25) NULL,
	[StreetCode] [varchar](3) NULL,
	[AreaCode] [int] NULL,
	[Street] [varchar](100) NOT NULL,
	[Town] [varchar](40) NULL,
	[County] [varchar](40) NULL,
	[Postcode] [varchar](10) NULL,
	[StructureLevel] [varchar](25) NOT NULL,
	[NominalCostCentre] [varchar](50) NULL,
	[Version] [varchar](100) NULL,
	[CreatedBy] [int] NULL,
	[CreatedOn] [datetime] NULL,
	[LastUpdateBy] [int] NULL,
	[LastUpdateOn] [datetime] NULL,
	[TechnicalOfficerCode] [int] NULL,
	[HousingOfficer] [int] NULL,
	[Active] [bit] NULL,
	[AsbestosPresent] [bit] NULL,
	[AsbestosDetails] [varchar](1000) NULL,
	[NominalDepartment] [varchar](50) NULL,
	[LastinspectionDate] [datetime] NULL,
	[LastInspectionNotes] [varchar](500) NULL,
	[ExternalFilesFolder] [varchar](200) NULL,
	[Flat] [varchar](25) NULL,
	[BuildingName] [varchar](50) NULL,
	[KeysetsAvailable] [int] NULL,
	[Latitude] [numeric](18, 0) NULL,
	[Longitude] [numeric](18, 0) NULL,
	[AlternateReference] [varchar](50) NULL,
	[AddressLine1] [varchar](127) NULL,
	[AreaOffice] [int] NULL,
	[BlockType] [int] NULL,
	[BlockSubType] [int] NULL,
	[CurrentStatus] [int] NULL,
	[BuildYear] [int] NULL,
	[LettableRooms] [int] NULL,
	[MarketRent] [money] NULL,
	[DebentureDate] [date] NULL,
	[DebentureCode] [varchar](25) NULL,
	[LTOVolume] [int] NULL,
	[LTOFolio] [int] NULL,
	[DebentureValue] [money] NULL,
	[JointVentureEquity] [money] NULL,
	[DebenturePrinciple] [money] NULL,
	[ContiguousBoundaryIsPrimary] [bit] NULL,
	[ContiguousBoundaryPrimaryID] [varchar](13) NULL,
	[AsbestosTotalRisk] [int] NULL,
	[AsbestosMaterialAssessment] [int] NULL,
	[AsbestosPriorityAssessment] [int] NULL,
	[AsbestosSurveyDate] [datetime] NULL
) ON [PRIMARY]

GO


