CREATE TABLE [extract_kypera].[PropertyStructure_Unit](
	[Company] [int] NOT NULL,
	[ID] [varchar](13) NOT NULL,
	[Name] [varchar](50) NULL,
	[AreaCode] [int] NULL,
	[StreetCode] [varchar](3) NOT NULL,
	[DwellingCode] [varchar](7) NOT NULL,
	[Number] [varchar](25) NULL,
	[Flat] [varchar](25) NULL,
	[Street] [varchar](50) NOT NULL,
	[Town] [varchar](40) NOT NULL,
	[County] [varchar](40) NULL,
	[Postcode] [varchar](10) NOT NULL,
	[isSold] [bit] NOT NULL,
	[SoldDate] [datetime] NULL,
	[isDemolished] [bit] NOT NULL,
	[DemolishedDate] [datetime] NULL,
	[Factored] [bit] NOT NULL,
	[FactoredType] [int] NULL,
	[CurrentStatus] [int] NOT NULL,
	[TechnicalOfficer] [int] NULL,
	[PropertyType] [int] NULL,
	[ConditionCode] [int] NULL,
	[HousingOfficer] [int] NULL,
	[IsGarageOrLockup] [bit] NULL,
	[Version] [varchar](100) NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[LastUpdateBy] [int] NOT NULL,
	[LastUpdateOn] [datetime] NOT NULL,
	[LastMainRentIncrease] [datetime] NULL,
	[NextMainRentIncrease] [datetime] NULL,
	[PreventChargeIncreasesUntil] [datetime] NULL,
	[PreventRentIncreasesUntil] [datetime] NULL,
	[LastOccupancyType] [int] NULL,
	[NominalCostCentre] [varchar](50) NULL,
	[Void] [bit] NOT NULL,
	[Aquired] [datetime] NULL,
	[NominalDepartment] [varchar](50) NULL,
	[ExcludeFromDebitRun] [bit] NOT NULL,
	[TechnicalOfficerCode] [int] NULL,
	[RepairsOnHold] [bit] NOT NULL,
	[CommonArea] [bit] NULL,
	[Commercial] [bit] NULL,
	[AsbestosPresent] [bit] NULL,
	[AsbestosDetails] [varchar](1000) NULL,
	[isShared] [bit] NULL,
	[PercentageOwnedByAssocation] [numeric](18, 4) NULL,
	[CommercialUnits] [int] NULL,
	[Ownership] [int] NULL,
	[AreaOffice] [int] NULL,
	[OwningBody] [int] NULL,
	[DefaultBlock] [varchar](13) NULL,
	[LocalAuthorityArea] [int] NULL,
	[Demand] [int] NULL,
	[UnlettableVoidReason] [int] NULL,
	[YearOfConstruction] [int] NULL,
	[ReasonForSale] [int] NULL,
	[NonHousingUnitType] [int] NULL,
	[RTBAppliedFor] [bit] NULL,
	[AddressLine1] [varchar](107) NOT NULL,
	[ChargeGroup] [int] NULL,
	[ChargeGroupFactored] [int] NULL,
	[PropertySubType] [int] NULL,
	[PropertyStyle] [int] NULL,
	[SHQS] [bit] NOT NULL,
	[SharedOwnershipTranche] [int] NULL,
	[PropertySource] [int] NULL,
	[SAPRating] [numeric](9, 1) NULL,
	[ExternalFilesFolder] [varchar](200) NULL,
	[CouncilTaxBand] [int] NULL,
	[TargetRent] [money] NULL,
	[RtbRights] [int] NULL,
	[DefaultOccupancyType] [int] NULL,
	[BuildingName] [varchar](50) NULL,
	[Address1Line] [varchar](256) NULL,
	[Address] [varchar](257) NULL,
	[RentSettingUnitValue] [money] NULL,
	[CountyID] [int] NULL,
	[RentSettingBedroomWeighting] [tinyint] NULL,
	[LocationOfMainsWaterIsolationValve] [varchar](100) NULL,
	[RentRegime] [int] NULL,
	[RentRegimeEffectiveDate] [datetime] NULL,
	[ShqsStatus] [int] NULL,
	[ShqsConformanceDate] [datetime] NULL,
	[ShqsNonConformanceReason] [int] NULL,
	[AlternateReference] [varchar](500) NULL,
	[Funder] [int] NULL,
	[FinancialAnalysis1] [int] NULL,
	[FinancialAnalysis2] [int] NULL,
	[NominationRights] [varchar](250) NULL,
	[CouncilRates] [numeric](9, 2) NULL,
	[MarketRent] [money] NULL,
	[NominalCompany] [varchar](20) NULL,
	[Targeted] [int] NULL,
	[TargetGroup] [varchar](200) NULL,
	[CAHProgram] [int] NULL,
	[MarketRentMethod] [int] NULL,
	[CurrentSubStatus] [int] NULL,
	[KeysetsAvailable] [int] NULL,
	[CeilingRent] [money] NULL,
	[Latitude] [numeric](18, 0) NULL,
	[Longitude] [numeric](18, 0) NULL,
	[BuildYear] [int] NULL,
	[BuildYearEstFrom] [int] NULL,
	[BuildYearEstTo] [int] NULL,
	[Pre] [bit] NULL,
	[Post] [bit] NULL,
	[BuildYearPrePost] [int] NULL,
	[LandLordReference] [varchar](12) NULL,
	[LandLordName] [varchar](50) NULL,
	[LandLordAddress] [varchar](200) NULL,
	[LandLordPostCode] [varchar](10) NULL,
	[LandLordContactTitle] [int] NULL,
	[LandLordContactForename] [varchar](50) NULL,
	[LandLordContactSurname] [varchar](50) NULL,
	[LandLordTelephoneNumber] [varchar](12) NULL,
	[LandLordFaxNumber] [varchar](12) NULL,
	[LandLordMobileNumber] [varchar](12) NULL,
	[LandLordEmailAddress] [varchar](100) NULL,
	[LandLordStartDate] [datetime] NULL,
	[LandLordEndDate] [datetime] NULL,
	[LandLordTerminationDate] [datetime] NULL,
	[LandLordExtended] [bit] NULL,
	[LandLordExtendedDate] [datetime] NULL,
	[LandLordNotes] [text] NULL,
	[RentOfficer] [int] NULL,
	[FinanceOfficer] [int] NULL,
	[DateRelinquished] [datetime] NULL,
	[DisabilityModifications] [int] NULL,
	[isRelinquished] [bit] NULL,
	[ContiguousBoundaryIsPrimary] [bit] NULL,
	[ContiguousBoundaryPrimaryUnitID] [varchar](13) NULL,
	[DecentHomeSurveyGeneratedDate] [datetime] NULL,
	[AsbestosTotalRisk] [int] NULL,
	[AsbestosMaterialAssessment] [int] NULL,
	[AsbestosPriorityAssessment] [int] NULL,
	[AsbestosSurveyDate] [datetime] NULL,
	[GroupHouseholdProperty] [bit] NULL,
	[HouseholdUnits] [int] NULL,
	[CPGPreOrPostReform] [int] NULL,
	[Association] [int] NULL,
	[OptedOut] [bit] NULL,
	[CaseManagementAgency] [int] NULL,
	[NRSCHHousingAgencnyIdentifier] [varchar](150) NULL,
	[NRSCHManagedByOther] [bit] NULL,
	[NRSCHManagingAgency] [varchar](150) NULL,
	[NRSCHRegisteredOwner] [varchar](150) NULL,
	[NRSCHStateVestedInterest] [bit] NULL,
	[NRSCHStateHoldsInterest] [int] NULL,
	[NRSCHAssetClass] [int] NULL,
	[NRSCHMaintenanceLiability] [int] NULL,
	[DecentHomeIndicator] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


