//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Work_Table
    {
        public decimal Activity_No { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<System.DateTime> Activity_Date { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public Nullable<int> Service_Prov_Position_ID { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<int> Organisation_ID { get; set; }
        public string Task_Type_Code { get; set; }
        public Nullable<byte> Indirect_Activity_Type_Code { get; set; }
        public Nullable<System.DateTimeOffset> Schedule_Time { get; set; }
        public Nullable<short> Schedule_Duration { get; set; }
        public Nullable<short> Activity_Duration { get; set; }
        public Nullable<decimal> Travel_Km { get; set; }
        public Nullable<short> Travel_Duration { get; set; }
        public Nullable<int> Allocated_Task_ID { get; set; }
        public Nullable<short> Compensible_Type_ID { get; set; }
        public Nullable<short> Funding_Prog_Code { get; set; }
        public Nullable<System.DateTimeOffset> Activity_Start_Time { get; set; }
        public Nullable<System.DateTimeOffset> Activity_End_Time { get; set; }
        public Nullable<int> Odometer_Reading { get; set; }
        public Nullable<decimal> Units_of_Service { get; set; }
        public Nullable<byte> On_Flag { get; set; }
        public Nullable<byte> Off_Flag { get; set; }
        public Nullable<byte> Format_OK { get; set; }
        public Nullable<byte> ComCare_Validation_OK { get; set; }
        public Nullable<byte> Payroll_Validation_OK { get; set; }
        public Nullable<byte> Verification_Required { get; set; }
        public Nullable<System.DateTimeOffset> Authorisation_Date { get; set; }
        public string Authorisation_Person { get; set; }
        public Nullable<byte> Actual_Service_Visit_No { get; set; }
        public Nullable<byte> Indirect_Activity_No { get; set; }
        public string Classn_Shift_Centre { get; set; }
        public Nullable<System.DateTimeOffset> Date_Extract_for_Payroll { get; set; }
        public Nullable<System.DateTime> Date_Upload_to_ComCare { get; set; }
        public System.DateTimeOffset Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTimeOffset> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<byte> Company_Vehicle { get; set; }
        public string Extracted_Funding_Prog_Code { get; set; }
        public Nullable<System.DateTimeOffset> Shift_Start_Time { get; set; }
        public Nullable<System.DateTimeOffset> Shift_End_Time { get; set; }
        public Nullable<int> PreAuthorise_Id { get; set; }
        public Nullable<int> Client_Casemix_Assignment_ID { get; set; }
        public string On_Call_Activity_Code { get; set; }
        public Nullable<int> WI_Record_ID { get; set; }
        public Nullable<decimal> Address_ID { get; set; }
        public Nullable<decimal> Schedule_Units_of_Service { get; set; }
        public Nullable<int> Interrupt_Duration { get; set; }
        public Nullable<int> Interrupted_Activity { get; set; }
        public string Registration_Number { get; set; }
        public Nullable<int> WI_Activity_ID { get; set; }
        public Nullable<bool> Cancelled_Visit { get; set; }
        public Nullable<int> Group_Activity_ID { get; set; }
        public Nullable<int> Student_Allocation_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> Internal_Task_Provider_ID { get; set; }
        public Nullable<int> Internal_Task_Working_Week_No { get; set; }
        public Nullable<System.DateTime> Internal_Task_From_Date { get; set; }
        public Nullable<int> CAP_ID { get; set; }
        public Nullable<short> User_Classification_ID { get; set; }
        public Nullable<decimal> Estimated_Travel_Km { get; set; }
        public Nullable<short> Estimated_Travel_Time { get; set; }
        public Nullable<bool> Client_Not_Home { get; set; }
        public Nullable<decimal> Destination_Address_ID { get; set; }
        public Nullable<short> Est_Intravisit_Travel_Km { get; set; }
        public Nullable<short> Actual_Intravisit_Travel_Km { get; set; }
        public Nullable<System.DateTimeOffset> Scheduled_Visit_End_Time { get; set; }
        public Nullable<bool> External_Provider { get; set; }
        public Nullable<decimal> Est_Visit_Charge { get; set; }
        public Nullable<byte> Visit_Cancel_Reason_ID { get; set; }
        public Nullable<int> Cancel_Recorded_Person_ID { get; set; }
        public Nullable<System.DateTimeOffset> Cancellation_Date { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Fee_Waived { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Person Person { get; set; }
        public virtual Indirect_Activity_Type Indirect_Activity_Type { get; set; }
        public virtual Task_Type Task_Type { get; set; }
    }
}
