//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Address1 = new HashSet<Address>();
            this.Period_of_Residency = new HashSet<Period_of_Residency>();
            this.Activity_Work_Table = new HashSet<Activity_Work_Table>();
        }
    
        public decimal Address_ID { get; set; }
        public Nullable<short> Abode_Type_Code { get; set; }
        public string Post_Code { get; set; }
        public decimal Suburb_ID { get; set; }
        public string Building_Name { get; set; }
        public string Dwelling_Number { get; set; }
        public string Street_or_PO_Box { get; set; }
        public string International_Address { get; set; }
        public string Access_Comments { get; set; }
        public string Nearest_Cross_Street { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<decimal> Org_Address_ID { get; set; }
        public string Location_Detail { get; set; }
        public string DPID { get; set; }
        public string Bar_Code { get; set; }
        public Nullable<int> Attachment_ID { get; set; }
        public string Att_File_Name { get; set; }
        public Nullable<decimal> xxxLat { get; set; }
        public Nullable<decimal> xxxLng { get; set; }
        public Nullable<byte> Accuracy { get; set; }
        public string xxxGMAP_Address { get; set; }
        public string xxxAddress_Type { get; set; }
        public string xxxLocation_Type { get; set; }
        public Nullable<int> xxxGMAP_Address_ID { get; set; }
        public Nullable<int> GM_Address_ID { get; set; }
        public string Additional_Addr_Line { get; set; }
        public string CRM_Reference_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address1 { get; set; }
        public virtual Address Address2 { get; set; }
        public virtual Suburb Suburb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Period_of_Residency> Period_of_Residency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Work_Table> Activity_Work_Table { get; set; }
    }
}
