//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.FC_Client_Contract = new HashSet<FC_Client_Contract>();
            this.FB_Client_Contract_Billing = new HashSet<FB_Client_Contract_Billing>();
        }
    
        public int Client_ID { get; set; }
        public Nullable<byte> Carer_Availability_Type_Code { get; set; }
        public Nullable<short> Old_Country_Code { get; set; }
        public Nullable<short> Old_Language_Code { get; set; }
        public Nullable<decimal> Organisation_ID { get; set; }
        public Nullable<byte> Old_Ethnicity_Class_Code { get; set; }
        public Nullable<System.DateTime> Spare { get; set; }
        public string URN { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<byte> Spare_1 { get; set; }
        public Nullable<int> ComCare_PID { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<decimal> Centre_ID { get; set; }
        public Nullable<short> Religion_Code { get; set; }
        public Nullable<byte> Carer_Residency_Status_Code { get; set; }
        public Nullable<byte> Pension_Benefit_Status_Code { get; set; }
        public Nullable<byte> Living_Arrangement_Type_Code { get; set; }
        public Nullable<short> Stream_Type_Code { get; set; }
        public Nullable<System.DateTime> Next_Hazax_Date { get; set; }
        public string IHI_Number { get; set; }
        public string IHI_Record_Status { get; set; }
        public string IHI_Status { get; set; }
        public Nullable<System.DateTimeOffset> IHI_Last_Updated_Date { get; set; }
        public string IHI_Status_Code { get; set; }
        public string IHI_Reason { get; set; }
        public string IHI_Severity { get; set; }
        public Nullable<bool> PCEHR_Exists { get; set; }
        public Nullable<System.DateTimeOffset> PCEHR_Last_Checked { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FC_Client_Contract> FC_Client_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_Contract_Billing> FB_Client_Contract_Billing { get; set; }
    }
}
