//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class extract_comcare_physicalContainer : DbContext
    {
        public extract_comcare_physicalContainer()
            : base("name=extract_comcare_physicalContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<FC_Account> FC_Account { get; set; }
        public virtual DbSet<FC_Client_Contract> FC_Client_Contract { get; set; }
        public virtual DbSet<FC_Transaction> FC_Transaction { get; set; }
        public virtual DbSet<FC_Transaction_Type> FC_Transaction_Type { get; set; }
        public virtual DbSet<Period_of_Residency> Period_of_Residency { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PT_Program> PT_Program { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Suburb> Suburbs { get; set; }
        public virtual DbSet<Activity_Work_Table> Activity_Work_Table { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Provider_Contract> Provider_Contract { get; set; }
        public virtual DbSet<Indirect_Activity_Type> Indirect_Activity_Type { get; set; }
        public virtual DbSet<Task_Type> Task_Type { get; set; }
        public virtual DbSet<FC_Account_Type> FC_Account_Type { get; set; }
        public virtual DbSet<FB_Client_CB_Split> FB_Client_CB_Split { get; set; }
        public virtual DbSet<FB_Client_Contract_Billed_To> FB_Client_Contract_Billed_To { get; set; }
        public virtual DbSet<FB_Client_Contract_Billing> FB_Client_Contract_Billing { get; set; }
    }
}
