//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_Client_Contract_Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FB_Client_Contract_Billing()
        {
            this.FB_Client_Contract_Billed_To = new HashSet<FB_Client_Contract_Billed_To>();
        }
    
        public decimal Client_CB_ID { get; set; }
        public int Client_ID { get; set; }
        public decimal Funder_Contract_ID { get; set; }
        public Nullable<decimal> Billing_Rate_Classification_ID { get; set; }
        public Nullable<int> Primary_Signatory_ID { get; set; }
        public Nullable<int> Secondary_Signatory_ID { get; set; }
        public byte Contract_Billing_Group_ID { get; set; }
        public Nullable<decimal> Billing_Cap { get; set; }
        public System.DateTime Billing_Start_Date { get; set; }
        public Nullable<System.DateTime> Billing_End_Date { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public string Billing_Reference { get; set; }
        public Nullable<bool> Insurance_Claim { get; set; }
        public Nullable<System.DateTime> Actual_Admission_Date { get; set; }
        public Nullable<System.DateTime> Proposed_Discharged_Date { get; set; }
        public Nullable<System.DateTime> Contract_Date { get; set; }
        public string Billing_Number { get; set; }
        public Nullable<bool> Assessed_As_Couple { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public decimal Contract_Billing_ID { get; set; }
        public Nullable<bool> Information_Sharing_Indicator { get; set; }
        public Nullable<System.DateTime> Review_Date { get; set; }
        public Nullable<decimal> Bill_From_Organisation_ID { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_Contract_Billed_To> FB_Client_Contract_Billed_To { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
