//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_Client_CB_Split
    {
        public decimal Client_CB_Split_ID { get; set; }
        public decimal Client_Contract_Billed_To_ID { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public Nullable<decimal> Organisation_ID { get; set; }
        public decimal Split_Percentage { get; set; }
        public Nullable<bool> Direct_Debit { get; set; }
        public Nullable<bool> Statement_Exempt { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public string Debtor_ID { get; set; }
    
        public virtual FB_Client_Contract_Billed_To FB_Client_Contract_Billed_To { get; set; }
        public virtual Person Person { get; set; }
    }
}
