//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_Client_Contract_Billed_To
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FB_Client_Contract_Billed_To()
        {
            this.FB_Client_CB_Split = new HashSet<FB_Client_CB_Split>();
        }
    
        public decimal Client_Contract_Billed_To_ID { get; set; }
        public decimal Client_CB_ID { get; set; }
        public System.DateTime Effective_From_Date { get; set; }
        public Nullable<System.DateTime> Effective_To_Date { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_CB_Split> FB_Client_CB_Split { get; set; }
        public virtual FB_Client_Contract_Billing FB_Client_Contract_Billing { get; set; }
    }
}
