//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FC_Account()
        {
            this.FC_Transaction = new HashSet<FC_Transaction>();
        }
    
        public decimal FC_Account_ID { get; set; }
        public Nullable<decimal> Client_Contract_ID { get; set; }
        public decimal FC_Account_Type_ID { get; set; }
        public string Account_Code { get; set; }
        public Nullable<decimal> Actual_Balance { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
    
        public virtual FC_Client_Contract FC_Client_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FC_Transaction> FC_Transaction { get; set; }
        public virtual FC_Account_Type FC_Account_Type { get; set; }
    }
}
