//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Account_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FC_Account_Type()
        {
            this.FC_Account = new HashSet<FC_Account>();
        }
    
        public decimal FC_Account_Type_ID { get; set; }
        public decimal Funding_Care_Model_ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Print_On_Statement { get; set; }
        public System.DateTime Effective_From_Date { get; set; }
        public Nullable<System.DateTime> Effective_To_Date { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<bool> Account_Automatic_Creation { get; set; }
        public Nullable<bool> Is_Contigency_Account { get; set; }
        public string EOS_Code { get; set; }
        public Nullable<bool> Default_Account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FC_Account> FC_Account { get; set; }
    }
}
