//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Client_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FC_Client_Contract()
        {
            this.FC_Account = new HashSet<FC_Account>();
        }
    
        public decimal Client_Contract_ID { get; set; }
        public decimal Funder_Contract_ID { get; set; }
        public Nullable<decimal> Program_ID { get; set; }
        public int Client_ID { get; set; }
        public Nullable<bool> Funded_Indicator { get; set; }
        public string Govt_Recipient_ID { get; set; }
        public Nullable<System.DateTime> Start_Date_of_Claim { get; set; }
        public Nullable<System.DateTime> End_Date_of_Claim { get; set; }
        public Nullable<System.DateTime> ACAT_Assessment_Date { get; set; }
        public Nullable<System.DateTime> ACAT_Expiry_Date { get; set; }
        public string ACAT_Level { get; set; }
        public System.DateTime Effective_From_Date { get; set; }
        public Nullable<System.DateTime> Effective_To_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public Nullable<decimal> FC_Service_Delivery_Outcome_ID { get; set; }
        public Nullable<decimal> Amount_Transferred_In { get; set; }
        public Nullable<decimal> Amount_Transferred_Out { get; set; }
        public Nullable<decimal> Overhead_Rate_Percentage { get; set; }
        public Nullable<System.DateTime> Entry_To_Care { get; set; }
        public Nullable<decimal> Program_Level_ID { get; set; }
        public Nullable<bool> Record_In_Error { get; set; }
        public Nullable<decimal> FC_Care_Rating_ID { get; set; }
        public Nullable<decimal> Amount_Transferred_In_Client { get; set; }
        public Nullable<decimal> Amount_Transferred_Out_Client { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FC_Account> FC_Account { get; set; }
        public virtual PT_Program PT_Program { get; set; }
    }
}
