//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Transaction_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FC_Transaction_Type()
        {
            this.FC_Transaction = new HashSet<FC_Transaction>();
        }
    
        public byte FC_Transaction_Type_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Effective_From_Date { get; set; }
        public Nullable<System.DateTime> Effective_To_Date { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<int> Statement_Display_Order { get; set; }
        public Nullable<bool> Print_Statement_If_Transaction_Present { get; set; }
        public Nullable<bool> Print_On_Statement { get; set; }
        public string Transaction_Type_Category_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FC_Transaction> FC_Transaction { get; set; }
    }
}
