//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Transaction
    {
        public decimal FC_Transaction_ID { get; set; }
        public Nullable<System.Guid> Unique_Identifier { get; set; }
        public decimal FC_Account_ID { get; set; }
        public byte FC_Transaction_Type_ID { get; set; }
        public string Account_Code { get; set; }
        public string Transaction_Source { get; set; }
        public Nullable<System.DateTime> Activity_Date { get; set; }
        public string Activity_Type { get; set; }
        public Nullable<decimal> Estimated_Amount { get; set; }
        public Nullable<decimal> Actual_Amount { get; set; }
        public Nullable<decimal> Balance_After_Txn { get; set; }
        public string Comments { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public string Source_Table { get; set; }
        public string Source_Record_Key { get; set; }
        public Nullable<decimal> FC_Product_ID { get; set; }
        public Nullable<decimal> Funding_Care_Model_Period_ID { get; set; }
        public Nullable<decimal> Statement_Closing_Balance { get; set; }
        public Nullable<decimal> Overhead_Client_Supplement_ID { get; set; }
        public Nullable<byte> FC_Supplement_Type_ID { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> Exported_Date { get; set; }
    
        public virtual FC_Account FC_Account { get; set; }
        public virtual FC_Transaction_Type FC_Transaction_Type { get; set; }
    }
}
