//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indirect_Activity_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indirect_Activity_Type()
        {
            this.Activity_Work_Table = new HashSet<Activity_Work_Table>();
        }
    
        public byte Indirect_Activity_Type_Code { get; set; }
        public string Description { get; set; }
        public string Short_Description { get; set; }
        public Nullable<bool> Internal_Task { get; set; }
        public Nullable<System.DateTime> Effective_Date_From { get; set; }
        public Nullable<System.DateTime> Effective_Date_To { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Work_Table> Activity_Work_Table { get; set; }
    }
}
