//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Period_of_Residency = new HashSet<Period_of_Residency>();
            this.Activity_Work_Table = new HashSet<Activity_Work_Table>();
            this.FB_Client_CB_Split = new HashSet<FB_Client_CB_Split>();
            this.FB_Client_Contract_Billing = new HashSet<FB_Client_Contract_Billing>();
            this.FB_Client_Contract_Billing1 = new HashSet<FB_Client_Contract_Billing>();
        }
    
        public int Person_ID { get; set; }
        public string Title_Code { get; set; }
        public Nullable<byte> Gender_Code { get; set; }
        public string Given_Names { get; set; }
        public string Last_Name { get; set; }
        public string Preferred_Name { get; set; }
        public string Salutation { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Sold_To_Account_Code { get; set; }
        public string Bill_To_Account_Code { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<System.DateTimeOffset> Deceased_Date { get; set; }
        public Nullable<short> Country_Code { get; set; }
        public Nullable<short> Language_Code { get; set; }
        public Nullable<byte> Ethnicity_Class_Code { get; set; }
        public Nullable<bool> Estimated_DOB_Flag { get; set; }
        public Nullable<int> Attachment_ID { get; set; }
        public Nullable<byte> Employment_Status_ID { get; set; }
        public Nullable<byte> Marital_Status_ID { get; set; }
        public Nullable<bool> Dummy_PID { get; set; }
        public Nullable<decimal> FS_Blob_ID { get; set; }
        public string BPAY_ID { get; set; }
        public string POSTPAY_ID { get; set; }
        public string Source_System_Person_ID { get; set; }
        public string Source_System { get; set; }
        public Nullable<byte> Interpreter_Status_ID { get; set; }
        public Nullable<bool> Family_PID { get; set; }
        public string CRM_Reference_1 { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Period_of_Residency> Period_of_Residency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Work_Table> Activity_Work_Table { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Provider Provider1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_CB_Split> FB_Client_CB_Split { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_Contract_Billing> FB_Client_Contract_Billing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_Contract_Billing> FB_Client_Contract_Billing1 { get; set; }
    }
}
