//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.Provider_Contract = new HashSet<Provider_Contract>();
            this.FB_Client_Contract_Billing = new HashSet<FB_Client_Contract_Billing>();
        }
    
        public int Provider_ID { get; set; }
        public string ComCare_Provider_No { get; set; }
        public string Employee_No { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Trainer { get; set; }
        public string HPII_Number { get; set; }
        public Nullable<System.DateTimeOffset> HPII_Last_Updated_Date { get; set; }
        public Nullable<decimal> Working_Hour_ID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider_Contract> Provider_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FB_Client_Contract_Billing> FB_Client_Contract_Billing { get; set; }
    }
}
