//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Contract
    {
        public int Provider_ID { get; set; }
        public byte Provider_Contract_Type_Code { get; set; }
        public System.DateTime Effective_Date_From { get; set; }
        public Nullable<decimal> Working_Week_No { get; set; }
        public Nullable<System.DateTime> Effective_Date_To { get; set; }
        public Nullable<decimal> Minimum_Daily_Hours { get; set; }
        public Nullable<decimal> Maximum_Daily_Hours { get; set; }
        public Nullable<decimal> Minimum_Period_Hours { get; set; }
        public Nullable<decimal> Maximum_Period_Hours { get; set; }
        public string Comment { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public string Provider_Class_Code { get; set; }
        public Nullable<decimal> Organisation_ID { get; set; }
        public Nullable<decimal> Agency_Organisation_ID { get; set; }
        public Nullable<decimal> Centre_ID { get; set; }
        public Nullable<short> Team_No { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
