//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suburb()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public decimal Suburb_ID { get; set; }
        public string HACC_Region_Code { get; set; }
        public string Post_Code { get; set; }
        public Nullable<byte> ASGC_State_Code { get; set; }
        public Nullable<int> ASGC_Division_Code { get; set; }
        public Nullable<int> ASGC_Sub_Divison_Code { get; set; }
        public Nullable<int> ASGC_SLA_Code { get; set; }
        public Nullable<byte> State_Code { get; set; }
        public string Suburb_Name { get; set; }
        public Nullable<System.DateTime> Effective_From_Date { get; set; }
        public Nullable<System.DateTime> Effective_To_Date { get; set; }
        public Nullable<decimal> xxxLat { get; set; }
        public Nullable<decimal> xxxLng { get; set; }
        public Nullable<byte> Accuracy { get; set; }
        public string GMAP_Address { get; set; }
        public string Address_Type { get; set; }
        public string Location_Type { get; set; }
        public string ISO_3Alpha_Country_Code { get; set; }
        public string Time_Zone_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual State State { get; set; }
    }
}
