//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_Type()
        {
            this.Activity_Work_Table = new HashSet<Activity_Work_Table>();
        }
    
        public string Task_Type_Code { get; set; }
        public string Service_Type_Code { get; set; }
        public Nullable<byte> Display_Sequence { get; set; }
        public string Description { get; set; }
        public System.DateTime Effective_Date { get; set; }
        public Nullable<System.DateTime> Withdrawn_Date { get; set; }
        public string Visit_Indicator { get; set; }
        public string Funding_Required { get; set; }
        public string Short_Description { get; set; }
        public string Penalty_Rate_Apply { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Creator_User_Name { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public string Last_Modified_User_Name { get; set; }
        public Nullable<bool> Valid_Interruption { get; set; }
        public Nullable<bool> Include_in_Claim { get; set; }
        public Nullable<bool> Group_Activity_Task_Ind { get; set; }
        public string Preferred_Provider_Class_Code { get; set; }
        public Nullable<bool> Out_Of_Home { get; set; }
        public Nullable<bool> Transport_Ind { get; set; }
        public string Unit_Description { get; set; }
        public Nullable<bool> Allow_Optional_Travel { get; set; }
        public Nullable<bool> Use_Round_Rostering_Allocation { get; set; }
        public Nullable<bool> Use_CSA_Allocation { get; set; }
        public Nullable<int> Alarm_Visit_Start_Delay { get; set; }
        public Nullable<int> Alarm_Visit_End_Delay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Work_Table> Activity_Work_Table { get; set; }
    }
}
