//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_transactions_fact
    {
        public int customer_transaction_key { get; set; }
        public int customer_key { get; set; }
        public int date_key { get; set; }
        public int transaction_type_key { get; set; }
        public int program_key { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string comment { get; set; }
        public string description { get; set; }
        public string commnets { get; set; }
        public int responsible_party_key { get; set; }
        public string comments { get; set; }
    
        public virtual customer_dim customer_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual transaction_type_dim transaction_type_dim { get; set; }
        public virtual responsible_party_dim responsible_party_dim { get; set; }
    }
}
