//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class date_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public date_dim()
        {
            this.customer_transactions_fact = new HashSet<customer_transactions_fact>();
        }
    
        public int date_key { get; set; }
        public Nullable<System.DateTime> full_date { get; set; }
        public string display_date { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> quarter { get; set; }
        public string quarter_name { get; set; }
        public Nullable<int> month_no { get; set; }
        public string month_name { get; set; }
        public Nullable<int> day_of_month { get; set; }
        public Nullable<int> day_of_week { get; set; }
        public string day_name { get; set; }
        public string is_public_holiday { get; set; }
        public string public_holiday_name { get; set; }
        public string financial_year { get; set; }
        public string fbt_range { get; set; }
        public string pay_period_end { get; set; }
        public Nullable<int> financial_month_no { get; set; }
        public Nullable<decimal> max_temperature { get; set; }
        public Nullable<decimal> min_temperature { get; set; }
        public Nullable<decimal> rainfall { get; set; }
        public Nullable<decimal> max_wind_speed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_transactions_fact> customer_transactions_fact { get; set; }
    }
}
