//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_dim()
        {
            this.employee_payment_fact = new HashSet<employee_payment_fact>();
            this.employee_timesheet_fact = new HashSet<employee_timesheet_fact>();
        }
    
        public int account_key { get; set; }
        public string ledger_name { get; set; }
        public string account_number_raw { get; set; }
        public string account_number { get; set; }
        public string short_description { get; set; }
        public string description { get; set; }
        public string entity { get; set; }
        public string cost_centre { get; set; }
        public string activity_account { get; set; }
        public string natural_account { get; set; }
        public string account_type { get; set; }
        public string status { get; set; }
        public string entity_description { get; set; }
        public string cost_centre_description { get; set; }
        public string activity_account_description { get; set; }
        public string natural_account_description { get; set; }
        public string account_type_description { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_payment_fact> employee_payment_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet_fact> employee_timesheet_fact { get; set; }
    }
}
