//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_leave_snapshot_fact
    {
        public int employee_leave_snapshot_key { get; set; }
        public int date_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int leave_type_key { get; set; }
        public Nullable<decimal> leave_taken_permanent_ft { get; set; }
        public Nullable<decimal> leave_taken_permanent_pt { get; set; }
        public Nullable<decimal> leave_taken_contract_ft { get; set; }
        public Nullable<decimal> leave_taken_contract_pt { get; set; }
        public Nullable<decimal> leave_taken_casual { get; set; }
        public Nullable<decimal> leave_booked_permanent_ft { get; set; }
        public Nullable<decimal> leave_booked_permanent_pt { get; set; }
        public Nullable<decimal> leave_booked_contract_ft { get; set; }
        public Nullable<decimal> leave_booked_contract_pt { get; set; }
        public Nullable<decimal> leave_booked_casual { get; set; }
        public Nullable<int> employee_count { get; set; }
    
        public virtual date_dim date_dim { get; set; }
        public virtual leave_type_dim leave_type_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
    }
}
