//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_working_hours_fact
    {
        public int employee_working_hours_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int position_key { get; set; }
        public int employee_key { get; set; }
        public int date_key { get; set; }
        public int leave_type_key { get; set; }
        public int payment_type_key { get; set; }
        public Nullable<decimal> working_hours { get; set; }
        public Nullable<decimal> paid_leave_hours { get; set; }
        public Nullable<decimal> unpaid_leave_hours { get; set; }
        public int employee_dim_employee_key { get; set; }
        public int portfolio_dim_portfolio_key { get; set; }
        public int service_stream_dim_service_stream_key { get; set; }
        public int program_dim_program_key { get; set; }
        public int position_dim_position_key { get; set; }
        public int employee_dim_employee_key1 { get; set; }
        public int date_dim_date_key { get; set; }
        public int leave_type_dim_leave_type_key { get; set; }
        public int payment_type_dim_payment_type_key { get; set; }
    
        public virtual employee_dim employee_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual position_dim position_dim { get; set; }
        public virtual employee_dim employee_dim1 { get; set; }
        public virtual date_dim date_dim { get; set; }
        public virtual leave_type_dim leave_type_dim { get; set; }
        public virtual payment_type_dim payment_type_dim { get; set; }
    }
}
