//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hris_conceptualContainer : DbContext
    {
        public hris_conceptualContainer()
            : base("name=hris_conceptualContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_dim> account_dim { get; set; }
        public virtual DbSet<accreditation_dim> accreditation_dim { get; set; }
        public virtual DbSet<date_dim> date_dim { get; set; }
        public virtual DbSet<employee_accreditation_fact> employee_accreditation_fact { get; set; }
        public virtual DbSet<employee_benefit_dim> employee_benefit_dim { get; set; }
        public virtual DbSet<employee_contract_fact> employee_contract_fact { get; set; }
        public virtual DbSet<employee_dim> employee_dim { get; set; }
        public virtual DbSet<employee_leave_accrued_fact> employee_leave_accrued_fact { get; set; }
        public virtual DbSet<employee_leave_booked_fact> employee_leave_booked_fact { get; set; }
        public virtual DbSet<employee_leave_booked_txn_fact> employee_leave_booked_txn_fact { get; set; }
        public virtual DbSet<employee_leave_snapshot_fact> employee_leave_snapshot_fact { get; set; }
        public virtual DbSet<employee_leave_taken_fact> employee_leave_taken_fact { get; set; }
        public virtual DbSet<employee_payment_dim> employee_payment_dim { get; set; }
        public virtual DbSet<employee_payment_fact> employee_payment_fact { get; set; }
        public virtual DbSet<employee_position_fact> employee_position_fact { get; set; }
        public virtual DbSet<employee_profile_fact> employee_profile_fact { get; set; }
        public virtual DbSet<employee_recruitment_fact> employee_recruitment_fact { get; set; }
        public virtual DbSet<employee_renumeration_fact> employee_renumeration_fact { get; set; }
        public virtual DbSet<employee_termination_fact> employee_termination_fact { get; set; }
        public virtual DbSet<employee_timesheet_fact> employee_timesheet_fact { get; set; }
        public virtual DbSet<item_dim> item_dim { get; set; }
        public virtual DbSet<labour_turnover_fact> labour_turnover_fact { get; set; }
        public virtual DbSet<leave_type_dim> leave_type_dim { get; set; }
        public virtual DbSet<month_dim> month_dim { get; set; }
        public virtual DbSet<organisation_dim> organisation_dim { get; set; }
        public virtual DbSet<payment_type_dim> payment_type_dim { get; set; }
        public virtual DbSet<portfolio_dim> portfolio_dim { get; set; }
        public virtual DbSet<position_dim> position_dim { get; set; }
        public virtual DbSet<program_dim> program_dim { get; set; }
        public virtual DbSet<salary_code_dim> salary_code_dim { get; set; }
        public virtual DbSet<service_stream_dim> service_stream_dim { get; set; }
        public virtual DbSet<work_pattern_fact> work_pattern_fact { get; set; }
        public virtual DbSet<timesheet_validation_fact> timesheet_validation_fact { get; set; }
        public virtual DbSet<employee_working_hours_fact> employee_working_hours_fact { get; set; }
        public virtual DbSet<employee_last_paid_date_fact> employee_last_paid_date_fact { get; set; }
        public virtual DbSet<personalleave_usage_report_fact> personalleave_usage_report_fact { get; set; }
        public virtual DbSet<position_establishment_fact> position_establishment_fact { get; set; }
        public virtual DbSet<all_employees_report_fact> all_employees_report_fact { get; set; }
        public virtual DbSet<labour_turnover_fact1> labour_turnover_fact1 { get; set; }
        public virtual DbSet<labour_turnover_report_fact> labour_turnover_report_fact { get; set; }
        public virtual DbSet<personalleave_usage_report_fact1> personalleave_usage_report_fact1 { get; set; }
    }
}
