//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class labour_turnover_fact1
    {
        public int labour_turnover_key { get; set; }
        public int month_date_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public Nullable<int> permanent_ft_total { get; set; }
        public Nullable<int> permanent_pt_total { get; set; }
        public Nullable<int> contract_ft_total { get; set; }
        public Nullable<int> contract_pt_total { get; set; }
        public Nullable<int> casual_total { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> permanent_ft_lost { get; set; }
        public Nullable<int> permanent_pt_lost { get; set; }
        public Nullable<int> contract_ft_lost { get; set; }
        public Nullable<int> contract_pt_lost { get; set; }
        public Nullable<int> casual_lost { get; set; }
        public Nullable<int> total_lost { get; set; }
        public Nullable<decimal> permanent_ft_turnover { get; set; }
        public Nullable<decimal> permanent_pt_turnover { get; set; }
        public Nullable<decimal> contract_ft_turnover { get; set; }
        public Nullable<decimal> contract_pt_turnover { get; set; }
        public Nullable<decimal> casual_turnover { get; set; }
        public Nullable<decimal> total_turnover { get; set; }
    }
}
