//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_establishment_fact
    {
        public int position_establishment_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int position_key { get; set; }
        public int employee_key { get; set; }
        public string employee_type { get; set; }
        public string employee_class { get; set; }
        public int effective_date_key { get; set; }
        public int vacant_date_key { get; set; }
        public int manager_key { get; set; }
        public int manager_position_key { get; set; }
        public string position_emp_type { get; set; }
        public string position_emp_class { get; set; }
        public Nullable<int> count { get; set; }
    }
}
