//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class probation_monitoring_fact
    {
        public int probation_monitoring_key { get; set; }
        public int probation_end_date_key { get; set; }
        public int employee_key { get; set; }
        public int organisation_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
    
        public virtual date_dim date_dim { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual organisation_dim organisation_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
    }
}
