//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_validation_fact
    {
        public int timesheet_validation_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int position_key { get; set; }
        public int employee_key { get; set; }
        public int manager_key { get; set; }
        public int manager_position_key { get; set; }
        public int activity_date_key { get; set; }
        public string validation_type { get; set; }
        public int activity1_start_time { get; set; }
        public int activity1_end_time { get; set; }
        public string activity1_cost_centre { get; set; }
        public string activity1_activity_code { get; set; }
        public string activity1_activity_desc { get; set; }
        public Nullable<int> activity2_start_time { get; set; }
        public Nullable<int> activity2_end_time { get; set; }
        public string activity2_cost_centre { get; set; }
        public string activity2_activity_code { get; set; }
        public string activity2_activity_desc { get; set; }
        public int portfolio_dim_portfolio_key { get; set; }
        public int service_stream_dim_service_stream_key { get; set; }
        public int program_dim_program_key { get; set; }
        public int position_dim_position_key { get; set; }
        public int employee_dim_employee_key { get; set; }
        public int date_dim_date_key { get; set; }
    
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual position_dim position_dim { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
    }
}
