
-- --------------------------------------------------
-- creating all tables
-- --------------------------------------------------

-- creating table 'hrsys_hierarch_ctl'
create table extract.[hrsys_hierarch_ctl] (
    [company_code] int  not null,
    [hierarchy_type] varchar(10)  not null,
    [hierarchy_code] varchar(10)  not null,
    [hierarchy_descr] varchar(50)  null,
    [parent_node] varchar(10)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [comments] varchar(255)  null,
    [status] varchar(10)  null,
    [pos_profile_code] varchar(10)  null,
    [pos_profile_ovr_ind] varchar(1)  null,
    [last_publish_date] datetime  null
);
go

-- creating table 'hrsys_hierarch_itm'
create table extract.[hrsys_hierarch_itm] (
    [company_code] int  null,
    [hierarchy_type] varchar(10)  null,
    [hierarchy_code] varchar(10)  null,
    [parent_type] varchar(10)  null,
    [parent_node] varchar(10)  null,
    [tree_index] varchar(40)  not null,
    [parent_index] varchar(40)  null,
    [current_level] int  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [org_key] varchar(40)  null,
    [seq_num] int  null,
    [parent_num] int  not null
);
go

-- creating table 'hrsys_hierarch_lvl'
create table extract.[hrsys_hierarch_lvl] (
    [company_code] int  not null,
    [hierarchy_type] varchar(10)  not null,
    [hierarchy_level] int  not null,
    [level_desc] varchar(50)  null,
    [comments] varchar(255)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [techone_fld1] varchar(40)  null,
    [techone_fld2] varchar(40)  null,
    [techone_fld3] varchar(40)  null,
    [techone_fld4] varchar(40)  null,
    [techone_fld5] varchar(40)  null
);
go

-- creating table 'hrhmn_empl_job_ctl'
create table extract.[hrhmn_empl_job_ctl] (
    [id_number] int  not null,
    [effective_date] datetime  not null,
    [job_dtl_title] varchar(50)  null,
    [reason_type] varchar(10)  null,
    [reason_descr] varchar(50)  null,
    [company_code] int  null,
    [date_hired] datetime  null,
    [probatn_period_end] datetime  null,
    [next_review_date] datetime  null,
    [empl_type_code] varchar(10)  null,
    [empl_class] varchar(10)  null,
    [holiday_ctgy] varchar(10)  null,
    [pay_basis_code] varchar(10)  null,
    [pay_doc_type] varchar(1)  null,
    [pay_period_type] varchar(10)  null,
    [pay_location] varchar(10)  null,
    [payadv_trans_meth] varchar(10)  null,
    [payadv_address] varchar(1)  null,
    [techone_fld1] varchar(40)  null,
    [techone_fld2] varchar(40)  null,
    [techone_fld3] varchar(40)  null,
    [techone_fld4] varchar(40)  null,
    [row_status] int  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [end_date] datetime  null,
    [increment_ind] varchar(1)  null,
    [payroll_tax_state] varchar(10)  null,
    [workcover_tax_state] varchar(10)  null,
    [region_code] varchar(20)  null,
    [id_class] varchar(10)  null,
    [tlt_mgt_system_code] varchar(10)  null,
    [apprs_cycle_code] varchar(10)  null,
    [probatn_generate_ind] varchar(1)  null,
    [probatn_position_profile] varchar(10)  null,
    [probatn_period_start] datetime  null,
    [probatn_emplplan_id] int  null,
    [probatn_comp_ind] varchar(1)  null,
    [probatn_otcm_code] varchar(10)  null,
    [probatn_tlt_mgt_system] varchar(10)  null,
    [probatn_apprs_meth_code] varchar(10)  null
);
go

-- creating table 'hrhmn_empl_job_pos'
create table extract.[hrhmn_empl_job_pos] (
    [id_number] int  not null,
    [effective_date] datetime  not null,
    [position_code] varchar(10)  not null,
    [position_type_ind] varchar(1)  null,
    [end_date] datetime  null,
    [job_pos_title] varchar(50)  null,
    [reason_type] varchar(10)  null,
    [reason_descr] varchar(50)  null,
    [department_code] varchar(10)  null,
    [id_number_supervsr] int  null,
    [work_group] varchar(10)  null,
    [work_location] varchar(10)  null,
    [empl_cond_award] varchar(10)  null,
    [empl_cond_grade] varchar(10)  null,
    [empl_cond_level] varchar(10)  null,
    [ent_tech_key] int  null,
    [trade_code] varchar(10)  null,
    [union_code] varchar(10)  null,
    [season_status] int  null,
    [supervisor_ind] varchar(1)  null,
    [tradesman_ind] varchar(1)  null,
    [tmc_sequence_no] int  null,
    [tmc_calc_method] varchar(10)  null,
    [tmc_leave_rule] varchar(1)  null,
    [recov_item_type] varchar(10)  null,
    [recov_item_code] varchar(10)  null,
    [oncrecov_item_type] varchar(10)  null,
    [oncrecov_item_code] varchar(10)  null,
    [cost_type] varchar(4)  null,
    [cost_code] varchar(4)  null,
    [ts_system_name] varchar(10)  null,
    [ts_fmt_name] varchar(10)  null,
    [ts_entry_ind] varchar(1)  null,
    [techone_fld1] varchar(40)  null,
    [techone_fld2] varchar(40)  null,
    [techone_fld3] varchar(40)  null,
    [techone_fld4] varchar(40)  null,
    [row_status] int  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [org_unit_code] varchar(10)  null,
    [position_supervsr] varchar(10)  null,
    [full_time_equivalent] decimal(18,6)  null,
    [increment_ind] varchar(1)  null,
    [home_cost_centre] varchar(10)  null,
    [disb_code] varchar(10)  null,
    [security_profile_name] varchar(50)  null,
    [hrhmn_empl_refid_number] int  null
);
go

-- creating table 'hrhmn_empl_ref'
create table extract.[hrhmn_empl_ref] (
    [id_number] int  not null,
    [family_name] varchar(50)  null,
    [given_name] varchar(50)  null,
    [other_given_name] varchar(50)  null,
    [date_of_birth] datetime  null,
    [alias_name] varchar(50)  null,
    [marital_status_cde] varchar(10)  null,
    [gender_code] varchar(10)  null,
    [addrss_postal_code] int  null,
    [addrss_street_code] int  null,
    [id_class] varchar(10)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [rehire_ind] varchar(1)  null,
    [active_ind] varchar(1)  null,
    [empl_nationality] varchar(10)  null,
    [ethnic_group] varchar(10)  null,
    [main_language] varchar(10)  null,
    [empl_disability] varchar(10)  null,
    [empl_id_code] varchar(14)  null,
    [user_id] varchar(14)  null,
    [ent_tech_key] int  null,
    [reempl_code] varchar(20)  null,
    [last_term_datei] datetime  null,
    [salutation] varchar(20)  null,
    [previous_name] varchar(50)  null,
    [resident_status] varchar(20)  null,
    [visa_type] varchar(20)  null,
    [previous_given_name] varchar(50)  null,
    [previous_other_given_name] varchar(50)  null,
    [next_emplplan_start_date] datetime  null,
    [last_emplapprs_id] int  null,
    [last_emplapprs_start_date] datetime  null,
    [last_emplapprs_end_date] datetime  null,
    [tlt_mgt_system_code] varchar(10)  null,
    [rating_profile_code] varchar(10)  null,
    [last_rating_code] varchar(10)  null,
    [last_rating_calc_score] decimal(10,6)  null
);
go

-- creating table 'hrhmn_emplterm_dtl'
create table [extract].[hrhmn_emplterm_dtl] (
    [id_number] int  not null,
    [term_code] varchar(10)  null,
    [term_reason] varchar(99)  null,
    [term_date] datetime  not null,
    [term_removal_date] datetime  null,
    [id_number_term_by] int  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [gen_act_key] varchar(40)  null,
    [term_type] varchar(10)  null
);
go

-- creating table 'hrhmn_qual_ref'
create table [extract].[hrhmn_qual_ref] (
    [qual_code] varchar(10)  not null,
    [qual_desc] varchar(50)  null,
    [issuing_instituton] varchar(50)  null,
    [country_code] varchar(10)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [qual_type] varchar(10)  null,
    [expiry_type] varchar(10)  null,
    [expiry_period] decimal(18,6)  null,
    [comments] varchar(1000)  null,
    [qual_category] varchar(1)  null,
    [empl_expiring_alert_days] int  null,
    [mgr_expiring_alert_days] int  null,
    [hr_expiring_alert_days] int  null
);
go
-- creating table 'hrhmn_emplqual_dtl'
create table [extract].[hrhmn_emplqual_dtl] (
    [id_number] int  not null,
    [qual_code] varchar(10)  not null,
    [qual_issue_date] datetime  null,
    [serial_number] varchar(20)  null,
    [qual_cancel_date] datetime  null,
    [extend_qual_desc] varchar(50)  null,
    [qual_level] varchar(50)  null,
    [year_graduated] int  null,
    [remarks] varchar(1000)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [status] varchar(2)  null,
    [source_type] varchar(2)  null,
    [source_id] varchar(20)  null,
    [qual_expiry_datei] datetime  null,
    [qual_target_datei] datetime  null,
    [inst_company_code] int  null,
    [emplqual_seq_no] int  not null,
    [superseded_ind] varchar(1)  null,
    [emplqual_status] varchar(1)  null,
    [emplqual_cancel_status] varchar(1)  null,
    [cancel_source_type] varchar(2)  null,
    [wrkflw_system] varchar(10)  null,
    [wrkflw_name] varchar(15)  null,
    [cancel_wrkflw_system] varchar(10)  null,
    [cancel_wrkflw_name] varchar(15)  null,
    [original_id_number] int  null
);
go

-- creating table 'hrpay_leave_ctl'
create table [extract].[hrpay_leave_ctl] (
    [leave_ctl_type] varchar(10)  not null,
    [id_number] int  not null,
    [leave_start_date] datetime  not null,
    [leave_end_date] datetime  null,
    [pay_component_ref] decimal(10,4)  null,
    [pay_period_date] datetime  null,
    [company_code] int  null,
    [doc_type_code] varchar(10)  null,
    [tmc_seq_number] int  null,
    [number_of_weeks] decimal(10,4)  null,
    [id_number_apprvng] int  null,
    [leave_descr] varchar(50)  null,
    [orig_auth_code] varchar(8)  null,
    [last_auth_code] varchar(8)  null,
    [refer_auth_code] varchar(8)  null,
    [last_auth_seqnbr] int  null,
    [auth_status] varchar(1)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [leave_status] varchar(2)  null,
    [leave_sub_status] varchar(2)  null,
    [ldg_code] varchar(2)  null,
    [accnbri] varchar(32)  null,
    [position_code] varchar(10)  null,
    [reference_nbr] varchar(40)  null,
    [leave_status_user_id] varchar(14)  null,
    [leave_status_comment] varchar(255)  null,
    [leave_seq_nbr] smallint  not null,
    [reversing_leave_seq_nbr] smallint  null
);
go

-- creating table 'hrpay_leave_dtl'
create table [extract].[hrpay_leave_dtl] (
    [id_number] int  not null,
    [pay_period_date] datetime  not null,
    [company_code] int  null,
    [doc_type_code] varchar(10)  null,
    [leave_start_date] datetime  null,
    [leave_end_date] datetime  null,
    [termination_date] datetime  null,
    [hourly_rate] decimal(14,4)  null,
    [use_annual_leave] varchar(1)  null,
    [use_lsl] varchar(1)  null,
    [al_93_hrs_accrued] decimal(10,4)  null,
    [al_93_hrs_accrual] decimal(10,4)  null,
    [al_93_amount] decimal(14,4)  null,
    [al_93_tax] decimal(14,4)  null,
    [al_hours_accrued] decimal(10,4)  null,
    [al_hours_accrual] decimal(10,4)  null,
    [al_hours_prorata] decimal(14,4)  null,
    [al_amount] decimal(14,4)  null,
    [tt_hours_accrued] decimal(10,4)  null,
    [tt_hours] decimal(10,4)  null,
    [tt_hours_prorata] decimal(14,4)  null,
    [tt_amount] decimal(14,4)  null,
    [cont_crush_hours] decimal(10,4)  null,
    [cont_crush_amount] decimal(14,4)  null,
    [rdo_hours] decimal(10,4)  null,
    [rdo_amount] decimal(14,4)  null,
    [ado_hours] decimal(10,4)  null,
    [ado_amount] decimal(14,4)  null,
    [public_holiday_hrs] decimal(10,4)  null,
    [public_holiday_amt] decimal(14,4)  null,
    [sick_pay_hours] decimal(10,4)  null,
    [sick_pay_amount] decimal(14,4)  null,
    [all_amount] decimal(14,4)  null,
    [all_amount_ytd] decimal(14,4)  null,
    [extra_amounts] decimal(14,4)  null,
    [total_leave_amnts] decimal(14,4)  null,
    [lsl_ttl_hrs_accrd] decimal(10,4)  null,
    [lsl_ttl_amount] decimal(14,4)  null,
    [lsl_ttl_tax] decimal(14,4)  null,
    [lsl_78_hours_accrd] decimal(10,4)  null,
    [lsl_78_hours_accrl] decimal(10,4)  null,
    [lsl_78_amount] decimal(14,4)  null,
    [lsl_78_tax] decimal(14,4)  null,
    [lsl_93_hours_accrd] decimal(10,4)  null,
    [lsl_93_hours_accrl] decimal(10,4)  null,
    [lsl_93_amount] decimal(14,4)  null,
    [lsl_93_tax] decimal(14,4)  null,
    [lsl_hours_accrued] decimal(10,4)  null,
    [lsl_hours_accrual] decimal(10,4)  null,
    [lsl_hours_prorata] decimal(14,4)  null,
    [lsl_amount] decimal(14,4)  null,
    [current_gross_amnt] decimal(14,4)  null,
    [current_gross_tax] decimal(14,4)  null,
    [lsp_amount] decimal(14,4)  null,
    [lsp_tax] decimal(14,4)  null,
    [lsp_taxable] decimal(14,4)  null,
    [total_tax] decimal(14,4)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [hourly_rate_slack] decimal(14,4)  null,
    [use_lsl_first] varchar(1)  null,
    [lsl_days] decimal(10,4)  null,
    [lsl_days_slack] decimal(10,4)  null,
    [lsl_hours_slack] decimal(10,4)  null,
    [lsl_amount_slack] decimal(14,4)  null,
    [al_hours_slack] decimal(10,4)  null,
    [al_amount_slack] decimal(14,4)  null,
    [tt_hours_slack] decimal(10,4)  null,
    [tt_amount_slack] decimal(14,4)  null,
    [ph_hours_slack] decimal(10,4)  null,
    [ph_amount_slack] decimal(14,4)  null,
    [ttl_workdays] decimal(10,4)  null,
    [ttl_workdays_slack] decimal(10,4)  null,
    [number_of_weeks] int  null
);
go

-- creating table 'hrpay_master_ctl'
create table [extract].[hrpay_master_ctl] (
    [document_type] varchar(10)  not null,
    [company_code] int  not null,
    [pay_document_no] int  not null,
    [id_number] int  null,
    [pay_period_enddate] datetime  null,
    [pay_period_type] varchar(10)  null,
    [base_amount] decimal(14,4)  null,
    [gross_amount] decimal(14,4)  null,
    [taxable_income] decimal(14,4)  null,
    [total_tax_amount] decimal(14,4)  null,
    [nett_pay] decimal(14,4)  null,
    [pay_calc_date] datetime  null,
    [jnl_creation_date] datetime  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [paid_date] datetime  null,
    [no_of_pay_periods] decimal(10,4)  null,
    [amount_paid] decimal(14,4)  null,
    [payment_method_pc] decimal(10,4)  null,
    [pay_period_startdate] datetime  null,
    [periodend_position_code] varchar(20)  null,
    [periodend_job_effdate] datetime  null,
    [periodend_tax_effdate] datetime  null
);
go

-- creating table 'hrpay_payitems_dtl'
create table [extract].[hrpay_payitems_dtl] (
    [document_type] varchar(10)  not null,
    [company_code] int  not null,
    [pay_document_no] int  not null,
    [pay_component_def1] varchar(10)  null,
    [pay_component_ref1] varchar(10)  null,
    [sequence_no] int  not null,
    [module_id] varchar(10)  null,
    [number_units] decimal(10,4)  null,
    [pay_period_unit] varchar(10)  null,
    [pay_item_rate] decimal(18,6)  null,
    [pay_item_amount] decimal(18,6)  null,
    [taxable] varchar(1)  null,
    [payment] varchar(1)  null,
    [calbydaysworked] varchar(1)  null,
    [accts_payable_ref] varchar(10)  null,
    [account_mumber] varchar(20)  null,
    [bonus_code] varchar(10)  null,
    [pay_calc_date] datetime  null,
    [pay_item_expl] varchar(40)  null,
    [transaction_date] datetime  null,
    [trans_accnt_no] varchar(20)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [accrual_date] datetime  null,
    [accrual_date_prev] datetime  null,
    [accrual_amt_prev] decimal(14,4)  null,
    [pay_component_def] int  null,
    [pay_component_ref] decimal(10,4)  not null,
    [no_accruals_prev] int  null,
    [no_accruals] int  null,
    [pay_item_type] varchar(10)  null,
    [disb_code] varchar(10)  null,
    [ldg_code] varchar(2)  null,
    [accnbri] varchar(32)  null,
    [clr_ldg_code] varchar(2)  null,
    [clr_accnbri] varchar(32)  null,
    [disbursed_ind] varchar(1)  null,
    [id_number] int  null,
    [pay_period_enddate] datetime  null,
    [pay_period_type] varchar(10)  null,
    [posted_ind] varchar(1)  null,
    [pgrp_name] varchar(8)  null,
    [period] smallint  null,
    [ldg_name] varchar(8)  null,
    [trans_nbr] decimal(15,0)  null,
    [clr_ldg_name] varchar(8)  null,
    [clr_trans_nbr] decimal(15,0)  null,
    [empl_cond_award] varchar(10)  null,
    [empl_cond_grade] varchar(10)  null,
    [empl_cond_level] varchar(10)  null,
    [posting_ind] varchar(1)  null,
    [empl_debtor_ind] varchar(1)  null,
    [calc_type] varchar(1)  null,
    [techone_fld1] varchar(40)  null,
    [techone_fld2] varchar(40)  null,
    [techone_fld3] varchar(40)  null,
    [techone_fld4] varchar(40)  null,
    [position_code] varchar(10)  null,
    [item_start_datei] datetime  null,
    [item_end_datei] datetime  null,
    [worked_pay_period_enddate] datetime  null,
    [impact_status] varchar(10)  null,
    [fund_nbr] smallint  null,
    [fund_trans_class] varchar(1)  null,
    [fund_ldg_name] varchar(8)  null,
    [fund_accnbri] varchar(32)  null,
    [funds_ctl_ind] varchar(2)  null,
    [funds_ctl_ind_clr] varchar(2)  null,
    [fund_nbr_clr] smallint  null,
    [fund_trns_clss_clr] varchar(1)  null,
    [fund_ldg_name_clr] varchar(8)  null,
    [fund_accnbri_clr] varchar(32)  null,
    [reference_nbr] varchar(50)  null
);
go

-- creating table 'hrpay_payitems_summaccr'
create table [extract].[hrpay_payitems_summaccr] (
    [employee_id] int  not null,
    [accrual_date] datetime  not null,
    [pay_component_ref] decimal(18,6)  not null,
    [period_accrual] decimal(18,6)  null,
    [period_taken] decimal(18,6)  null,
    [unit_type] varchar(10)  null,
    [open_entitlement] decimal(18,6)  null,
    [open_pro_rata] decimal(18,6)  null,
    [open_taken] decimal(18,6)  null,
    [open_balance] decimal(18,6)  null,
    [close_entitlement] decimal(18,6)  null,
    [close_pro_rata] decimal(18,6)  null,
    [close_taken] decimal(18,6)  null,
    [close_balance] decimal(18,6)  null,
    [prev_entitlement] decimal(18,6)  null,
    [prev_pro_rata] decimal(18,6)  null,
    [prev_taken] decimal(18,6)  null,
    [prev_balance] decimal(18,6)  null,
    [accrual_group] varchar(20)  null,
    [last_accrual_date] datetime  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null
);
go

-- creating table 'hrpay_payitems_summpmnt'
create table [extract].[hrpay_payitems_summpmnt] (
    [company_code] int  not null,
    [pay_period_enddate] datetime  not null,
    [document_type] varchar(10)  not null,
    [employee_id] int  not null,
    [pay_component_ref] decimal(18,6)  not null,
    [super_fund_code] varchar(20)  not null,
    [unit_type] varchar(20)  null,
    [number_of_units] decimal(18,6)  null,
    [ytd_opening_amount] decimal(18,6)  null,
    [period_amount] decimal(18,6)  null,
    [ytd_closing_amount] decimal(18,6)  null,
    [prev_amount] decimal(18,6)  null,
    [pay_component_def] decimal(18,6)  null,
    [payment_type] varchar(1)  null,
    [taxable_ind] varchar(1)  null,
    [bank_code] varchar(20)  null,
    [bank_branch_number] varchar(32)  null,
    [bank_account_number] varchar(40)  null,
    [bank_account_name] varchar(50)  null,
    [super_institute_code] varchar(10)  null,
    [super_member_number] varchar(32)  null,
    [super_contribution_type] varchar(10)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null
);
go
