-- creating table 'hrpcm_paycomp_ref'
create table [extract].[hrpcm_paycomp_ref] (
    [pay_component_def1] varchar(10)  null,
    [pay_component_ref1] varchar(10)  null,
    [pay_comp_eff_date] datetime  null,
    [pay_comp_ref_desc] varchar(50)  null,
    [payment_deduction] varchar(1)  null,
    [taxable] varchar(1)  null,
    [calcbydaysworked] varchar(1)  null,
    [etp_type_payment] varchar(1)  null,
    [control_method] varchar(10)  null,
    [pay_period_type] varchar(10)  null,
    [units_per_period] decimal(15,6)  null,
    [pay_period_unit] varchar(1)  null,
    [accrual_marker] varchar(1)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [dep_pay_comp_def1] varchar(10)  null,
    [dep_pay_comp_ref1] varchar(10)  null,
    [component_amount] decimal(15,6)  null,
    [use_season_status] varchar(1)  null,
    [accrl_paycomp_ref1] varchar(10)  null,
    [usedbyroster] varchar(1)  null,
    [pay_component_def] int  null,
    [pay_component_ref] decimal(15,6)  not null,
    [dep_pay_comp_def] int  null,
    [dep_pay_comp_ref] decimal(15,6)  null,
    [accrl_pay_comp_ref] decimal(15,6)  null,
    [amount_minimum] decimal(14,5)  null,
    [amount_maximum] decimal(14,5)  null,
    [units_minimum] decimal(14,5)  null,
    [units_maximum] decimal(14,5)  null,
    [posting_ind] varchar(1)  null,
    [techone_fld1] decimal(14,5)  null,
    [techone_fld2] decimal(14,5)  null,
    [techone_fld3] decimal(14,5)  null,
    [techone_fld4] decimal(14,5)  null,
    [techone_fld5] datetime  null,
    [techone_fld6] datetime  null,
    [techone_fld7] datetime  null,
    [techone_fld8] datetime  null,
    [techone_fld9] varchar(10)  null,
    [techone_fld10] varchar(10)  null,
    [techone_fld11] varchar(10)  null,
    [techone_fld12] varchar(10)  null,
    [self_service_ind] varchar(1)  null,
    [payslip_print_ind] varchar(1)  null,
    [priority_sequence] smallint  null,
    [tsheet_ind] varchar(1)  null,
    [dep_config_code] varchar(10)  null,
    [trans_depndt_ind] varchar(1)  null,
    [percent_multiplier] decimal(18,6)  null,
    [amount_script_name] varchar(15)  null,
    [dep_script_name] varchar(15)  null,
    [percent_total_ind] varchar(1)  null,
    [payee_code] varchar(20)  null,
    [deduction_type] varchar(20)  null,
    [rpt_group_1] varchar(20)  null,
    [rpt_group_2] varchar(20)  null,
    [rpt_group_3] varchar(20)  null,
    [rpt_group_4] varchar(20)  null,
    [rpt_group_5] varchar(20)  null
);
go
-- creating primary key on [pay_component_ref] in table 'hrpcm_paycomp_ref'
alter table [extract].[hrpcm_paycomp_ref]
add constraint [pk_hrpcm_paycomp_ref]
    primary key clustered ([pay_component_ref] asc);
go