//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBComplainant_CA
    {
        public int FBComplainant_ID { get; set; }
        public string FBCompMRN { get; set; }
        public string FBCompTitle { get; set; }
        public string FBCompFirstName { get; set; }
        public string FBCompSurname { get; set; }
        public Nullable<System.DateTime> FBCompDateOfBirth { get; set; }
        public string FBCompAgeRange { get; set; }
        public string FBCompGender { get; set; }
        public string FBCompAddress1 { get; set; }
        public string FBCompAddress2 { get; set; }
        public string FBCompSuburb { get; set; }
        public string FBCompPostcode { get; set; }
        public string FBCompState { get; set; }
        public string FBCompWPhone { get; set; }
        public string FBCompHPhone { get; set; }
        public string FBCompMPhone { get; set; }
        public string FBCompFax { get; set; }
        public string FBCompEmail { get; set; }
        public string FBCompPrimaryLanguage { get; set; }
        public string FBCompInterpreter { get; set; }
        public string FBCompCountry { get; set; }
        public string FBCompAboriginalType { get; set; }
        public string FBCompStatus { get; set; }
        public string FBCompOrganisation { get; set; }
        public string FBCompRelationship { get; set; }
        public string FBCompPermComplain { get; set; }
        public Nullable<System.DateTime> FBCompPermComplainDate { get; set; }
        public string FBCompPermComplainMode { get; set; }
        public string FBCompPermMedicalInfo { get; set; }
        public Nullable<System.DateTime> FBCompPermMedicalInfoDate { get; set; }
        public string FBCompPermMedicalInfoMode { get; set; }
        public Nullable<bool> FBCompAnon { get; set; }
        public string FBCompContactMode { get; set; }
        public string FBCompStatusOther { get; set; }
        public string FBCompDescribeRShip { get; set; }
        public Nullable<bool> FBCompIndigenous { get; set; }
    }
}
