//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBConsumer_CA
    {
        public int FBConsumer_ID { get; set; }
        public string FBConsMRN { get; set; }
        public string FBConsTitle { get; set; }
        public string FBConsFirstName { get; set; }
        public string FBConsSurname { get; set; }
        public Nullable<System.DateTime> FBConsDateOfBirth { get; set; }
        public string FBConsAgeRange { get; set; }
        public string FBConsGender { get; set; }
        public string FBConsAddress1 { get; set; }
        public string FBConsAddress2 { get; set; }
        public string FBConsSuburb { get; set; }
        public string FBConsPostcode { get; set; }
        public string FBConsState { get; set; }
        public string FBConsWPhone { get; set; }
        public string FBConsHPhone { get; set; }
        public string FBConsMPhone { get; set; }
        public string FBConsFax { get; set; }
        public string FBConsEmail { get; set; }
        public string FBConsPrimaryLanguage { get; set; }
        public string FBConsInterpreter { get; set; }
        public string FBConsCountry { get; set; }
        public string FBConsAboriginalType { get; set; }
        public string FBConsStatus { get; set; }
        public string FBConsOrganisation { get; set; }
        public string FBConsType { get; set; }
        public Nullable<System.DateTime> FBConsAdmissionDate { get; set; }
        public Nullable<System.DateTime> FBConsDischargeDate { get; set; }
        public Nullable<bool> FBConsDeceased { get; set; }
        public Nullable<bool> FBConsAnon { get; set; }
        public Nullable<bool> FBConsIndigenous { get; set; }
    }
}
