//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBDetail_CA
    {
        public int FBDetail_ID { get; set; }
        public string FBFormalityLevel { get; set; }
        public string FBModeReceived { get; set; }
        public Nullable<System.DateTime> FBAckDate { get; set; }
        public Nullable<System.DateTime> FBFirstFormalDate { get; set; }
        public string FBReportedTo { get; set; }
        public string FBReportedToPosition { get; set; }
        public string FBReferredTo { get; set; }
        public string FBReferredToPosition { get; set; }
        public Nullable<bool> FBAssocInc { get; set; }
        public string FBAssocIncNo { get; set; }
        public Nullable<bool> FBInsurerNotifReq { get; set; }
        public string FBSAC { get; set; }
        public Nullable<int> FBSACScore { get; set; }
        public string FBSACRowLabel { get; set; }
        public string FBSACColLabel { get; set; }
        public string FBRefPath { get; set; }
        public Nullable<bool> FBResultedInQIA { get; set; }
        public string FBModeReceivedOther { get; set; }
        public Nullable<bool> FBRelateClient { get; set; }
        public Nullable<bool> FBSpecificService { get; set; }
        public Nullable<bool> FBRelateStaff { get; set; }
        public string FBRelateStaffName { get; set; }
        public Nullable<bool> FBCreateIncident { get; set; }
    }
}
