//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBDetail1_CA
    {
        public int FBDetail1_ID { get; set; }
        public string FBResultedInQIANotes { get; set; }
        public string FBTestField { get; set; }
        public Nullable<bool> FBIsClosed { get; set; }
        public string FBStaffNames { get; set; }
        public string OtherService { get; set; }
        public string OtherSite { get; set; }
        public string OtherAddr { get; set; }
        public string FBWing { get; set; }
    }
}
