//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentClassificationsIFR
    {
        public Nullable<int> ID { get; set; }
        public string Supergroup { get; set; }
        public string IncidentClass { get; set; }
        public string Definitions { get; set; }
        public Nullable<short> SortSeq { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> DefinitionID { get; set; }
        public int autonum { get; set; }
    }
}
