//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.riskman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiskmanEntities : DbContext
    {
        public RiskmanEntities()
            : base("name=RiskmanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FBComplainant_CA> FBComplainant_CA { get; set; }
        public virtual DbSet<FBConsumer_CA> FBConsumer_CA { get; set; }
        public virtual DbSet<FBDetail_CA> FBDetail_CA { get; set; }
        public virtual DbSet<FBDetail1_CA> FBDetail1_CA { get; set; }
        public virtual DbSet<IncidentClassificationsIFR> IncidentClassificationsIFRs { get; set; }
        public virtual DbSet<IncidentsForReview> IncidentsForReviews { get; set; }
    }
}
