CREATE TABLE [extract_comcare].[Activity_Work_Table](
	[Activity_No] [numeric](18, 0) NOT NULL,
	[Client_ID] [int] NULL,
	[Activity_Date] [datetime] NULL,
	[Provider_ID] [int] NULL,
	[Service_Prov_Position_ID] [int] NULL,
	[Person_ID] [int] NULL,
	[Organisation_ID] [int] NULL,
	[Task_Type_Code] [varchar](8) NULL,
	[Indirect_Activity_Type_Code] [tinyint] NULL,
	[Schedule_Time] [datetimeoffset](7) NULL,
	[Schedule_Duration] [smallint] NULL,
	[Activity_Duration] [smallint] NULL,
	[Travel_Km] [decimal](5, 1) NULL,
	[Travel_Duration] [smallint] NULL,
	[Allocated_Task_ID] [int] NULL,
	[Compensible_Type_ID] [smallint] NULL,
	[Funding_Prog_Code] [smallint] NULL,
	[Activity_Start_Time] [datetimeoffset](7) NULL,
	[Activity_End_Time] [datetimeoffset](7) NULL,
	[Odometer_Reading] [int] NULL,
	[Units_of_Service] [decimal](10, 2) NULL,
	[On_Flag] [tinyint] NULL,
	[Off_Flag] [tinyint] NULL,
	[Format_OK] [tinyint] NULL,
	[ComCare_Validation_OK] [tinyint] NULL,
	[Payroll_Validation_OK] [tinyint] NULL,
	[Verification_Required] [tinyint] NULL,
	[Authorisation_Date] [datetimeoffset](7) NULL,
	[Authorisation_Person] [varchar](20) NULL,
	[Actual_Service_Visit_No] [tinyint] NULL,
	[Indirect_Activity_No] [tinyint] NULL,
	[Classn_Shift_Centre] [varchar](20) NULL,
	[Date_Extract_for_Payroll] [datetimeoffset](7) NULL,
	[Date_Upload_to_ComCare] [datetime] NULL,
	[Creation_Date] [datetimeoffset](7) NOT NULL,
	[Creator_User_Name] [varchar](20) NOT NULL,
	[Last_Modified_Date] [datetimeoffset](7) NULL,
	[Last_Modified_User_Name] [varchar](20) NULL,
	[Company_Vehicle] [tinyint] NULL,
	[Extracted_Funding_Prog_Code] [varchar](10) NULL,
	[Shift_Start_Time] [datetimeoffset](7) NULL,
	[Shift_End_Time] [datetimeoffset](7) NULL,
	[PreAuthorise_Id] [int] NULL,
	[Client_Casemix_Assignment_ID] [int] NULL,
	[On_Call_Activity_Code] [varchar](4) NULL,
	[WI_Record_ID] [int] NULL,
	[Address_ID] [numeric](18, 0) NULL,
	[Schedule_Units_of_Service] [decimal](10, 2) NULL,
	[Interrupt_Duration] [int] NULL,
	[Interrupted_Activity] [int] NULL,
	[Registration_Number] [varchar](20) NULL,
	[WI_Activity_ID] [int] NULL,
	[Cancelled_Visit] [bit] NULL,
	[Group_Activity_ID] [int] NULL,
	[Student_Allocation_ID] [int] NULL,
	[Class_ID] [int] NULL,
	[Internal_Task_Provider_ID] [int] NULL,
	[Internal_Task_Working_Week_No] [int] NULL,
	[Internal_Task_From_Date] [datetime] NULL,
	[CAP_ID] [int] NULL,
	[User_Classification_ID] [smallint] NULL,
	[Estimated_Travel_Km] [decimal](5, 1) NULL,
	[Estimated_Travel_Time] [smallint] NULL,
	[Client_Not_Home] [bit] NULL,
	[Destination_Address_ID] [numeric](18, 0) NULL,
	[Est_Intravisit_Travel_Km] [smallint] NULL,
	[Actual_Intravisit_Travel_Km] [smallint] NULL,
	[Scheduled_Visit_End_Time] [datetimeoffset](7) NULL,
	[External_Provider] [bit] NULL,
	[Est_Visit_Charge] [decimal](9, 2) NULL,
 CONSTRAINT [PK_ACTIVITY_WORK_TABLE] PRIMARY KEY NONCLUSTERED 
(
	[Activity_No] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO