CREATE TABLE [extract_comcare].[actual_service](
	[Client_ID] [int] NOT NULL,
	[Visit_Date] [datetime] NOT NULL,
	[Visit_No] [tinyint] NOT NULL,
	[Provider_ID] [int] NOT NULL,
	[Service_Prov_Position_ID] [numeric](18, 0) NOT NULL,
	[Organisation_ID] [numeric](18, 0) NULL,
	[Task_Type_Code] [char](8) NOT NULL,
	[Person_ID] [int] NULL,
	[Visit_Time] [datetimeoffset](7) NULL,
	[Scheduled_Duration] [smallint] NULL,
	[Visit_Duration] [smallint] NULL,
	[Travel_Km] [numeric](5, 1) NULL,
	[Travel_Duration] [smallint] NULL,
	[Support_Meeting_Duration] [smallint] NULL,
	[Other_Duration] [smallint] NULL,
	[Creation_Date] [datetimeoffset](7) NOT NULL,
	[Creator_User_Name] [varchar](20) NOT NULL,
	[Last_Modified_Date] [datetimeoffset](7) NULL,
	[Last_Modified_User_Name] [varchar](20) NULL,
	[Allocated_Task_ID] [int] NULL,
	[Compensible_Type_ID] [smallint] NULL,
	[Visit_Category_Code] [tinyint] NULL,
	[Funding_Prog_Code] [smallint] NULL,
	[Client_Casemix_Assignment_ID] [numeric](18, 0) NULL,
	[Activity_Start_Time] [datetimeoffset](7) NULL,
	[Activity_End_Time] [datetimeoffset](7) NULL,
	[Odometer_Reading] [int] NULL,
	[Units_of_Service] [numeric](10, 2) NULL,
	[Date_Upload_from_AWT] [datetime] NULL,
	[Address_ID] [numeric](18, 0) NULL,
	[On_Call_Activity_Code] [varchar](4) NULL,
	[Group_Activity_ID] [numeric](18, 0) NULL,
	[CAP_ID] [int] NULL,
	[Date_Finalised] [datetime] NULL,
	[Activity_No] [numeric](18, 0) NULL,
	[Billed_Date] [datetime] NULL,
	[Capped_Funding_Prog_Code] [smallint] NULL,
	[User_Classification_ID] [smallint] NULL,
	[Client_Not_Home] [bit] NULL,
	[Destination_Address_ID] [numeric](18, 0) NULL,
	[Est_Intravisit_Travel_Km] [smallint] NULL,
	[Actual_Intravisit_Travel_Km] [smallint] NULL,
	[Scheduled_Visit_End_Time] [datetimeoffset](7) NULL,
	[External_Provider] [bit] NULL,
	[Est_Visit_Charge] [numeric](9, 2) NULL,
	[Date_Costed] [datetime] NULL,
	[Value_Costed] [numeric](9, 2) NULL,
	[FC_Account_ID] [numeric](18, 0) NULL,
	[Archived] [bit] NULL,
	[WI_Activity_ID] [numeric](18, 0) NULL,
	[Visit_Cancel_Reason_ID] [tinyint] NULL,
	[Cancel_Recorded_Person_ID] [int] NULL,
	[Cancellation_Date] [datetimeoffset](7) NULL,
	[Comment] [varchar](max) NULL,
	[Fee_Waived] [bit] NULL,
	[Scheduled_Visit_Start_Time] [datetimeoffset](7) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


