//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public action_dim()
        {
            this.incident_action_bridge = new HashSet<incident_action_bridge>();
        }
    
        public int action_key { get; set; }
        public string preventative_corrective_action { get; set; }
        public string specific_preventative_corrective_action { get; set; }
        public Nullable<System.DateTime> action_due_date { get; set; }
        public Nullable<System.DateTime> action_completed_date { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident_action_bridge> incident_action_bridge { get; set; }
    }
}
