//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_riskman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conform_riskman_conceptualContainer : DbContext
    {
        public conform_riskman_conceptualContainer()
            : base("name=conform_riskman_conceptualContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<date_dim> date_dim { get; set; }
        public virtual DbSet<employee_dim> employee_dim { get; set; }
        public virtual DbSet<incident_fact> incident_fact { get; set; }
        public virtual DbSet<incident_type_bridge> incident_type_bridge { get; set; }
        public virtual DbSet<incident_type_dim> incident_type_dim { get; set; }
        public virtual DbSet<person_dim> person_dim { get; set; }
        public virtual DbSet<portfolio_dim> portfolio_dim { get; set; }
        public virtual DbSet<program_dim> program_dim { get; set; }
        public virtual DbSet<service_stream_dim> service_stream_dim { get; set; }
        public virtual DbSet<action_dim> action_dim { get; set; }
        public virtual DbSet<incident_action_bridge> incident_action_bridge { get; set; }
    }
}
