//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_dim()
        {
            this.incident_fact = new HashSet<incident_fact>();
        }
    
        public int employee_key { get; set; }
        public Nullable<int> id_number { get; set; }
        public string given_name { get; set; }
        public string family_name { get; set; }
        public string preferred_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string passport_number { get; set; }
        public string visa_number { get; set; }
        public string country_of_origin { get; set; }
        public string employee_type { get; set; }
        public string employee_class { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
        public Nullable<decimal> pay_per_period { get; set; }
        public Nullable<decimal> units_per_period { get; set; }
        public string rem_level { get; set; }
        public string rem_range { get; set; }
        public string car_flag { get; set; }
        public string phone_flag { get; set; }
        public string salary_continuance { get; set; }
        public string street_address_line1 { get; set; }
        public string street_address_line2 { get; set; }
        public string street_address_line3 { get; set; }
        public string street_city { get; set; }
        public string street_state { get; set; }
        public string street_post_code { get; set; }
        public string street_country_code { get; set; }
        public string street_telephone1 { get; set; }
        public string street_telephone2 { get; set; }
        public string street_telephone3 { get; set; }
        public string street_mobile1 { get; set; }
        public string street_mobile2 { get; set; }
        public string street_email1 { get; set; }
        public string street_email2 { get; set; }
        public string postal_address_line1 { get; set; }
        public string postal_address_line2 { get; set; }
        public string postal_address_line3 { get; set; }
        public string postal_city { get; set; }
        public string postal_state { get; set; }
        public string postal_post_code { get; set; }
        public string postal_country_code { get; set; }
        public string postal_telephone1 { get; set; }
        public string postal_telephone2 { get; set; }
        public string postal_telephone3 { get; set; }
        public string postal_mobile1 { get; set; }
        public string postal_mobile2 { get; set; }
        public string postal_email1 { get; set; }
        public string postal_email2 { get; set; }
        public string ethnic_group { get; set; }
        public string pay_period_unit { get; set; }
        public string visa_type { get; set; }
        public Nullable<decimal> fte { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string contact_family_name { get; set; }
        public string contact_given_name { get; set; }
        public string contact_dependant_flag { get; set; }
        public string contact_type { get; set; }
        public string contact_address_line1 { get; set; }
        public string contact_address_line2 { get; set; }
        public string contact_address_line3 { get; set; }
        public string contact_address_city { get; set; }
        public string contact_address_state { get; set; }
        public string contact_address_post_code { get; set; }
        public string contact_address_country_code { get; set; }
        public string contact_telephone1 { get; set; }
        public string contact_telephone2 { get; set; }
        public string contact_telephone3 { get; set; }
        public string contact_mobile1 { get; set; }
        public string contact_mobile2 { get; set; }
        public string contact_email1 { get; set; }
        public string contact_email2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident_fact> incident_fact { get; set; }
    }
}
