//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident_fact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incident_fact()
        {
            this.incident_type_bridge = new HashSet<incident_type_bridge>();
            this.incident_action_bridge = new HashSet<incident_action_bridge>();
        }
    
        public int incident_key { get; set; }
        public int id { get; set; }
        public int logged_by_employee_key { get; set; }
        public int person_key { get; set; }
        public int portfolio_key { get; set; }
        public int Service_Stream_Key { get; set; }
        public int Program_Key { get; set; }
        public int date_closed_key { get; set; }
        public int incident_date_key { get; set; }
        public int notification_date_key { get; set; }
        public int date_deleted_key { get; set; }
        public int date_entered_key { get; set; }
        public Nullable<System.DateTime> incident_time { get; set; }
        public Nullable<int> Age { get; set; }
        public string Severity { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string Incident_involved { get; set; }
        public string Deceased { get; set; }
        public string Coroner_notified { get; set; }
        public string autopsy { get; set; }
        public string next_of_kin_notified { get; set; }
        public string notification_reason { get; set; }
        public string transfer_location { get; set; }
        public string employee_site { get; set; }
        public string nature_of_injury { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int closed_date_key { get; set; }
        public int notified_date_key { get; set; }
        public int deleted_date_key { get; set; }
        public int entered_date_key { get; set; }
        public int investigation_initiated_date_key { get; set; }
        public int investigation_completed_date_key { get; set; }
        public Nullable<int> age { get; set; }
        public string severity { get; set; }
        public string status { get; set; }
        public string location { get; set; }
        public string incident_involved { get; set; }
        public string deceased { get; set; }
        public string coroner_notified { get; set; }
        public string summary { get; set; }
        public string lti_incurred { get; set; }
        public string investigation_initiated { get; set; }
        public string safeworksa_notified { get; set; }
        public string staff_injury { get; set; }
        public string preventative_corrective_action_required { get; set; }
        public string police_notified { get; set; }
        public string fire_brigade_notified { get; set; }
        public string ambulance__notified { get; set; }
        public string human_services_notified { get; set; }
        public string health_sa_notified { get; set; }
        public string crisis_intervention_notified { get; set; }
        public string carl_notified { get; set; }
        public string ag_notified { get; set; }
        public string housing_regulator_notified { get; set; }
        public string funder_notified { get; set; }
    
        public virtual date_dim date_dim { get; set; }
        public virtual date_dim date_dim2 { get; set; }
        public virtual date_dim date_dim4 { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual person_dim person_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident_type_bridge> incident_type_bridge { get; set; }
        public virtual date_dim date_dim5 { get; set; }
        public virtual date_dim date_dim6 { get; set; }
        public virtual date_dim date_dim3 { get; set; }
        public virtual date_dim date_dim41 { get; set; }
        public virtual date_dim date_dim51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident_action_bridge> incident_action_bridge { get; set; }
    }
}
