//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.management
{
    using System;
    using System.Collections.Generic;
    
    public partial class date_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public date_dim()
        {
            this.etl_process_fact = new HashSet<etl_process_fact>();
            this.error_event_detail_fact = new HashSet<error_event_detail_fact>();
            this.error_event_fact = new HashSet<error_event_fact>();
        }
    
        public int date_key { get; set; }
        public Nullable<System.DateTime> full_date { get; set; }
        public string year { get; set; }
        public string quarter { get; set; }
        public string quarter_name { get; set; }
        public string month { get; set; }
        public string month_name { get; set; }
        public string day_of_month { get; set; }
        public string day_of_week { get; set; }
        public string day_name { get; set; }
        public string is_public_holiday { get; set; }
        public string public_holiday_name { get; set; }
        public string financial_year { get; set; }
        public string fbt_range { get; set; }
        public string pay_period_end { get; set; }
        public Nullable<int> month_no { get; set; }
        public Nullable<int> financial_month_no { get; set; }
        public Nullable<decimal> max_temperature { get; set; }
        public Nullable<decimal> min_temperature { get; set; }
        public Nullable<decimal> rainfall { get; set; }
        public Nullable<decimal> max_wind_speed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etl_process_fact> etl_process_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<error_event_detail_fact> error_event_detail_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<error_event_fact> error_event_fact { get; set; }
    }
}
