//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.management
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_event_fact
    {
        public int error_event_key { get; set; }
        public int batch_key { get; set; }
        public int date_key { get; set; }
        public string error_date_time { get; set; }
        public string error_severity { get; set; }
        public int package_key { get; set; }
    
        public virtual batch_dim batch_dim { get; set; }
        public virtual package_dim package_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
    }
}
