//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.management
{
    using System;
    using System.Collections.Generic;
    
    public partial class etl_process_fact
    {
        public int etl_process_key { get; set; }
        public int date_key { get; set; }
        public int batch_key { get; set; }
        public int table_key { get; set; }
        public int status_key { get; set; }
        public System.DateTime cdc_date_time { get; set; }
        public int package_key { get; set; }
        public string operation { get; set; }
    
        public virtual batch_dim batch_dim { get; set; }
        public virtual status_dim status_dim { get; set; }
        public virtual table_dim table_dim { get; set; }
        public virtual package_dim package_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
    }
}
