//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.management
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_control
    {
        public int job_key { get; set; }
        public int source_table_key { get; set; }
        public string job_enabled_flag { get; set; }
        public int destination_table_key { get; set; }
        public int package_key { get; set; }
        public Nullable<int> priority { get; set; }
        public string frequency { get; set; }
    
        public virtual package_dim package_dim { get; set; }
        public virtual table_dim table_dim { get; set; }
        public virtual table_dim table_dim1 { get; set; }
    }
}
