//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class management_conceptualContainer : DbContext
    {
        public management_conceptualContainer()
            : base("name=management_conceptualContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch_dim> batch_dim { get; set; }
        public virtual DbSet<error_event_detail_fact> error_event_detail_fact { get; set; }
        public virtual DbSet<error_event_fact> error_event_fact { get; set; }
        public virtual DbSet<etl_process_fact> etl_process_fact { get; set; }
        public virtual DbSet<job_control> job_control { get; set; }
        public virtual DbSet<package_dim> package_dim { get; set; }
        public virtual DbSet<status_dim> status_dim { get; set; }
        public virtual DbSet<table_dim> table_dim { get; set; }
        public virtual DbSet<date_dim> date_dim { get; set; }
        public virtual DbSet<quality_check_fact> quality_check_fact { get; set; }
    }
}
