//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.management
{
    using System;
    using System.Collections.Generic;
    
    public partial class quality_check_fact
    {
        public int quality_check_key { get; set; }
        public int table_key { get; set; }
        public string business_owner { get; set; }
        public string column_name { get; set; }
        public string description { get; set; }
        public string sql { get; set; }
        public string check_type { get; set; }
        public string error_message { get; set; }
        public string error_action { get; set; }
        public string on_off_flag { get; set; }
    
        public virtual table_dim table_dim { get; set; }
    }
}
