//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_dim()
        {
            this.employee_accreditation_fact = new HashSet<employee_accreditation_fact>();
            this.employee_accreditation_fact1 = new HashSet<employee_accreditation_fact>();
            this.employee_contract_fact = new HashSet<employee_contract_fact>();
            this.employee_contract_fact1 = new HashSet<employee_contract_fact>();
            this.employee_leave_booked_fact = new HashSet<employee_leave_booked_fact>();
            this.employee_leave_taken_fact = new HashSet<employee_leave_taken_fact>();
            this.employee_position_fact = new HashSet<employee_position_fact>();
            this.employee_termination_fact = new HashSet<employee_termination_fact>();
            this.employee_leave_accrued_fact = new HashSet<employee_leave_accrued_fact>();
            this.employee_leave_accrued_fact1 = new HashSet<employee_leave_accrued_fact>();
            this.employee_leave_booked_fact1 = new HashSet<employee_leave_booked_fact>();
            this.employee_leave_booked_txn_fact = new HashSet<employee_leave_booked_txn_fact>();
            this.employee_leave_booked_txn_fact1 = new HashSet<employee_leave_booked_txn_fact>();
            this.employee_leave_taken_fact1 = new HashSet<employee_leave_taken_fact>();
            this.employee_payment_fact = new HashSet<employee_payment_fact>();
            this.employee_position_fact1 = new HashSet<employee_position_fact>();
            this.employee_profile_fact = new HashSet<employee_profile_fact>();
            this.employee_profile_fact1 = new HashSet<employee_profile_fact>();
            this.employee_recruitment_fact = new HashSet<employee_recruitment_fact>();
            this.employee_timesheet_fact = new HashSet<employee_timesheet_fact>();
            this.employee_timesheet_fact1 = new HashSet<employee_timesheet_fact>();
            this.employee_timesheet_fact2 = new HashSet<employee_timesheet_fact>();
            this.work_pattern_fact = new HashSet<work_pattern_fact>();
            this.work_pattern_fact1 = new HashSet<work_pattern_fact>();
            this.all_employees_report_fact = new HashSet<all_employees_report_fact>();
            this.all_employees_report_fact1 = new HashSet<all_employees_report_fact>();
            this.position_establishment_fact = new HashSet<position_establishment_fact>();
            this.position_establishment_fact1 = new HashSet<position_establishment_fact>();
            this.employee_last_paid_date_fact = new HashSet<employee_last_paid_date_fact>();
            this.employee_renumeration_fact = new HashSet<employee_renumeration_fact>();
            this.employee_renumeration_fact1 = new HashSet<employee_renumeration_fact>();
        }
    
        public int employee_key { get; set; }
        public Nullable<int> id_number { get; set; }
        public string given_name { get; set; }
        public string family_name { get; set; }
        public string preferred_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string passport_number { get; set; }
        public string visa_number { get; set; }
        public string country_of_origin { get; set; }
        public string employee_type { get; set; }
        public string employee_class { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
        public Nullable<decimal> pay_per_period { get; set; }
        public string rem_level { get; set; }
        public string rem_range { get; set; }
        public string car_flag { get; set; }
        public string phone_flag { get; set; }
        public string salary_continuance { get; set; }
        public string street_address_line1 { get; set; }
        public string street_address_line2 { get; set; }
        public string street_address_line3 { get; set; }
        public string street_city { get; set; }
        public string street_state { get; set; }
        public string street_post_code { get; set; }
        public string street_country_code { get; set; }
        public string street_telephone1 { get; set; }
        public string street_telephone2 { get; set; }
        public string street_telephone3 { get; set; }
        public string street_mobile1 { get; set; }
        public string street_mobile2 { get; set; }
        public string street_email1 { get; set; }
        public string street_email2 { get; set; }
        public string postal_address_line1 { get; set; }
        public string postal_address_line2 { get; set; }
        public string postal_address_line3 { get; set; }
        public string postal_city { get; set; }
        public string postal_state { get; set; }
        public string postal_post_code { get; set; }
        public string postal_country_code { get; set; }
        public string postal_telephone1 { get; set; }
        public string postal_telephone2 { get; set; }
        public string postal_telephone3 { get; set; }
        public string postal_mobile1 { get; set; }
        public string postal_mobile2 { get; set; }
        public string postal_email1 { get; set; }
        public string postal_email2 { get; set; }
        public string ethnic_group { get; set; }
        public string pay_period_unit { get; set; }
        public Nullable<decimal> units_per_period { get; set; }
        public string visa_type { get; set; }
        public Nullable<decimal> fte { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string contact_family_name { get; set; }
        public string contact_given_name { get; set; }
        public string contact_dependant_flag { get; set; }
        public string contact_type { get; set; }
        public string contact_address_line1 { get; set; }
        public string contact_address_line2 { get; set; }
        public string contact_address_line3 { get; set; }
        public string contact_address_city { get; set; }
        public string contact_address_state { get; set; }
        public string contact_address_post_code { get; set; }
        public string contact_address_country_code { get; set; }
        public string contact_telephone1 { get; set; }
        public string contact_telephone2 { get; set; }
        public string contact_telephone3 { get; set; }
        public string contact_mobile1 { get; set; }
        public string contact_mobile2 { get; set; }
        public string contact_email1 { get; set; }
        public string contact_email2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_accreditation_fact> employee_accreditation_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_accreditation_fact> employee_accreditation_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_contract_fact> employee_contract_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_contract_fact> employee_contract_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_booked_fact> employee_leave_booked_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_taken_fact> employee_leave_taken_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_position_fact> employee_position_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_termination_fact> employee_termination_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_accrued_fact> employee_leave_accrued_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_accrued_fact> employee_leave_accrued_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_booked_fact> employee_leave_booked_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_booked_txn_fact> employee_leave_booked_txn_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_booked_txn_fact> employee_leave_booked_txn_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_taken_fact> employee_leave_taken_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_payment_fact> employee_payment_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_position_fact> employee_position_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_profile_fact> employee_profile_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_profile_fact> employee_profile_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_recruitment_fact> employee_recruitment_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet_fact> employee_timesheet_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet_fact> employee_timesheet_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet_fact> employee_timesheet_fact2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_pattern_fact> work_pattern_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_pattern_fact> work_pattern_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<all_employees_report_fact> all_employees_report_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<all_employees_report_fact> all_employees_report_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<position_establishment_fact> position_establishment_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<position_establishment_fact> position_establishment_fact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_last_paid_date_fact> employee_last_paid_date_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_renumeration_fact> employee_renumeration_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_renumeration_fact> employee_renumeration_fact1 { get; set; }
    }
}
