//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_timesheet_fact
    {
        public int employee_timesheet_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int position_key { get; set; }
        public int employee_key { get; set; }
        public int manager_key { get; set; }
        public int manager_position_key { get; set; }
        public int timesheet_entry_date_key { get; set; }
        public int account_key { get; set; }
        public int pay_period_end_date_key { get; set; }
        public int payment_type_key { get; set; }
        public int authoriser_key { get; set; }
        public string entry_type { get; set; }
        public string authorised_flag { get; set; }
        public Nullable<System.TimeSpan> clock_in_time { get; set; }
        public Nullable<System.TimeSpan> clock_out_time { get; set; }
        public Nullable<decimal> units { get; set; }
        public string meal_break { get; set; }
        public string comments { get; set; }
        public Nullable<int> count { get; set; }
        public string status { get; set; }
    
        public virtual account_dim account_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
        public virtual date_dim date_dim1 { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual employee_dim employee_dim1 { get; set; }
        public virtual employee_dim employee_dim2 { get; set; }
        public virtual position_dim position_dim { get; set; }
        public virtual payment_type_dim payment_type_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual position_dim position_dim1 { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
    }
}
