//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_accreditation_fact
    {
        public int employee_accreditation_key { get; set; }
        public int employee_key { get; set; }
        public int manager_key { get; set; }
        public int manager_position_key { get; set; }
        public int received_date_key { get; set; }
        public int valid_until_date_key { get; set; }
        public int renewal_sent_date_key { get; set; }
        public int expiry_date_key { get; set; }
        public int organisation_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int accreditation_key { get; set; }
        public int position_key { get; set; }
        public string convictions { get; set; }
        public string qual_code { get; set; }
        public string serial_number { get; set; }
        public string extend_qual_desc { get; set; }
        public string qual_level { get; set; }
        public string remarks { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual accreditation_dim accreditation_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
        public virtual date_dim date_dim1 { get; set; }
        public virtual date_dim date_dim2 { get; set; }
        public virtual date_dim date_dim3 { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual position_dim position_dim { get; set; }
        public virtual employee_dim employee_dim1 { get; set; }
        public virtual organisation_dim organisation_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
    }
}
