//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_pay_temp
    {
        public int employee_pay_temp_key { get; set; }
        public Nullable<int> employee_key { get; set; }
        public string id_number { get; set; }
        public string organisation_code { get; set; }
        public Nullable<int> organisation_key { get; set; }
        public string portfolio_code { get; set; }
        public Nullable<int> portfolio_key { get; set; }
        public string service_stream_code { get; set; }
        public Nullable<int> service_stream_key { get; set; }
        public string program_code { get; set; }
        public Nullable<int> program_key { get; set; }
        public string position_code { get; set; }
        public Nullable<int> position_key { get; set; }
        public Nullable<int> pay_period_end_date_key { get; set; }
        public string pay_document_no { get; set; }
        public Nullable<decimal> number_units { get; set; }
        public Nullable<decimal> pay_item_rate { get; set; }
        public Nullable<decimal> pay_item_amount { get; set; }
        public string taxable { get; set; }
        public Nullable<int> pay_component_def { get; set; }
    }
}
