//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_position_fact
    {
        public int employee_position_key { get; set; }
        public string new_position_flag { get; set; }
        public int manager_key { get; set; }
        public int manager_position_key { get; set; }
        public int organisation_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int position_key { get; set; }
        public string primary_position_flag { get; set; }
        public int employee_key { get; set; }
        public int position_start_date_key { get; set; }
        public int anniversary_date_key { get; set; }
        public int increment_date_key { get; set; }
        public int last_increment_date_key { get; set; }
        public int service_date_key { get; set; }
        public int position_vacant_date_key { get; set; }
        public Nullable<int> permanent_ft_count { get; set; }
        public Nullable<int> permanent_pt_count { get; set; }
        public Nullable<int> contract_ft_count { get; set; }
        public Nullable<int> contract_pt_count { get; set; }
        public Nullable<int> casual_count { get; set; }
        public Nullable<int> total_count { get; set; }
    
        public virtual date_dim date_dim { get; set; }
        public virtual date_dim date_dim1 { get; set; }
        public virtual date_dim date_dim2 { get; set; }
        public virtual date_dim date_dim3 { get; set; }
        public virtual date_dim date_dim4 { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual employee_dim employee_dim1 { get; set; }
        public virtual position_dim position_dim { get; set; }
        public virtual organisation_dim organisation_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual position_dim position_dim1 { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
    }
}
