//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_payment_fact
    {
        public int employee_payment_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int position_key { get; set; }
        public int employee_key { get; set; }
        public int pay_period_date_key { get; set; }
        public int account_key { get; set; }
        public Nullable<decimal> number_units { get; set; }
        public string pay_period_unit { get; set; }
        public string pay_period_unit_desc { get; set; }
        public Nullable<decimal> pay_item_rate { get; set; }
        public Nullable<decimal> pay_item_amount { get; set; }
        public string taxable { get; set; }
        public string payment { get; set; }
        public Nullable<int> pay_component_def { get; set; }
        public Nullable<decimal> pay_component_ref { get; set; }
        public string pay_period_type { get; set; }
        public string posted_ind { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual account_dim account_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
        public virtual employee_dim employee_dim { get; set; }
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual position_dim position_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual service_stream_dim service_stream_dim { get; set; }
    }
}
