//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class labour_turnover_report_fact
    {
        public int labour_turnover_report__key { get; set; }
        public int month_date_key { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> lost { get; set; }
        public Nullable<decimal> monthly { get; set; }
        public Nullable<decimal> last_year_monthly { get; set; }
        public Nullable<decimal> yearly { get; set; }
    
        public virtual month_dim month_dim { get; set; }
    }
}
