//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_type_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public leave_type_dim()
        {
            this.employee_leave_accrued_fact = new HashSet<employee_leave_accrued_fact>();
            this.employee_leave_booked_fact = new HashSet<employee_leave_booked_fact>();
            this.employee_leave_booked_txn_fact = new HashSet<employee_leave_booked_txn_fact>();
            this.employee_leave_snapshot_fact = new HashSet<employee_leave_snapshot_fact>();
            this.employee_leave_taken_fact = new HashSet<employee_leave_taken_fact>();
        }
    
        public int leave_type_key { get; set; }
        public string leave_name { get; set; }
        public string leave_code { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_accrued_fact> employee_leave_accrued_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_booked_fact> employee_leave_booked_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_booked_txn_fact> employee_leave_booked_txn_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_snapshot_fact> employee_leave_snapshot_fact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_leave_taken_fact> employee_leave_taken_fact { get; set; }
    }
}
