//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_hris
{
    using System;
    using System.Collections.Generic;
    
    public partial class program_temp
    {
        public int program_temp_key { get; set; }
        public Nullable<int> program_key { get; set; }
        public string program_code { get; set; }
        public string service_stream_code { get; set; }
    }
}
