CREATE TABLE [extract].[F1TIM_FMT_LNE](
	[TS_SYSTEM_NAME] [varchar](10) NOT NULL,
	[TS_FMT_NAME] [varchar](10) NOT NULL,
	[TS_LINE_ID] [smallint] NOT NULL,
	[TS_LINE_SEQ_NBR] [smallint] NULL,
	[VERS] [int] NULL,
	[TS_LINE_TITLE] [varchar](40) NULL,
	[TS_LINE_TYPE] [varchar](2) NULL,
	[PAY_COMPONENT_REF] [decimal](10, 1) NULL,
	[PAY_COMPONENT_IND] [varchar](1) NULL,
	[EMP_CONDITION_IND] [varchar](1) NULL,
	[DEF_LDG_CODE] [varchar](2) NULL,
	[COSTING_TYPE] [varchar](2) NULL,
	[ASSIGNED_TASK_IND] [varchar](1) NULL,
	[BILLING_IND] [varchar](1) NULL,
	[BUDGET_IND] [varchar](1) NULL,
	[FORECAST_IND] [varchar](1) NULL,
	[PLANT_ENTRY_IND] [varchar](1) NULL,
	[LDG_CODE_IND] [varchar](1) NULL,
	[ITEM_TYPE] [varchar](10) NULL,
	[TECHONE_FLD1] [varchar](40) NULL,
	[TECHONE_FLD2] [varchar](40) NULL,
	[TECHONE_FLD3] [varchar](40) NULL,
	[TECHONE_FLD4] [varchar](40) NULL,
	[TECHONE_FLD5] [varchar](40) NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[SUPER_VISIBLE_IND] [varchar](1) NULL,
	[EXCLUDE_TOTAL_IND] [varchar](1) NULL,
	[ACCNBRI_IND] [varchar](1) NULL,
	[LINE_DESCR_IND] [varchar](1) NULL,
	[LINE_DESCR] [varchar](40) NULL,
	[LINE_DESCR_CMP] [varchar](2) NULL,
	[LINE_DESCR_CMP_TYP] [varchar](1) NULL,
	[LDG_CODE_CAPTION] [varchar](30) NULL,
	[PAY_COMP_CAPTION] [varchar](30) NULL,
	[ROSTER_IND] [varchar](1) NULL,
	[CLOCKIN_HRS_IND] [varchar](1) NULL,
	[COST_RATE_IND] [varchar](1) NULL,
	[COST_RATE_TYPE] [varchar](4) NULL,
	[COST_RATE_CODE] [varchar](4) NULL,
	[COMP_PREC_RULE] [varchar](1) NULL,
	[OTH_ITEM_TYPE] [varchar](10) NULL,
	[PROJ_MGR_IND] [varchar](1) NULL,
	[PROJ_MGR_EDIT_IND] [varchar](1) NULL,
	[ACCOUNT_MSK_ORDER] [varchar](50) NULL,
	[ACCOUNT_MSKI] [varchar](32) NULL,
	[SERVICE_RATE_SRC] [varchar](1) NULL,
	[LINE_ITEM_TYPE] [varchar](10) NULL,
	[SERVICE_RATE_TYPE] [varchar](4) NULL,
	[SERVICE_RATE_CODE] [varchar](4) NULL,
	[PLANT_MAP_OPTN] [varchar](2) NULL,
	[ASSET_REG_NAME] [varchar](8) NULL,
	[ENABLE_METER1_IND] [varchar](1) NULL,
	[ENABLE_METER2_IND] [varchar](1) NULL,
	[ENABLE_METER3_IND] [varchar](1) NULL,
	[ENABLE_METER4_IND] [varchar](1) NULL,
 CONSTRAINT [F1FTFLN_IDX1] PRIMARY KEY CLUSTERED 
(
	[TS_SYSTEM_NAME] ASC,
	[TS_FMT_NAME] ASC,
	[TS_LINE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO