-- creating table 'hrhmn_empl_job_pos'
create table extract.[hrhmn_empl_job_pos] (
   	[ID_NUMBER] [int] NOT NULL,
	[EFFECTIVE_DATE] [datetime] NOT NULL,
	[POSITION_CODE] [varchar](10) NOT NULL,
	[POSITION_TYPE_IND] [varchar](1) NULL,
	[END_DATE] [datetime] NULL,
	[JOB_POS_TITLE] [varchar](50) NULL,
	[REASON_TYPE] [varchar](10) NULL,
	[REASON_DESCR] [varchar](50) NULL,
	[DEPARTMENT_CODE] [varchar](10) NULL,
	[ID_NUMBER_SUPERVSR] [int] NULL,
	[WORK_GROUP] [varchar](10) NULL,
	[WORK_LOCATION] [varchar](10) NULL,
	[EMPL_COND_AWARD] [varchar](10) NULL,
	[EMPL_COND_GRADE] [varchar](10) NULL,
	[EMPL_COND_LEVEL] [varchar](10) NULL,
	[ENT_TECH_KEY] [int] NULL,
	[TRADE_CODE] [varchar](10) NULL,
	[UNION_CODE] [varchar](10) NULL,
	[SEASON_STATUS] [int] NULL,
	[SUPERVISOR_IND] [varchar](1) NULL,
	[TRADESMAN_IND] [varchar](1) NULL,
	[TMC_SEQUENCE_NO] [int] NULL,
	[TMC_CALC_METHOD] [varchar](10) NULL,
	[TMC_LEAVE_RULE] [varchar](1) NULL,
	[RECOV_ITEM_TYPE] [varchar](10) NULL,
	[RECOV_ITEM_CODE] [varchar](10) NULL,
	[ONCRECOV_ITEM_TYPE] [varchar](10) NULL,
	[ONCRECOV_ITEM_CODE] [varchar](10) NULL,
	[COST_TYPE] [varchar](4) NULL,
	[COST_CODE] [varchar](4) NULL,
	[TS_SYSTEM_NAME] [varchar](10) NULL,
	[TS_FMT_NAME] [varchar](10) NULL,
	[TS_ENTRY_IND] [varchar](1) NULL,
	[TECHONE_FLD1] [varchar](40) NULL,
	[TECHONE_FLD2] [varchar](40) NULL,
	[TECHONE_FLD3] [varchar](40) NULL,
	[TECHONE_FLD4] [varchar](40) NULL,
	[ROW_STATUS] [int] NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[VERS] [int] NULL,
	[ORG_UNIT_CODE] [varchar](10) NULL,
	[POSITION_SUPERVSR] [varchar](10) NULL,
	[FULL_TIME_EQUIVALENT] [decimal](18, 6) NULL,
	[INCREMENT_IND] [varchar](1) NULL,
	[HOME_COST_CENTRE] [varchar](10) NULL,
	[DISB_CODE] [varchar](10) NULL,
	[SECURITY_PROFILE_NAME] [varchar](50) NULL,
	[COMPANY_SUPERVSR] [int] NULL,
	[APPOINT_START_DATE] [datetime] NULL,
	[APPOINT_END_DATE] [datetime] NULL,
	[LAST_EFFECTIVE_APPOINT_IND] [varchar](1) NULL,
	[COMPANY_SUPERVSR_1] [int] NULL,
	[POSITION_SUPERVSR_1] [varchar](10) NULL,
	[COMPANY_SUPERVSR_2] [int] NULL,
	[POSITION_SUPERVSR_2] [varchar](10) NULL,
	[ORG_SYSTEM_CODE] [varchar](20) NULL,
	[SUPERVISOR_IND_1] [varchar](1) NULL,
	[SUPERVISOR_IND_2] [varchar](1) NULL,
 CONSTRAINT [HRFHJP_IDX1] PRIMARY KEY CLUSTERED 
(
	[ID_NUMBER] ASC,
	[EFFECTIVE_DATE] ASC,
	[POSITION_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO