CREATE TABLE [extract].[HREEN_EMPL_ENT_CTL](
	[ID_NUMBER] [int] NOT NULL,
	[ENT_TECH_KEY] [int] NOT NULL,
	[EFFECTIVE_DATE] [datetime] NOT NULL,
	[END_DATE] [datetime] NULL,
	[ENTITLEMENT_TITLE] [varchar](50) NULL,
	[REASON_TYPE] [varchar](10) NULL,
	[REASON_DESCR] [varchar](50) NULL,
	[TECHONE_FLD1] [varchar](40) NULL,
	[TECHONE_FLD2] [varchar](40) NULL,
	[TECHONE_FLD3] [varchar](40) NULL,
	[TECHONE_FLD4] [varchar](40) NULL,
	[ROW_STATUS] [int] NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[VERS] [int] NULL,
 CONSTRAINT [HRFEEL_IDX1] PRIMARY KEY CLUSTERED 
(
	[ID_NUMBER] ASC,
	[ENT_TECH_KEY] ASC,
	[EFFECTIVE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO