CREATE TABLE [extract].[HRHMN_EMPLCONT_DTL](
	[ID_NUMBER] [int] NOT NULL,
	[CONTACT_SEQ_NUMBER] [int] NOT NULL,
	[CONTCT_DISPLAY_SEQ] [int] NULL,
	[CONTCT_FAMILY_NAME] [varchar](50) NULL,
	[CONTCT_GIVEN_NAMES] [varchar](50) NULL,
	[ADDRSS_POSTAL_CODE] [int] NULL,
	[ADDRSS_STREET_CODE] [int] NULL,
	[ROW_STATUS] [int] NULL,
	[CLOSED_USER] [varchar](14) NULL,
	[CLOSED_DATE] [datetime] NULL,
	[CLOSED_TIME] [int] NULL,
	[CLOSED_TERM] [varchar](10) NULL,
	[CLOSED_WINDOW] [varchar](8) NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[VERS] [int] NULL,
	[DEPENDANT_IND] [varchar](1) NULL,
	[CONTACT_TYPE] [varchar](20) NULL,
 CONSTRAINT [HRFHCD_IDX1] PRIMARY KEY CLUSTERED 
(
	[ID_NUMBER] ASC,
	[CONTACT_SEQ_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO