-- creating table 'hrpay_payitems_summpmnt'
create table [extract].[hrpay_payitems_summpmnt] (
    [company_code] int  not null,
    [pay_period_enddate] datetime  not null,
    [document_type] varchar(10)  not null,
    [employee_id] int  not null,
    [pay_component_ref] decimal(18,6)  not null,
    [super_fund_code] varchar(20)  not null,
    [unit_type] varchar(20)  null,
    [number_of_units] decimal(18,6)  null,
    [ytd_opening_amount] decimal(18,6)  null,
    [period_amount] decimal(18,6)  null,
    [ytd_closing_amount] decimal(18,6)  null,
    [prev_amount] decimal(18,6)  null,
    [pay_component_def] decimal(18,6)  null,
    [payment_type] varchar(1)  null,
    [taxable_ind] varchar(1)  null,
    [bank_code] varchar(20)  null,
    [bank_branch_number] varchar(32)  null,
    [bank_account_number] varchar(40)  null,
    [bank_account_name] varchar(50)  null,
    [super_institute_code] varchar(10)  null,
    [super_member_number] varchar(32)  null,
    [super_contribution_type] varchar(10)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null
);
go