CREATE TABLE [extract].[GLF_SELN_CODE](
	[VERS] [smallint] NULL,
	[SELN_TYPE] [varchar](8) NOT NULL,
	[SELN_CODE] [varchar](8) NOT NULL,
	[DESCR] [varchar](20) NULL,
	[FDESCR] [varchar](60) NULL,
	[NARR1] [varchar](40) NULL,
	[NARR2] [varchar](40) NULL,
	[NARR3] [varchar](40) NULL,
	[PAR_SELN_TYPE1] [varchar](8) NULL,
	[PAR_SELN_CODE1] [varchar](8) NULL,
	[PAR_SELN_TYPE2] [varchar](8) NULL,
	[PAR_SELN_CODE2] [varchar](8) NULL,
	[PAR_SELN_TYPE3] [varchar](8) NULL,
	[PAR_SELN_CODE3] [varchar](8) NULL,
	[PAR_SELN_TYPE4] [varchar](8) NULL,
	[PAR_SELN_CODE4] [varchar](8) NULL,
	[PAR_SELN_TYPE5] [varchar](8) NULL,
	[PAR_SELN_CODE5] [varchar](8) NULL,
	[PAR_SELN_TYPE6] [varchar](8) NULL,
	[PAR_SELN_CODE6] [varchar](8) NULL,
	[USER_FLD1] [varchar](40) NULL,
	[USER_NUM1] [decimal](18, 6) NULL,
	[USER_DATEI1] [datetime] NULL,
	[USER_FLD2] [varchar](40) NULL,
	[USER_NUM2] [decimal](18, 6) NULL,
	[USER_DATEI2] [datetime] NULL,
	[USER_FLD3] [varchar](40) NULL,
	[USER_NUM3] [decimal](18, 6) NULL,
	[USER_DATEI3] [datetime] NULL,
	[USER_FLD4] [varchar](40) NULL,
	[USER_NUM4] [decimal](18, 6) NULL,
	[USER_DATEI4] [datetime] NULL,
	[USER_FLD5] [varchar](40) NULL,
	[USER_NUM5] [decimal](18, 6) NULL,
	[USER_DATEI5] [datetime] NULL,
	[USER_FLD6] [varchar](40) NULL,
	[USER_NUM6] [decimal](18, 6) NULL,
	[USER_DATEI6] [datetime] NULL,
	[USER_FLD7] [varchar](40) NULL,
	[USER_NUM7] [decimal](18, 6) NULL,
	[USER_DATEI7] [datetime] NULL,
	[USER_FLD8] [varchar](40) NULL,
	[USER_NUM8] [decimal](18, 6) NULL,
	[USER_DATEI8] [datetime] NULL,
	[USER_FLD9] [varchar](40) NULL,
	[USER_NUM9] [decimal](18, 6) NULL,
	[USER_DATEI9] [datetime] NULL,
	[USER_FLD10] [varchar](40) NULL,
	[USER_NUM10] [decimal](18, 6) NULL,
	[USER_DATEI10] [datetime] NULL,
	[USER_FLD11] [varchar](40) NULL,
	[USER_NUM11] [decimal](18, 6) NULL,
	[USER_DATEI11] [datetime] NULL,
	[USER_FLD12] [varchar](40) NULL,
	[USER_NUM12] [decimal](18, 6) NULL,
	[USER_DATEI12] [datetime] NULL,
	[USER_FLD13] [varchar](40) NULL,
	[USER_NUM13] [decimal](18, 6) NULL,
	[USER_DATEI13] [datetime] NULL,
	[USER_FLD14] [varchar](40) NULL,
	[USER_NUM14] [decimal](18, 6) NULL,
	[USER_DATEI14] [datetime] NULL,
	[USER_FLD15] [varchar](40) NULL,
	[USER_NUM15] [decimal](18, 6) NULL,
	[USER_DATEI15] [datetime] NULL,
	[USER_FLD16] [varchar](40) NULL,
	[USER_NUM16] [decimal](18, 6) NULL,
	[USER_DATEI16] [datetime] NULL,
	[USER_FLD17] [varchar](40) NULL,
	[USER_NUM17] [decimal](18, 6) NULL,
	[USER_DATEI17] [datetime] NULL,
	[USER_FLD18] [varchar](40) NULL,
	[USER_NUM18] [decimal](18, 6) NULL,
	[USER_DATEI18] [datetime] NULL,
	[USER_FLD19] [varchar](40) NULL,
	[USER_NUM19] [decimal](18, 6) NULL,
	[USER_DATEI19] [datetime] NULL,
	[USER_FLD20] [varchar](40) NULL,
	[USER_NUM20] [decimal](18, 6) NULL,
	[USER_DATEI20] [datetime] NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[COMP_CHART_NAME] [varchar](8) NULL,
	[COMP_CHART_IND] [varchar](1) NULL,
	[STAT_IND] [varchar](1) NULL,
 CONSTRAINT [GLFSCD_IDX1] PRIMARY KEY CLUSTERED 
(
	[SELN_TYPE] ASC,
	[SELN_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO