CREATE TABLE [extract].[HRTIM_TSHEET_ENTRY](
	[TSHEET_ENTRY_ID] [int]  NOT NULL,
	[EMPLOYEE_ID] [int] NULL,
	[TIMESHEET_DATE] [datetime] NULL,
	[TS_END_DATE] [datetime] NULL,
	[POSITION_CODE] [varchar](10) NULL,
	[SYSTEM_NAME] [varchar](10) NULL,
	[FORMAT_NAME] [varchar](10) NULL,
	[ENTRY_TYPE_ID] [smallint] NULL,
	[ENTRY_TYPE] [varchar](2) NULL,
	[AUTHORISED_IND] [varchar](1) NULL,
	[HISTORICAL_IND] [varchar](1) NULL,
	[UNITS] [decimal](18, 6) NULL,
	[UNIT_TYPE] [varchar](10) NULL,
	[CLOCK_IN] [int] NULL,
	[CLOCK_OUT] [int] NULL,
	[COMMENTS] [varchar](1000) NULL,
	[LDG_CODE] [varchar](2) NULL,
	[ACCNBRI] [varchar](32) NULL,
	[PAY_COMPONENT_REF] [decimal](10, 1) NULL,
	[PAYROLL_COND_AWARD] [varchar](10) NULL,
	[PAYROLL_COND_GRADE] [varchar](10) NULL,
	[PAYROLL_COND_LEVEL] [varchar](10) NULL,
	[PAYROLL_RATE] [decimal](18, 6) NULL,
	[LEAVE_ID] [int] NULL,
	[LEAVE_ALT_UNIT_TYPE] [varchar](10) NULL,
	[LEAVE_ALT_UNITS] [decimal](18, 6) NULL,
	[PARENT_TSHEET_ENTRY_ID] [int] NULL,
	[PLANT_ITEM_TYPE] [varchar](10) NULL,
	[PLANT_ITEM_CODE] [varchar](10) NULL,
	[PLANT_ASSNBRI] [varchar](32) NULL,
	[PLANT_ASSET_REG_NAME] [varchar](8) NULL,
	[PLANT_RATE_TYPE] [varchar](4) NULL,
	[PLANT_RATE_CODE] [varchar](4) NULL,
	[PLANT_METER1_READ_UNITS] [decimal](18, 6) NULL,
	[PLANT_METER2_READ_UNITS] [decimal](18, 6) NULL,
	[PLANT_METER3_READ_UNITS] [decimal](18, 6) NULL,
	[PLANT_METER4_READ_UNITS] [decimal](18, 6) NULL,
	[PAID_IND] [varchar](1) NULL,
	[POSTED_IND] [varchar](1) NULL,
	[APPROVAL_TYPE] [varchar](10) NULL,
	[APPROVAL_DATETIME] [datetime] NULL,
	[APPROVAL_USER_ID] [varchar](14) NULL,
	[SELN_TYPE_CODE1] [varchar](8) NULL,
	[SELN_TYPE_CODE2] [varchar](8) NULL,
	[SELN_TYPE_CODE3] [varchar](8) NULL,
	[SELN_TYPE_CODE4] [varchar](8) NULL,
	[SELN_TYPE_CODE5] [varchar](8) NULL,
	[SELN_TYPE_CODE6] [varchar](8) NULL,
	[SELN_TYPE_CODE7] [varchar](8) NULL,
	[SELN_TYPE_CODE8] [varchar](8) NULL,
	[SELN_TYPE_CODE9] [varchar](8) NULL,
	[SELN_TYPE_CODE10] [varchar](8) NULL,
	[SELN_TYPE_CODE11] [varchar](8) NULL,
	[SELN_TYPE_CODE12] [varchar](8) NULL,
	[USER_FLD1] [varchar](40) NULL,
	[USER_FLD2] [varchar](40) NULL,
	[USER_FLD3] [varchar](40) NULL,
	[USER_FLD4] [varchar](40) NULL,
	[USER_FLD5] [varchar](40) NULL,
	[USER_FLD6] [varchar](40) NULL,
	[USER_FLD7] [varchar](40) NULL,
	[USER_FLD8] [varchar](40) NULL,
	[USER_FLD9] [varchar](40) NULL,
	[USER_FLD10] [varchar](40) NULL,
	[USER_FLD11] [varchar](40) NULL,
	[USER_FLD12] [varchar](40) NULL,
	[USER_DATEI1] [datetime] NULL,
	[USER_DATEI2] [datetime] NULL,
	[USER_DATEI3] [datetime] NULL,
	[USER_DATEI4] [datetime] NULL,
	[USER_DATEI5] [datetime] NULL,
	[USER_DATEI6] [datetime] NULL,
	[USER_DATEI7] [datetime] NULL,
	[USER_DATEI8] [datetime] NULL,
	[USER_DATEI9] [datetime] NULL,
	[USER_DATEI10] [datetime] NULL,
	[USER_DATEI11] [datetime] NULL,
	[USER_DATEI12] [datetime] NULL,
	[USER_NUM1] [decimal](18, 6) NULL,
	[USER_NUM2] [decimal](18, 6) NULL,
	[USER_NUM3] [decimal](18, 6) NULL,
	[USER_NUM4] [decimal](18, 6) NULL,
	[USER_NUM5] [decimal](18, 6) NULL,
	[USER_NUM6] [decimal](18, 6) NULL,
	[USER_NUM7] [decimal](18, 6) NULL,
	[USER_NUM8] [decimal](18, 6) NULL,
	[USER_NUM9] [decimal](18, 6) NULL,
	[USER_NUM10] [decimal](18, 6) NULL,
	[USER_NUM11] [decimal](18, 6) NULL,
	[USER_NUM12] [decimal](18, 6) NULL,
	[VERS] [int] NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[RES_ACTY_CODE] [varchar](32) NULL,
	[REVERSED_TSHEET_ENTRY_ID] [int] NULL,
	[COMPANY_CODE] [int] NULL,
 CONSTRAINT [HRTIM_TSHEET_ENTRY_IDX1] PRIMARY KEY CLUSTERED 
(
	[TSHEET_ENTRY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO