-- creating table 'hrpay_master_ctl'
create table [extract].[hrpay_master_ctl] (
    [document_type] varchar(10)  not null,
    [company_code] int  not null,
    [pay_document_no] int  not null,
    [id_number] int  null,
    [pay_period_enddate] datetime  null,
    [pay_period_type] varchar(10)  null,
    [base_amount] decimal(14,4)  null,
    [gross_amount] decimal(14,4)  null,
    [taxable_income] decimal(14,4)  null,
    [total_tax_amount] decimal(14,4)  null,
    [nett_pay] decimal(14,4)  null,
    [pay_calc_date] datetime  null,
    [jnl_creation_date] datetime  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [paid_date] datetime  null,
    [no_of_pay_periods] decimal(10,4)  null,
    [amount_paid] decimal(14,4)  null,
    [payment_method_pc] decimal(10,4)  null,
    [pay_period_startdate] datetime  null,
    [periodend_position_code] varchar(20)  null,
    [periodend_job_effdate] datetime  null,
    [periodend_tax_effdate] datetime  null
);
go