create table [extract].[hrsys_usrseln_dtl](
	[entity_type] [varchar](10) not null,
	[unique_nbr] [int] not null,
	[entity_key_1] [varchar](40) null,
	[entity_key_2] [varchar](40) null,
	[entity_key_3] [varchar](40) null,
	[entity_key_4] [varchar](40) null,
	[entity_key_5] [varchar](40) null,
	[entity_key_6] [varchar](40) null,
	[entity_key_7] [varchar](40) null,
	[entity_key_8] [varchar](40) null,
	[entity_key_9] [varchar](40) null,
	[entity_key_10] [varchar](40) null,
	[seln_code1] [varchar](10) null,
	[seln_code2] [varchar](10) null,
	[seln_code3] [varchar](10) null,
	[seln_code4] [varchar](10) null,
	[seln_code5] [varchar](10) null,
	[seln_code6] [varchar](10) null,
	[seln_code7] [varchar](10) null,
	[seln_code8] [varchar](10) null,
	[seln_code9] [varchar](10) null,
	[seln_code10] [varchar](10) null,
	[seln_code11] [varchar](10) null,
	[seln_code12] [varchar](10) null,
	[seln_code13] [varchar](10) null,
	[seln_code14] [varchar](10) null,
	[seln_code15] [varchar](10) null,
	[seln_code16] [varchar](10) null,
	[seln_code17] [varchar](10) null,
	[seln_code18] [varchar](10) null,
	[seln_code19] [varchar](10) null,
	[seln_code20] [varchar](10) null,
	[val_alpha1] [varchar](40) null,
	[val_alpha2] [varchar](40) null,
	[val_alpha3] [varchar](40) null,
	[val_alpha4] [varchar](40) null,
	[val_alpha5] [varchar](40) null,
	[val_alpha6] [varchar](40) null,
	[val_alpha7] [varchar](40) null,
	[val_alpha8] [varchar](40) null,
	[val_alpha9] [varchar](40) null,
	[val_alpha10] [varchar](40) null,
	[val_alpha11] [varchar](40) null,
	[val_alpha12] [varchar](40) null,
	[val_alpha13] [varchar](40) null,
	[val_alpha14] [varchar](40) null,
	[val_alpha15] [varchar](40) null,
	[val_alpha16] [varchar](40) null,
	[val_alpha17] [varchar](40) null,
	[val_alpha18] [varchar](40) null,
	[val_alpha19] [varchar](40) null,
	[val_alpha20] [varchar](40) null,
	[val_num1] [decimal](18, 6) null,
	[val_num2] [decimal](18, 6) null,
	[val_num3] [decimal](18, 6) null,
	[val_num4] [decimal](18, 6) null,
	[val_num5] [decimal](18, 6) null,
	[val_num6] [decimal](18, 6) null,
	[val_num7] [decimal](18, 6) null,
	[val_num8] [decimal](18, 6) null,
	[val_num9] [decimal](18, 6) null,
	[val_num10] [decimal](18, 6) null,
	[val_num11] [decimal](18, 6) null,
	[val_num12] [decimal](18, 6) null,
	[val_num13] [decimal](18, 6) null,
	[val_num14] [decimal](18, 6) null,
	[val_num15] [decimal](18, 6) null,
	[val_num16] [decimal](18, 6) null,
	[val_num17] [decimal](18, 6) null,
	[val_num18] [decimal](18, 6) null,
	[val_num19] [decimal](18, 6) null,
	[val_num20] [decimal](18, 6) null,
	[val_date1] [datetime] null,
	[val_date2] [datetime] null,
	[val_date3] [datetime] null,
	[val_date4] [datetime] null,
	[val_date5] [datetime] null,
	[val_date6] [datetime] null,
	[val_date7] [datetime] null,
	[val_date8] [datetime] null,
	[val_date9] [datetime] null,
	[val_date10] [datetime] null,
	[val_date11] [datetime] null,
	[val_date12] [datetime] null,
	[val_date13] [datetime] null,
	[val_date14] [datetime] null,
	[val_date15] [datetime] null,
	[val_date16] [datetime] null,
	[val_date17] [datetime] null,
	[val_date18] [datetime] null,
	[val_date19] [datetime] null,
	[val_date20] [datetime] null,
	[cruser] [varchar](14) null,
	[crdatei] [datetime] null,
	[crtimei] [int] null,
	[crterm] [varchar](10) null,
	[crwindow] [varchar](8) null,
	[last_mod_user] [varchar](14) null,
	[last_mod_datei] [datetime] null,
	[last_mod_timei] [int] null,
	[last_mod_term] [varchar](10) null,
	[last_mod_window] [varchar](8) null,
	[vers] [smallint] null,
 constraint [hrfusd_idx1] primary key clustered 
(
	[entity_type] asc,
	[unique_nbr] asc
)with (pad_index = off, statistics_norecompute = off, ignore_dup_key = off, allow_row_locks = on, allow_page_locks = on) on [primary]
) on [primary]

go