
CREATE TABLE [extract].[HRHMN_USR_FLD](
	[ID_NUMBER] [int] NOT NULL,
	[SELN_CD1] [varchar](10) NULL,
	[SELN_CD2] [varchar](10) NULL,
	[SELN_CD3] [varchar](10) NULL,
	[SELN_CD4] [varchar](10) NULL,
	[SELN_CD5] [varchar](10) NULL,
	[SELN_CD6] [varchar](10) NULL,
	[SELN_CD7] [varchar](10) NULL,
	[SELN_CD8] [varchar](10) NULL,
	[SELN_CD9] [varchar](10) NULL,
	[SELN_CD10] [varchar](10) NULL,
	[SELN_CD11] [varchar](10) NULL,
	[SELN_CD12] [varchar](10) NULL,
	[SELN_CD13] [varchar](10) NULL,
	[SELN_CD14] [varchar](10) NULL,
	[SELN_CD15] [varchar](10) NULL,
	[SELN_CD16] [varchar](10) NULL,
	[SELN_CD17] [varchar](10) NULL,
	[SELN_CD18] [varchar](10) NULL,
	[SELN_CD19] [varchar](10) NULL,
	[SELN_CD20] [varchar](10) NULL,
	[VAL_ALPHA1] [varchar](40) NULL,
	[VAL_ALPHA2] [varchar](40) NULL,
	[VAL_ALPHA3] [varchar](40) NULL,
	[VAL_ALPHA4] [varchar](40) NULL,
	[VAL_ALPHA5] [varchar](40) NULL,
	[VAL_ALPHA6] [varchar](40) NULL,
	[VAL_ALPHA7] [varchar](40) NULL,
	[VAL_ALPHA8] [varchar](40) NULL,
	[VAL_ALPHA9] [varchar](40) NULL,
	[VAL_ALPHA10] [varchar](40) NULL,
	[VAL_ALPHA11] [varchar](40) NULL,
	[VAL_ALPHA12] [varchar](40) NULL,
	[VAL_ALPHA13] [varchar](40) NULL,
	[VAL_ALPHA14] [varchar](40) NULL,
	[VAL_ALPHA15] [varchar](40) NULL,
	[VAL_ALPHA16] [varchar](40) NULL,
	[VAL_ALPHA17] [varchar](40) NULL,
	[VAL_ALPHA18] [varchar](40) NULL,
	[VAL_ALPHA19] [varchar](40) NULL,
	[VAL_ALPHA20] [varchar](40) NULL,
	[VAL_NUM1] [decimal](18, 6) NULL,
	[VAL_NUM2] [decimal](18, 6) NULL,
	[VAL_NUM3] [decimal](18, 6) NULL,
	[VAL_NUM4] [decimal](18, 6) NULL,
	[VAL_NUM5] [decimal](18, 6) NULL,
	[VAL_NUM6] [decimal](18, 6) NULL,
	[VAL_NUM7] [decimal](18, 6) NULL,
	[VAL_NUM8] [decimal](18, 6) NULL,
	[VAL_NUM9] [decimal](18, 6) NULL,
	[VAL_NUM10] [decimal](18, 6) NULL,
	[VAL_NUM11] [decimal](18, 6) NULL,
	[VAL_NUM12] [decimal](18, 6) NULL,
	[VAL_NUM13] [decimal](18, 6) NULL,
	[VAL_NUM14] [decimal](18, 6) NULL,
	[VAL_NUM15] [decimal](18, 6) NULL,
	[VAL_NUM16] [decimal](18, 6) NULL,
	[VAL_NUM17] [decimal](18, 6) NULL,
	[VAL_NUM18] [decimal](18, 6) NULL,
	[VAL_NUM19] [decimal](18, 6) NULL,
	[VAL_NUM20] [decimal](18, 6) NULL,
	[VAL_DATE1] [datetime] NULL,
	[VAL_DATE2] [datetime] NULL,
	[VAL_DATE3] [datetime] NULL,
	[VAL_DATE4] [datetime] NULL,
	[VAL_DATE5] [datetime] NULL,
	[VAL_DATE6] [datetime] NULL,
	[VAL_DATE7] [datetime] NULL,
	[VAL_DATE8] [datetime] NULL,
	[VAL_DATE9] [datetime] NULL,
	[VAL_DATE10] [datetime] NULL,
	[VAL_DATE11] [datetime] NULL,
	[VAL_DATE12] [datetime] NULL,
	[VAL_DATE13] [datetime] NULL,
	[VAL_DATE14] [datetime] NULL,
	[VAL_DATE15] [datetime] NULL,
	[VAL_DATE16] [datetime] NULL,
	[VAL_DATE17] [datetime] NULL,
	[VAL_DATE18] [datetime] NULL,
	[VAL_DATE19] [datetime] NULL,
	[VAL_DATE20] [datetime] NULL,
	[ROW_STATUS] [int] NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[CLOSED_USER] [varchar](14) NULL,
	[CLOSED_DATEI] [datetime] NULL,
	[CLOSED_TIMEI] [int] NULL,
	[CLOSED_TERM] [varchar](10) NULL,
	[CLOSED_WINDOW] [varchar](8) NULL,
	[VERS] [smallint] NULL,
 CONSTRAINT [HRESU_IDX1] PRIMARY KEY CLUSTERED 
(
	[ID_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO