-- creating table 'hrhmn_emplqual_dtl'
create table [extract].[hrhmn_emplqual_dtl] (
    [ID_NUMBER] [int] NOT NULL,
	[QUAL_CODE] [varchar](10) NOT NULL,
	[QUAL_ISSUE_DATE] [datetime] NULL,
	[SERIAL_NUMBER] [varchar](20) NULL,
	[QUAL_CANCEL_DATE] [datetime] NULL,
	[EXTEND_QUAL_DESC] [varchar](50) NULL,
	[QUAL_LEVEL] [varchar](50) NULL,
	[YEAR_GRADUATED] [int] NULL,
	[REMARKS] [varchar](1000) NULL,
	[ROW_STATUS] [int] NULL,
	[CLOSED_USER] [varchar](14) NULL,
	[CLOSED_DATE] [datetime] NULL,
	[CLOSED_TIME] [int] NULL,
	[CLOSED_TERM] [varchar](10) NULL,
	[CLOSED_WINDOW] [varchar](8) NULL,
	[CRUSER] [varchar](14) NULL,
	[CRDATEI] [datetime] NULL,
	[CRTIMEI] [int] NULL,
	[CRTERM] [varchar](10) NULL,
	[CRWINDOW] [varchar](8) NULL,
	[LAST_MOD_USER] [varchar](14) NULL,
	[LAST_MOD_DATEI] [datetime] NULL,
	[LAST_MOD_TIMEI] [int] NULL,
	[LAST_MOD_TERM] [varchar](10) NULL,
	[LAST_MOD_WINDOW] [varchar](8) NULL,
	[VERS] [int] NULL,
	[STATUS] [varchar](2) NULL,
	[SOURCE_TYPE] [varchar](2) NULL,
	[SOURCE_ID] [varchar](20) NULL,
	[QUAL_EXPIRY_DATEI] [datetime] NULL,
	[QUAL_TARGET_DATEI] [datetime] NULL,
	[INST_COMPANY_CODE] [int] NULL,
	[EMPLQUAL_SEQ_NO] [int] NOT NULL,
	[SUPERSEDED_IND] [varchar](1) NULL,
	[EMPLQUAL_STATUS] [varchar](1) NULL,
	[EMPLQUAL_CANCEL_STATUS] [varchar](1) NULL,
	[CANCEL_SOURCE_TYPE] [varchar](2) NULL,
	[WRKFLW_SYSTEM] [varchar](10) NULL,
	[WRKFLW_NAME] [varchar](15) NULL,
	[CANCEL_WRKFLW_SYSTEM] [varchar](10) NULL,
	[CANCEL_WRKFLW_NAME] [varchar](15) NULL,
	[ORIGINAL_ID_NUMBER] [int] NULL,
	[VERIFIED_IND] [varchar](1) NULL,
	[VERIFIED_DATE] [datetime] NULL,
 CONSTRAINT [HRFHQD_IDX1] PRIMARY KEY CLUSTERED 
(
	[ID_NUMBER] ASC,
	[QUAL_CODE] ASC,
	[EMPLQUAL_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO