CREATE TABLE extract.[GLF_LDG_ACC_TRANS](
	[VERS] [int] NULL,
	[LDG_NAME] [varchar](8) NOT NULL,
	[ACCNBRI] [varchar](32) NOT NULL,
	[PERIOD] [smallint] NOT NULL,
	[SEQNBR] [int] NOT NULL,
	[PDATEI] [datetime] NULL,
	[DELIMIT1] [varchar](1) NULL,
	[PTIMEI] [int] NULL,
	[DELIMIT2] [varchar](1) NULL,
	[JNL_LNE] [int] NULL,
	[DOC_TYPE] [varchar](10) NULL,
	[DOC_DATEI1] [datetime] NULL,
	[DOC_DATEI2] [datetime] NULL,
	[DOC_REF1] [varchar](30) NULL,
	[DOC_REF2] [varchar](30) NULL,
	[SOURCE] [varchar](2) NULL,
	[UNITS1] [decimal](18, 6) NULL,
	[UNITS2] [decimal](18, 6) NULL,
	[RATE_TYPE] [varchar](4) NULL,
	[RATE_CODE] [varchar](4) NULL,
	[RATE_AMT] [decimal](18, 6) NULL,
	[AMT1] [decimal](14, 2) NULL,
	[AMT2] [decimal](14, 2) NULL,
	[NARR1] [varchar](40) NULL,
	[NARR2] [varchar](40) NULL,
	[NARR3] [varchar](40) NULL,
	[BAT_NAME] [varchar](8) NULL,
	[BAT_CRDATEI] [datetime] NULL,
	[BAT_CRTIMEI] [int] NULL,
	[DOC_XREF] [varchar](26) NULL,
	[ORIG_LDG_NAME] [varchar](8) NULL,
	[DOC_REF3] [varchar](10) NULL,
	[TRANS_NBR] [decimal](15, 0) NULL,
	[ALLOC_AMT1] [decimal](14, 2) NULL,
	[ALLOC_AMT2] [decimal](14, 2) NULL,
	[OS_AMT1] [decimal](14, 2) NULL,
	[OS_AMT2] [decimal](14, 2) NULL,
	[MDSE_AMT] [decimal](14, 2) NULL,
	[DISCN_AMT1] [decimal](14, 2) NULL,
	[DISCN_AMT2] [decimal](14, 2) NULL,
	[DISCN_DATEI] [datetime] NULL,
	[RETN_AMT] [decimal](14, 2) NULL,
	[RETN_REAS1] [varchar](40) NULL,
	[RETN_REAS2] [varchar](40) NULL,
	[RETN_DATEI] [datetime] NULL,
	[STATUS] [varchar](2) NULL,
	[PRESP_STAT] [varchar](2) NULL,
	[STMT_AGING_CODE] [varchar](2) NULL,
	[DUE_DATEI] [datetime] NULL,
	[STMT_NBR] [decimal](15, 0) NULL,
	[CASHBOOK_IND] [varchar](1) NULL,
	[USER_FLD1] [varchar](40) NULL,
	[USER_FLD2] [varchar](40) NULL,
	[USER_FLD3] [varchar](40) NULL,
	[USER_FLD4] [varchar](40) NULL,
	[USER_FLD5] [varchar](40) NULL,
	[USER_FLD6] [varchar](40) NULL,
	[USER_FLD7] [varchar](40) NULL,
	[USER_FLD8] [varchar](40) NULL,
	[USER_FLD9] [varchar](40) NULL,
	[USER_FLD10] [varchar](40) NULL,
	[PLOCN_CODE] [varchar](4) NULL,
	[PURCHASE_TYPE] [varchar](1) NULL,
	[PORDNBR] [varchar](10) NULL,
	[BKORDNBR] [smallint] NULL,
	[PORDLINEID] [varchar](14) NULL,
	[CASHFLOW_UPDATE] [varchar](2) NULL,
	[CASHFLOW_PRDATEI] [datetime] NULL,
	[DOC_DATEI3] [datetime] NULL,
	[DOC_DATEI4] [datetime] NULL,
	[DOC_REF4] [varchar](10) NULL,
	[UNITS3] [decimal](18, 6) NULL,
	[UNITS4] [decimal](18, 6) NULL,
	[AMT3] [decimal](14, 2) NULL,
	[AMT4] [decimal](14, 2) NULL,
	[FUND_NBR] [smallint] NULL,
	[FUND_TRANS_CLASS] [varchar](1) NULL,
	[FUND_ACCNBRI] [varchar](32) NULL,
	[DOC_REG_NAME] [varchar](8) NULL,
	[DOC_REG_UNIQUE_NBR] [int] NULL,
	[DISS_LDG_CODE] [varchar](2) NULL,
	[DISS_ACCNBRI] [varchar](32) NULL,
	[PROC1_DATEI] [datetime] NULL,
	[PROC2_DATEI] [datetime] NULL,
	[PROC3_DATEI] [datetime] NULL,
	[PROC1_TIMEI] [int] NULL,
	[PROC2_TIMEI] [int] NULL,
	[PROC3_TIMEI] [int] NULL,
	[PROC1_CODE] [varchar](10) NULL,
	[PROC2_CODE] [varchar](10) NULL,
	[PROC3_CODE] [varchar](10) NULL,
	[BAT_CRID] [varchar](3) NULL,
	[BAT_CRUSER] [varchar](14) NULL,
	[BAT_CRTERM] [varchar](10) NULL,
	[SOURCE_ID] [varchar](3) NULL,
	[SOURCE_DATEI] [datetime] NULL,
	[SOURCE_TIMEI] [int] NULL,
	[SOURCE_USER] [varchar](14) NULL,
	[SOURCE_TERM] [varchar](10) NULL,
	[POST_ID] [varchar](3) NULL,
	[POST_USER] [varchar](14) NULL,
	[POST_TERM] [varchar](10) NULL,
	[MODIFY_ID] [varchar](3) NULL,
	[MODIFY_DATEI] [datetime] NULL,
	[MODIFY_TIMEI] [int] NULL,
	[MODIFY_USER] [varchar](14) NULL,
	[MODIFY_TERM] [varchar](10) NULL,
	[SEP_CHEQUE] [varchar](1) NULL,
	[COLL_COMMENT] [varchar](40) NULL,
	[ENTY_CODE] [varchar](32) NULL,
	[INT_HOLD_AREA] [varchar](8) NULL,
	[INT_HOLD_ITEM] [varchar](6) NULL,
	[INT_HOLD_ITEM_WP] [varchar](6) NULL,
	[EXT_HOLD_AREA] [varchar](8) NULL,
	[EXT_HOLD_ITEM] [varchar](6) NULL,
	[ENTY_TYPE] [varchar](1) NULL,
	[DOC_REG2_NAME] [varchar](8) NULL,
	[DOC_REG2_UNQ_NBR] [int] NULL,
	[CMPL_PRT_STMT_IND] [varchar](1) NULL,
	[DISS_SEQ_NBR] [int] NULL,
	[CCY_CODE] [varchar](4) NULL,
	[EXCH_RATE_TABLE_NAME] [varchar](10) NULL,
	[EXCH_RATE_DATEI] [datetime] NULL,
	[EXCH_RATE_ORIDE_IND] [varchar](1) NULL,
	[EXCH_RATE_AMT] [decimal](18, 6) NULL,
	[CCY_AMT] [decimal](14, 2) NULL,
	[OS_CCY_AMT] [decimal](14, 2) NULL,
	[DISCN_CCY_AMT] [decimal](14, 2) NULL,
	[RETN_CCY_AMT] [decimal](14, 2) NULL,
	[MDSE_CCY_AMT] [decimal](14, 2) NULL,
	[ALLOC_CCY_AMT] [decimal](14, 2) NULL,
	[ORIG_CCY_CODE] [varchar](4) NULL,
	[ORIG_EXCH_RATE_AMT] [decimal](18, 6) NULL,
	[ORIG_CCY_AMT] [decimal](14, 2) NULL,
	[ORIG_DISCN_CCY_AMT] [decimal](14, 2) NULL,
	[ORIG_RETN_CCY_AMT] [decimal](14, 2) NULL,
	[ORIG_MDSE_CCY_AMT] [decimal](14, 2) NULL,
	[SINGLE_EXCH_RATE_TBL_NM] [varchar](10) NULL,
	[SINGLE_EXCH_RATE_AMT] [decimal](18, 6) NULL,
	[STATUS_DATEI] [datetime] NULL,
	[LDG_TRANS_RID] [int] NOT NULL,
	[PAY_ACCT_ID] [varchar](3) NULL,
	[TRANS_SELN_CODE] [varchar](8) NULL,
	[DOC_UNIQUE_ID] [varchar](32) NULL,
	[ATTACH_IND] [varchar](1) NULL,
	[DISS_INV_AMT1] [decimal](14, 2) NULL,
	[DISS_VAT_EXC_INV_AMT] [decimal](14, 2) NULL,
	[DISS_VAT_INV_AMT] [decimal](14, 2) NULL,
	[DISS_INV_CCY_AMT] [decimal](14, 2) NULL,
	[DISS_VAT_EXC_INV_CCY_AMT] [decimal](14, 2) NULL,
	[DISS_VAT_INV_CCY_AMT] [decimal](14, 2) NULL,
	[DISS_INVM_BASE_ADJ_AMT1] [decimal](14, 2) NULL,
	[EXC_TAX_AMT] [decimal](14, 2) NULL,
	[CTRCT_IND] [varchar](1) NULL,
	[CTRCT_PROF_NAME] [varchar](10) NULL,
	[CTRCT_NBRI] [varchar](32) NULL,
	[CTRCT_SHD_NBR] [int] NULL,
	[CTRCT_SHD_ITEM_SEQNBR] [int] NULL,
	[CTRCT_SHD_ITEM_VARN_NBR] [int] NULL,
	[ON_HOLD_STATUS] [varchar](1) NULL,
	[ON_HOLD_NOTE_NBR] [varchar](14) NULL,
	[ON_HOLD_REASON_CODE] [varchar](8) NULL,
	[ORIG_PGRP_NAME] [varchar](8) NULL,
	[CTRCT_PARTY_PROF_NAME] [varchar](10) NULL,
	[CTRCT_PARTY_NBR] [varchar](32) NULL,
	[CTRCT_CLAIM_NBR] [int] NULL,
	[CONTAINS_CTRCT_IND] [varchar](1) NULL,
	[PUR_VERS_OPT] [varchar](4) NULL,
	[PUR_ORD_NBR] [varchar](30) NULL,
	[PUR_ORD_LINE_NBR] [int] NULL,
	[PUR_ORD_DISS_SEQ_NBR] [int] NULL,
	[PUR_RCPT_NBR] [varchar](30) NULL,
	[PUR_RCPT_LINE_NBR] [int] NULL,
	[PUR_RCPT_DISS_SEQ_NBR] [int] NULL,
	[PUR_INVC_NBR] [varchar](30) NULL,
	[PUR_INVC_LINE_NBR] [int] NULL,
	[PUR_INVC_DISS_SEQ_NBR] [int] NULL,
	[LAST_ON_HOLD_START_DATE] [datetime] NULL,
	[ACCUM_ON_HOLD_DAYS] [int] NULL,
 CONSTRAINT [GLFLAT_IDX1] PRIMARY KEY CLUSTERED 
(
	[LDG_NAME] ASC,
	[ACCNBRI] ASC,
	[PERIOD] ASC,
	[SEQNBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO