-- creating table 'hrpay_leave_ctl'
create table [extract].[hrpay_leave_ctl] (
    [leave_ctl_type] varchar(10)  not null,
    [id_number] int  not null,
    [leave_start_date] datetime  not null,
    [leave_end_date] datetime  null,
    [pay_component_ref] decimal(10,4)  null,
    [pay_period_date] datetime  null,
    [company_code] int  null,
    [doc_type_code] varchar(10)  null,
    [tmc_seq_number] int  null,
    [number_of_weeks] decimal(10,4)  null,
    [id_number_apprvng] int  null,
    [leave_descr] varchar(50)  null,
    [orig_auth_code] varchar(8)  null,
    [last_auth_code] varchar(8)  null,
    [refer_auth_code] varchar(8)  null,
    [last_auth_seqnbr] int  null,
    [auth_status] varchar(1)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [leave_status] varchar(2)  null,
    [leave_sub_status] varchar(2)  null,
    [ldg_code] varchar(2)  null,
    [accnbri] varchar(32)  null,
    [position_code] varchar(10)  null,
    [reference_nbr] varchar(40)  null,
    [leave_status_user_id] varchar(14)  null,
    [leave_status_comment] varchar(255)  null,
    [leave_seq_nbr] smallint  not null,
    [reversing_leave_seq_nbr] smallint  null
);
go