CREATE TABLE extract.[GLF_CHART_ACC_USF](
	[VERS] [smallint] NULL,
	[CHART_NAME] [varchar](8) NOT NULL,
	[ACCNBRI] [varchar](32) NOT NULL,
	[USER_FLD1] [varchar](40) NULL,
	[USER_NUM1] [decimal](18, 6) NULL,
	[USER_DATEI1] [datetime] NULL,
	[USER_FLD2] [varchar](40) NULL,
	[USER_NUM2] [decimal](18, 6) NULL,
	[USER_DATEI2] [datetime] NULL,
	[USER_FLD3] [varchar](40) NULL,
	[USER_NUM3] [decimal](18, 6) NULL,
	[USER_DATEI3] [datetime] NULL,
	[USER_FLD4] [varchar](40) NULL,
	[USER_NUM4] [decimal](18, 6) NULL,
	[USER_DATEI4] [datetime] NULL,
	[USER_FLD5] [varchar](40) NULL,
	[USER_NUM5] [decimal](18, 6) NULL,
	[USER_DATEI5] [datetime] NULL,
	[USER_FLD6] [varchar](40) NULL,
	[USER_NUM6] [decimal](18, 6) NULL,
	[USER_DATEI6] [datetime] NULL,
	[USER_FLD7] [varchar](40) NULL,
	[USER_NUM7] [decimal](18, 6) NULL,
	[USER_DATEI7] [datetime] NULL,
	[USER_FLD8] [varchar](40) NULL,
	[USER_NUM8] [decimal](18, 6) NULL,
	[USER_DATEI8] [datetime] NULL,
	[USER_FLD9] [varchar](40) NULL,
	[USER_NUM9] [decimal](18, 6) NULL,
	[USER_DATEI9] [datetime] NULL,
	[USER_FLD10] [varchar](40) NULL,
	[USER_NUM10] [decimal](18, 6) NULL,
	[USER_DATEI10] [datetime] NULL,
	[USER_FLD11] [varchar](40) NULL,
	[USER_NUM11] [decimal](18, 6) NULL,
	[USER_DATEI11] [datetime] NULL,
	[USER_FLD12] [varchar](40) NULL,
	[USER_NUM12] [decimal](18, 6) NULL,
	[USER_DATEI12] [datetime] NULL,
	[ADDR_COUNTRY_NAME] [varchar](40) NULL,
	[ADDR_COUNTRY_CODE] [varchar](10) NULL,
 CONSTRAINT [GLFCAU_IDX1] PRIMARY KEY CLUSTERED 
(
	[CHART_NAME] ASC,
	[ACCNBRI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO