-- creating table 'hrpay_payitems_dtl'
create table [extract].[hrpay_payitems_dtl] (
    [document_type] varchar(10)  not null,
    [company_code] int  not null,
    [pay_document_no] int  not null,
    [pay_component_def1] varchar(10)  null,
    [pay_component_ref1] varchar(10)  null,
    [sequence_no] int  not null,
    [module_id] varchar(10)  null,
    [number_units] decimal(10,4)  null,
    [pay_period_unit] varchar(10)  null,
    [pay_item_rate] decimal(18,6)  null,
    [pay_item_amount] decimal(18,6)  null,
    [taxable] varchar(1)  null,
    [payment] varchar(1)  null,
    [calbydaysworked] varchar(1)  null,
    [accts_payable_ref] varchar(10)  null,
    [account_mumber] varchar(20)  null,
    [bonus_code] varchar(10)  null,
    [pay_calc_date] datetime  null,
    [pay_item_expl] varchar(40)  null,
    [transaction_date] datetime  null,
    [trans_accnt_no] varchar(20)  null,
    [row_status] int  null,
    [closed_user] varchar(14)  null,
    [closed_date] datetime  null,
    [closed_time] int  null,
    [closed_term] varchar(10)  null,
    [closed_window] varchar(8)  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null,
    [accrual_date] datetime  null,
    [accrual_date_prev] datetime  null,
    [accrual_amt_prev] decimal(14,4)  null,
    [pay_component_def] int  null,
    [pay_component_ref] decimal(10,4)  not null,
    [no_accruals_prev] int  null,
    [no_accruals] int  null,
    [pay_item_type] varchar(10)  null,
    [disb_code] varchar(10)  null,
    [ldg_code] varchar(2)  null,
    [accnbri] varchar(32)  null,
    [clr_ldg_code] varchar(2)  null,
    [clr_accnbri] varchar(32)  null,
    [disbursed_ind] varchar(1)  null,
    [id_number] int  null,
    [pay_period_enddate] datetime  null,
    [pay_period_type] varchar(10)  null,
    [posted_ind] varchar(1)  null,
    [pgrp_name] varchar(8)  null,
    [period] smallint  null,
    [ldg_name] varchar(8)  null,
    [trans_nbr] decimal(15,0)  null,
    [clr_ldg_name] varchar(8)  null,
    [clr_trans_nbr] decimal(15,0)  null,
    [empl_cond_award] varchar(10)  null,
    [empl_cond_grade] varchar(10)  null,
    [empl_cond_level] varchar(10)  null,
    [posting_ind] varchar(1)  null,
    [empl_debtor_ind] varchar(1)  null,
    [calc_type] varchar(1)  null,
    [techone_fld1] varchar(40)  null,
    [techone_fld2] varchar(40)  null,
    [techone_fld3] varchar(40)  null,
    [techone_fld4] varchar(40)  null,
    [position_code] varchar(10)  null,
    [item_start_datei] datetime  null,
    [item_end_datei] datetime  null,
    [worked_pay_period_enddate] datetime  null,
    [impact_status] varchar(10)  null,
    [fund_nbr] smallint  null,
    [fund_trans_class] varchar(1)  null,
    [fund_ldg_name] varchar(8)  null,
    [fund_accnbri] varchar(32)  null,
    [funds_ctl_ind] varchar(2)  null,
    [funds_ctl_ind_clr] varchar(2)  null,
    [fund_nbr_clr] smallint  null,
    [fund_trns_clss_clr] varchar(1)  null,
    [fund_ldg_name_clr] varchar(8)  null,
    [fund_accnbri_clr] varchar(32)  null,
    [reference_nbr] varchar(50)  null
);
go