-- creating table 'hrpay_payitems_summaccr'
create table [extract].[hrpay_payitems_summaccr] (
    [employee_id] int  not null,
    [accrual_date] datetime  not null,
    [pay_component_ref] decimal(18,6)  not null,
    [period_accrual] decimal(18,6)  null,
    [period_taken] decimal(18,6)  null,
    [unit_type] varchar(10)  null,
    [open_entitlement] decimal(18,6)  null,
    [open_pro_rata] decimal(18,6)  null,
    [open_taken] decimal(18,6)  null,
    [open_balance] decimal(18,6)  null,
    [close_entitlement] decimal(18,6)  null,
    [close_pro_rata] decimal(18,6)  null,
    [close_taken] decimal(18,6)  null,
    [close_balance] decimal(18,6)  null,
    [prev_entitlement] decimal(18,6)  null,
    [prev_pro_rata] decimal(18,6)  null,
    [prev_taken] decimal(18,6)  null,
    [prev_balance] decimal(18,6)  null,
    [accrual_group] varchar(20)  null,
    [last_accrual_date] datetime  null,
    [cruser] varchar(14)  null,
    [crdatei] datetime  null,
    [crtimei] int  null,
    [crterm] varchar(10)  null,
    [crwindow] varchar(8)  null,
    [last_mod_user] varchar(14)  null,
    [last_mod_datei] datetime  null,
    [last_mod_timei] int  null,
    [last_mod_term] varchar(10)  null,
    [last_mod_window] varchar(8)  null,
    [vers] int  null
);
go