SELECT TOP 1000 t1.[COMPANY_CODE]
      ,t1.[HIERARCHY_TYPE]
      ,t1.[HIERARCHY_CODE]
      ,t1.[PARENT_TYPE]
      ,t1.[PARENT_NODE]
      ,t1.[TREE_INDEX]
      ,t1.[PARENT_INDEX]
      ,t1.[CURRENT_LEVEL]
      ,t2.HIERARCHY_DESCR
  FROM [DWHB].[extract].[HRSYS_HIERARCH_ITM] t1
  ,extract.HRSYS_HIERARCH_CTL t2
  where t1.HIERARCHY_CODE = 10050
  and t1.HIERARCHY_CODE = t2.HIERARCHY_CODE