//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident_fact
    {
        public int incident_key { get; set; }
        public int portfolio_key { get; set; }
        public int service_stream_key { get; set; }
        public int program_key { get; set; }
        public int incident_date_key { get; set; }
        public int location_key { get; set; }
    
        public virtual portfolio_dim portfolio_dim { get; set; }
        public virtual service_strean_dim service_strean_dim { get; set; }
        public virtual program_dim program_dim { get; set; }
        public virtual date_dim date_dim { get; set; }
        public virtual location_dim location_dim { get; set; }
    }
}
