//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhf.riskman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dwhfriskman : DbContext
    {
        public dwhfriskman()
            : base("name=dwhfriskman")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<incident_fact> incident_fact { get; set; }
        public virtual DbSet<portfolio_dim> portfolio_dim { get; set; }
        public virtual DbSet<service_strean_dim> service_strean_dim { get; set; }
        public virtual DbSet<program_dim> program_dim { get; set; }
        public virtual DbSet<date_dim> date_dim { get; set; }
        public virtual DbSet<location_dim> location_dim { get; set; }
    }
}
