CREATE TABLE [extract].[GLF_CHART_ACC_USF](
	[VERS] [smallint] NULL,
	[CHART_NAME] [varchar](8) NOT NULL,
	[ACCNBRI] [varchar](32) NOT NULL,
	[USER_FLD1] [varchar](40) NULL,
	[USER_NUM1] [numeric](18, 6) NULL,
	[USER_DATEI1] [datetime] NULL,
	[USER_FLD2] [varchar](40) NULL,
	[USER_NUM2] [numeric](18, 6) NULL,
	[USER_DATEI2] [datetime] NULL,
	[USER_FLD3] [varchar](40) NULL,
	[USER_NUM3] [numeric](18, 6) NULL,
	[USER_DATEI3] [datetime] NULL,
	[USER_FLD4] [varchar](40) NULL,
	[USER_NUM4] [numeric](18, 6) NULL,
	[USER_DATEI4] [datetime] NULL,
	[USER_FLD5] [varchar](40) NULL,
	[USER_NUM5] [numeric](18, 6) NULL,
	[USER_DATEI5] [datetime] NULL,
	[USER_FLD6] [varchar](40) NULL,
	[USER_NUM6] [numeric](18, 6) NULL,
	[USER_DATEI6] [datetime] NULL,
	[USER_FLD7] [varchar](40) NULL,
	[USER_NUM7] [numeric](18, 6) NULL,
	[USER_DATEI7] [datetime] NULL,
	[USER_FLD8] [varchar](40) NULL,
	[USER_NUM8] [numeric](18, 6) NULL,
	[USER_DATEI8] [datetime] NULL,
	[USER_FLD9] [varchar](40) NULL,
	[USER_NUM9] [numeric](18, 6) NULL,
	[USER_DATEI9] [datetime] NULL,
	[USER_FLD10] [varchar](40) NULL,
	[USER_NUM10] [numeric](18, 6) NULL,
	[USER_DATEI10] [datetime] NULL,
	[USER_FLD11] [varchar](40) NULL,
	[USER_NUM11] [numeric](18, 6) NULL,
	[USER_DATEI11] [datetime] NULL,
	[USER_FLD12] [varchar](40) NULL,
	[USER_NUM12] [numeric](18, 6) NULL,
	[USER_DATEI12] [datetime] NULL,
	[ADDR_COUNTRY_NAME] [varchar](40) NULL,
	[ADDR_COUNTRY_CODE] [varchar](10) NULL
) ON [PRIMARY]

GO


