//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_comcare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conform_comcare_physicalContainer : DbContext
    {
        public conform_comcare_physicalContainer()
            : base("name=conform_comcare_physicalContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer_dim> customer_dim { get; set; }
        public virtual DbSet<customer_transactions_fact> customer_transactions_fact { get; set; }
        public virtual DbSet<date_dim> date_dim { get; set; }
        public virtual DbSet<program_dim> program_dim { get; set; }
        public virtual DbSet<transaction_type_dim> transaction_type_dim { get; set; }
        public virtual DbSet<responsible_party_dim> responsible_party_dim { get; set; }
    }
}
