//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.conform_comcare
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_type_dim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaction_type_dim()
        {
            this.customer_transactions_fact = new HashSet<customer_transactions_fact>();
        }
    
        public int transaction_type_key { get; set; }
        public Nullable<int> transaction_type_natural_key { get; set; }
        public string transaction_type_description { get; set; }
        public string transaction_source { get; set; }
        public Nullable<System.DateTime> effective_from_date { get; set; }
        public Nullable<System.DateTime> effective_to_date { get; set; }
        public string category_code { get; set; }
        public string change_reason_code { get; set; }
        public string change_reason_description { get; set; }
        public Nullable<System.DateTime> row_effective_date { get; set; }
        public Nullable<System.DateTime> row_expiration_date { get; set; }
        public string current_row_indicator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_transactions_fact> customer_transactions_fact { get; set; }
    }
}
