//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class extract_t1_conceptualContainer : DbContext
    {
        public extract_t1_conceptualContainer()
            : base("name=extract_t1_conceptualContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<F1_USER_PROFILE> F1_USER_PROFILE { get; set; }
        public virtual DbSet<F1TIM_FMT_LNE> F1TIM_FMT_LNE { get; set; }
        public virtual DbSet<GLF_CHART_ACC_USF> GLF_CHART_ACC_USF { get; set; }
        public virtual DbSet<GLF_CHART_ACCT> GLF_CHART_ACCT { get; set; }
        public virtual DbSet<GLF_LDG_ACC_TRANS> GLF_LDG_ACC_TRANS { get; set; }
        public virtual DbSet<GLF_LDG_ACCT_DESC1> GLF_LDG_ACCT_DESC1 { get; set; }
        public virtual DbSet<GLF_SELN_CODE> GLF_SELN_CODE { get; set; }
        public virtual DbSet<HRCOM_ADDRESS_REF> HRCOM_ADDRESS_REF { get; set; }
        public virtual DbSet<HREEN_EMPL_ENT_CTL> HREEN_EMPL_ENT_CTL { get; set; }
        public virtual DbSet<HREEN_EMPL_ENT_DTL> HREEN_EMPL_ENT_DTL { get; set; }
        public virtual DbSet<HREEN_EMPLENT_ACCR> HREEN_EMPLENT_ACCR { get; set; }
        public virtual DbSet<HRHMN_EMPLCONT_DTL> HRHMN_EMPLCONT_DTL { get; set; }
        public virtual DbSet<HRHMN_EMPLISS_DTL> HRHMN_EMPLISS_DTL { get; set; }
        public virtual DbSet<HRHMN_USR_FLD> HRHMN_USR_FLD { get; set; }
        public virtual DbSet<hrpcm_paycomp_def> hrpcm_paycomp_def { get; set; }
        public virtual DbSet<hrpcm_paycomp_ref> hrpcm_paycomp_ref { get; set; }
        public virtual DbSet<HRRST_ROSTER_DTL> HRRST_ROSTER_DTL { get; set; }
        public virtual DbSet<HRRST_ROSTER_REF> HRRST_ROSTER_REF { get; set; }
        public virtual DbSet<hrstc_code> hrstc_code { get; set; }
        public virtual DbSet<hrsys_hiereff_mst> hrsys_hiereff_mst { get; set; }
        public virtual DbSet<hrsys_usrseln_dtl> hrsys_usrseln_dtl { get; set; }
        public virtual DbSet<HRTIM_TSHEET_ENTRY> HRTIM_TSHEET_ENTRY { get; set; }
        public virtual DbSet<HRHMN_EMPL_JOB_CTL> HRHMN_EMPL_JOB_CTL { get; set; }
        public virtual DbSet<HRHMN_EMPL_JOB_POS> HRHMN_EMPL_JOB_POS { get; set; }
        public virtual DbSet<HRHMN_EMPL_REF> HRHMN_EMPL_REF { get; set; }
        public virtual DbSet<HRHMN_EMPLQUAL_DTL> HRHMN_EMPLQUAL_DTL { get; set; }
        public virtual DbSet<HRHMN_EMPLTERM_DTL> HRHMN_EMPLTERM_DTL { get; set; }
        public virtual DbSet<HRHMN_QUAL_REF> HRHMN_QUAL_REF { get; set; }
        public virtual DbSet<HRLVE_LEAVE_CTL> HRLVE_LEAVE_CTL { get; set; }
        public virtual DbSet<HRPAY_LEAVE_CTL> HRPAY_LEAVE_CTL { get; set; }
        public virtual DbSet<HRPAY_LEAVE_DTL> HRPAY_LEAVE_DTL { get; set; }
        public virtual DbSet<HRPAY_LVE_TKN_DTL> HRPAY_LVE_TKN_DTL { get; set; }
        public virtual DbSet<HRPAY_MASTER_CTL> HRPAY_MASTER_CTL { get; set; }
        public virtual DbSet<HRPAY_PAYITEMS_DTL> HRPAY_PAYITEMS_DTL { get; set; }
        public virtual DbSet<HRPAY_PAYITEMS_SUMMACCR> HRPAY_PAYITEMS_SUMMACCR { get; set; }
        public virtual DbSet<HRPAY_PAYITEMS_SUMMPMNT> HRPAY_PAYITEMS_SUMMPMNT { get; set; }
        public virtual DbSet<HRSYS_HIERARCH_CTL> HRSYS_HIERARCH_CTL { get; set; }
        public virtual DbSet<HRSYS_HIERARCH_ITM> HRSYS_HIERARCH_ITM { get; set; }
        public virtual DbSet<HRSYS_HIERARCH_LVL> HRSYS_HIERARCH_LVL { get; set; }
    }
}
