//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class F1_USER_PROFILE
    {
        public string USER_ID { get; set; }
        public string OVERRIDE_USER_ID { get; set; }
        public string ACCOUNT_DISABLED { get; set; }
        public Nullable<int> INVALID_ATTEMPTS { get; set; }
        public Nullable<System.DateTime> LOGIN_ATMPT_DATEI { get; set; }
        public Nullable<int> LOGIN_ATMPT_TIMEI { get; set; }
        public string CUR_AP_LEDG { get; set; }
        public string CUR_AR_LEDG { get; set; }
        public string CUR_GL_LEDG { get; set; }
        public string CUR_AP_CHART { get; set; }
        public string CUR_AR_CHART { get; set; }
        public string CUR_GL_CHART { get; set; }
        public Nullable<short> PL_CLOSE_STATE { get; set; }
        public Nullable<short> OS_CLOSE_STATE { get; set; }
        public Nullable<short> ADVANCE_ON_SAVE { get; set; }
        public Nullable<short> MINIMISE { get; set; }
        public Nullable<short> MAXIMISE { get; set; }
        public Nullable<short> LOADSTATE { get; set; }
        public Nullable<short> TOOLBAR { get; set; }
        public Nullable<short> MENUSTYLE { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<short> PASSWD_MIN_LENGTH { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public Nullable<short> PASSWD_DURATION { get; set; }
        public string START_MENU { get; set; }
        public string USER_NAME { get; set; }
        public string FST_NAME { get; set; }
        public string LST_NAME { get; set; }
        public string TITLE { get; set; }
        public string NARR1 { get; set; }
        public string NARR2 { get; set; }
        public string NARR3 { get; set; }
        public string DEPT { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<System.DateTime> PASSWD_CHANGED { get; set; }
        public Nullable<short> CASCADE_FORMS { get; set; }
        public Nullable<short> DISPLAYMENUS { get; set; }
        public Nullable<short> DISPLAYPROGRAMS { get; set; }
        public string DB_SYS_USER_ID { get; set; }
        public string DB_SYS_PASSWD { get; set; }
        public string DB_USER_ID { get; set; }
        public string DB_PASSWD { get; set; }
        public Nullable<short> COMMONSENSE { get; set; }
        public Nullable<short> POSITION { get; set; }
        public Nullable<short> ORIENTATION { get; set; }
        public string CUR_PLOCN_CODE { get; set; }
        public string SECURITY_ACCESS { get; set; }
        public Nullable<short> DIRCDVERS { get; set; }
        public string DIRCD { get; set; }
        public string SUPERUSER { get; set; }
        public Nullable<short> FORMSTATE { get; set; }
        public string RESIZE { get; set; }
        public string DBLCLICK { get; set; }
        public string SMALL_FONTS { get; set; }
        public Nullable<decimal> FONT_SIZE { get; set; }
        public string CHK_ALLOW_BUILD { get; set; }
        public string CHK_EXT_CRIT_SMALL { get; set; }
        public string CHK_EXT_CRIT_LARGE { get; set; }
        public string VIEW_BTNBAR_IND { get; set; }
        public string VIEW_OBJBAR_IND { get; set; }
        public string CACHE_EXES { get; set; }
        public string CACHE_MENUS { get; set; }
        public string EMAIL_ADDR_NAME { get; set; }
        public string WEB_MENU { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public string TECHONE_FLD5 { get; set; }
        public string TECHONE_FLD6 { get; set; }
        public string USER_FLD1 { get; set; }
        public string USER_FLD2 { get; set; }
        public string USER_FLD3 { get; set; }
        public string USER_FLD4 { get; set; }
        public string USER_FLD5 { get; set; }
        public string CS_ACCESS_CTRL { get; set; }
        public string EBUS_ACCESS_CTRL { get; set; }
        public string EBUS_PRIMARY_ROLE { get; set; }
        public string WRKGRP_NAME { get; set; }
        public string SUPERVISOR_USER_ID { get; set; }
        public string HR_INTEGRATION_IND { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string ACCESS_METHOD_CODE { get; set; }
        public string CURR_PROFILE_NAME { get; set; }
        public Nullable<System.DateTime> COMMENCEMENT_DATEI { get; set; }
        public Nullable<System.DateTime> TERMINATION_DATEI { get; set; }
        public string TERMINATION_REASON { get; set; }
        public string REPORTS_TO_PROFILE { get; set; }
        public string USER_TYPE { get; set; }
        public string USER_STATUS { get; set; }
        public string SYNC_KEY { get; set; }
        public string USER_ACCESS_CODE { get; set; }
        public string CLAIMED_ID { get; set; }
        public string FEDERATED_EMAIL_ADDR { get; set; }
        public string PERSONAL_EMAIL_ADDR { get; set; }
        public string PREF_NAME { get; set; }
        public string STATUS_COMMENT { get; set; }
        public string JOB_TITLE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string SELF_REG_VERIFIED { get; set; }
        public string POSITION_SEC_IND { get; set; }
        public string FORCE_PW_RESET { get; set; }
        public string PW_SALT { get; set; }
    }
}
