//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class F1TIM_FMT_LNE
    {
        public string TS_SYSTEM_NAME { get; set; }
        public string TS_FMT_NAME { get; set; }
        public short TS_LINE_ID { get; set; }
        public Nullable<short> TS_LINE_SEQ_NBR { get; set; }
        public Nullable<int> VERS { get; set; }
        public string TS_LINE_TITLE { get; set; }
        public string TS_LINE_TYPE { get; set; }
        public Nullable<decimal> PAY_COMPONENT_REF { get; set; }
        public string PAY_COMPONENT_IND { get; set; }
        public string EMP_CONDITION_IND { get; set; }
        public string DEF_LDG_CODE { get; set; }
        public string COSTING_TYPE { get; set; }
        public string ASSIGNED_TASK_IND { get; set; }
        public string BILLING_IND { get; set; }
        public string BUDGET_IND { get; set; }
        public string FORECAST_IND { get; set; }
        public string PLANT_ENTRY_IND { get; set; }
        public string LDG_CODE_IND { get; set; }
        public string ITEM_TYPE { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public string TECHONE_FLD5 { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public string SUPER_VISIBLE_IND { get; set; }
        public string EXCLUDE_TOTAL_IND { get; set; }
        public string ACCNBRI_IND { get; set; }
        public string LINE_DESCR_IND { get; set; }
        public string LINE_DESCR { get; set; }
        public string LINE_DESCR_CMP { get; set; }
        public string LINE_DESCR_CMP_TYP { get; set; }
        public string LDG_CODE_CAPTION { get; set; }
        public string PAY_COMP_CAPTION { get; set; }
        public string ROSTER_IND { get; set; }
        public string CLOCKIN_HRS_IND { get; set; }
        public string COST_RATE_IND { get; set; }
        public string COST_RATE_TYPE { get; set; }
        public string COST_RATE_CODE { get; set; }
        public string COMP_PREC_RULE { get; set; }
        public string OTH_ITEM_TYPE { get; set; }
        public string PROJ_MGR_IND { get; set; }
        public string PROJ_MGR_EDIT_IND { get; set; }
        public string ACCOUNT_MSK_ORDER { get; set; }
        public string ACCOUNT_MSKI { get; set; }
        public string SERVICE_RATE_SRC { get; set; }
        public string LINE_ITEM_TYPE { get; set; }
        public string SERVICE_RATE_TYPE { get; set; }
        public string SERVICE_RATE_CODE { get; set; }
        public string PLANT_MAP_OPTN { get; set; }
        public string ASSET_REG_NAME { get; set; }
        public string ENABLE_METER1_IND { get; set; }
        public string ENABLE_METER2_IND { get; set; }
        public string ENABLE_METER3_IND { get; set; }
        public string ENABLE_METER4_IND { get; set; }
    }
}
