//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLF_CHART_ACC_USF
    {
        public Nullable<short> VERS { get; set; }
        public string CHART_NAME { get; set; }
        public string ACCNBRI { get; set; }
        public string USER_FLD1 { get; set; }
        public Nullable<decimal> USER_NUM1 { get; set; }
        public Nullable<System.DateTime> USER_DATEI1 { get; set; }
        public string USER_FLD2 { get; set; }
        public Nullable<decimal> USER_NUM2 { get; set; }
        public Nullable<System.DateTime> USER_DATEI2 { get; set; }
        public string USER_FLD3 { get; set; }
        public Nullable<decimal> USER_NUM3 { get; set; }
        public Nullable<System.DateTime> USER_DATEI3 { get; set; }
        public string USER_FLD4 { get; set; }
        public Nullable<decimal> USER_NUM4 { get; set; }
        public Nullable<System.DateTime> USER_DATEI4 { get; set; }
        public string USER_FLD5 { get; set; }
        public Nullable<decimal> USER_NUM5 { get; set; }
        public Nullable<System.DateTime> USER_DATEI5 { get; set; }
        public string USER_FLD6 { get; set; }
        public Nullable<decimal> USER_NUM6 { get; set; }
        public Nullable<System.DateTime> USER_DATEI6 { get; set; }
        public string USER_FLD7 { get; set; }
        public Nullable<decimal> USER_NUM7 { get; set; }
        public Nullable<System.DateTime> USER_DATEI7 { get; set; }
        public string USER_FLD8 { get; set; }
        public Nullable<decimal> USER_NUM8 { get; set; }
        public Nullable<System.DateTime> USER_DATEI8 { get; set; }
        public string USER_FLD9 { get; set; }
        public Nullable<decimal> USER_NUM9 { get; set; }
        public Nullable<System.DateTime> USER_DATEI9 { get; set; }
        public string USER_FLD10 { get; set; }
        public Nullable<decimal> USER_NUM10 { get; set; }
        public Nullable<System.DateTime> USER_DATEI10 { get; set; }
        public string USER_FLD11 { get; set; }
        public Nullable<decimal> USER_NUM11 { get; set; }
        public Nullable<System.DateTime> USER_DATEI11 { get; set; }
        public string USER_FLD12 { get; set; }
        public Nullable<decimal> USER_NUM12 { get; set; }
        public Nullable<System.DateTime> USER_DATEI12 { get; set; }
        public string ADDR_COUNTRY_NAME { get; set; }
        public string ADDR_COUNTRY_CODE { get; set; }
    }
}
