//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLF_SELN_CODE
    {
        public Nullable<short> VERS { get; set; }
        public string SELN_TYPE { get; set; }
        public string SELN_CODE { get; set; }
        public string DESCR { get; set; }
        public string FDESCR { get; set; }
        public string NARR1 { get; set; }
        public string NARR2 { get; set; }
        public string NARR3 { get; set; }
        public string PAR_SELN_TYPE1 { get; set; }
        public string PAR_SELN_CODE1 { get; set; }
        public string PAR_SELN_TYPE2 { get; set; }
        public string PAR_SELN_CODE2 { get; set; }
        public string PAR_SELN_TYPE3 { get; set; }
        public string PAR_SELN_CODE3 { get; set; }
        public string PAR_SELN_TYPE4 { get; set; }
        public string PAR_SELN_CODE4 { get; set; }
        public string PAR_SELN_TYPE5 { get; set; }
        public string PAR_SELN_CODE5 { get; set; }
        public string PAR_SELN_TYPE6 { get; set; }
        public string PAR_SELN_CODE6 { get; set; }
        public string USER_FLD1 { get; set; }
        public Nullable<decimal> USER_NUM1 { get; set; }
        public Nullable<System.DateTime> USER_DATEI1 { get; set; }
        public string USER_FLD2 { get; set; }
        public Nullable<decimal> USER_NUM2 { get; set; }
        public Nullable<System.DateTime> USER_DATEI2 { get; set; }
        public string USER_FLD3 { get; set; }
        public Nullable<decimal> USER_NUM3 { get; set; }
        public Nullable<System.DateTime> USER_DATEI3 { get; set; }
        public string USER_FLD4 { get; set; }
        public Nullable<decimal> USER_NUM4 { get; set; }
        public Nullable<System.DateTime> USER_DATEI4 { get; set; }
        public string USER_FLD5 { get; set; }
        public Nullable<decimal> USER_NUM5 { get; set; }
        public Nullable<System.DateTime> USER_DATEI5 { get; set; }
        public string USER_FLD6 { get; set; }
        public Nullable<decimal> USER_NUM6 { get; set; }
        public Nullable<System.DateTime> USER_DATEI6 { get; set; }
        public string USER_FLD7 { get; set; }
        public Nullable<decimal> USER_NUM7 { get; set; }
        public Nullable<System.DateTime> USER_DATEI7 { get; set; }
        public string USER_FLD8 { get; set; }
        public Nullable<decimal> USER_NUM8 { get; set; }
        public Nullable<System.DateTime> USER_DATEI8 { get; set; }
        public string USER_FLD9 { get; set; }
        public Nullable<decimal> USER_NUM9 { get; set; }
        public Nullable<System.DateTime> USER_DATEI9 { get; set; }
        public string USER_FLD10 { get; set; }
        public Nullable<decimal> USER_NUM10 { get; set; }
        public Nullable<System.DateTime> USER_DATEI10 { get; set; }
        public string USER_FLD11 { get; set; }
        public Nullable<decimal> USER_NUM11 { get; set; }
        public Nullable<System.DateTime> USER_DATEI11 { get; set; }
        public string USER_FLD12 { get; set; }
        public Nullable<decimal> USER_NUM12 { get; set; }
        public Nullable<System.DateTime> USER_DATEI12 { get; set; }
        public string USER_FLD13 { get; set; }
        public Nullable<decimal> USER_NUM13 { get; set; }
        public Nullable<System.DateTime> USER_DATEI13 { get; set; }
        public string USER_FLD14 { get; set; }
        public Nullable<decimal> USER_NUM14 { get; set; }
        public Nullable<System.DateTime> USER_DATEI14 { get; set; }
        public string USER_FLD15 { get; set; }
        public Nullable<decimal> USER_NUM15 { get; set; }
        public Nullable<System.DateTime> USER_DATEI15 { get; set; }
        public string USER_FLD16 { get; set; }
        public Nullable<decimal> USER_NUM16 { get; set; }
        public Nullable<System.DateTime> USER_DATEI16 { get; set; }
        public string USER_FLD17 { get; set; }
        public Nullable<decimal> USER_NUM17 { get; set; }
        public Nullable<System.DateTime> USER_DATEI17 { get; set; }
        public string USER_FLD18 { get; set; }
        public Nullable<decimal> USER_NUM18 { get; set; }
        public Nullable<System.DateTime> USER_DATEI18 { get; set; }
        public string USER_FLD19 { get; set; }
        public Nullable<decimal> USER_NUM19 { get; set; }
        public Nullable<System.DateTime> USER_DATEI19 { get; set; }
        public string USER_FLD20 { get; set; }
        public Nullable<decimal> USER_NUM20 { get; set; }
        public Nullable<System.DateTime> USER_DATEI20 { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public string COMP_CHART_NAME { get; set; }
        public string COMP_CHART_IND { get; set; }
        public string STAT_IND { get; set; }
    }
}
