//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLF_LDG_ACCT_DESC1
    {
        public Nullable<short> VERS { get; set; }
        public string LDG_NAME { get; set; }
        public string ACCNBRI { get; set; }
        public string EDACCNBR { get; set; }
        public string SDESCR { get; set; }
        public string DESCR { get; set; }
        public string STATUS { get; set; }
        public string ACC_COMP1 { get; set; }
        public string ACC_COMP2 { get; set; }
        public string ACC_COMP3 { get; set; }
        public string ACC_COMP4 { get; set; }
        public string ACC_COMP5 { get; set; }
        public string ACC_COMP6 { get; set; }
        public string ACC_COMP7 { get; set; }
        public string ACC_COMP8 { get; set; }
        public string ACC_COMP9 { get; set; }
        public string ACC_COMP10 { get; set; }
        public string ACC_COMP11 { get; set; }
        public string ACC_COMP12 { get; set; }
        public string ACC_COMP1_SDESCR { get; set; }
        public string ACC_COMP2_SDESCR { get; set; }
        public string ACC_COMP3_SDESCR { get; set; }
        public string ACC_COMP4_SDESCR { get; set; }
        public string ACC_COMP5_SDESCR { get; set; }
        public string ACC_COMP6_SDESCR { get; set; }
        public string ACC_COMP7_SDESCR { get; set; }
        public string ACC_COMP8_SDESCR { get; set; }
        public string ACC_COMP9_SDESCR { get; set; }
        public string ACC_COMP10_SDESCR { get; set; }
        public string ACC_COMP11_SDESCR { get; set; }
        public string ACC_COMP12_SDESCR { get; set; }
        public string ACC_COMP1_DESCR1 { get; set; }
        public string ACC_COMP2_DESCR1 { get; set; }
        public string ACC_COMP3_DESCR1 { get; set; }
        public string ACC_COMP4_DESCR1 { get; set; }
        public string ACC_COMP5_DESCR1 { get; set; }
        public string ACC_COMP6_DESCR1 { get; set; }
        public string ACC_COMP7_DESCR1 { get; set; }
        public string ACC_COMP8_DESCR1 { get; set; }
        public string ACC_COMP9_DESCR1 { get; set; }
        public string ACC_COMP10_DESCR1 { get; set; }
        public string ACC_COMP11_DESCR1 { get; set; }
        public string ACC_COMP12_DESCR1 { get; set; }
        public string SELN_TYPE1 { get; set; }
        public string SELN_TYPE2 { get; set; }
        public string SELN_TYPE3 { get; set; }
        public string SELN_TYPE4 { get; set; }
        public string SELN_TYPE5 { get; set; }
        public string SELN_TYPE6 { get; set; }
        public string SELN_CODE1 { get; set; }
        public string SELN_CODE2 { get; set; }
        public string SELN_CODE3 { get; set; }
        public string SELN_CODE4 { get; set; }
        public string SELN_CODE5 { get; set; }
        public string SELN_CODE6 { get; set; }
        public string CHART_NAME { get; set; }
        public string SELN_TYPE7 { get; set; }
        public string SELN_TYPE8 { get; set; }
        public string SELN_TYPE9 { get; set; }
        public string SELN_TYPE10 { get; set; }
        public string SELN_TYPE11 { get; set; }
        public string SELN_TYPE12 { get; set; }
        public string SELN_TYPE13 { get; set; }
        public string SELN_TYPE14 { get; set; }
        public string SELN_TYPE15 { get; set; }
        public string SELN_TYPE16 { get; set; }
        public string SELN_TYPE17 { get; set; }
        public string SELN_TYPE18 { get; set; }
        public string SELN_TYPE19 { get; set; }
        public string SELN_TYPE20 { get; set; }
        public string SELN_CODE7 { get; set; }
        public string SELN_CODE8 { get; set; }
        public string SELN_CODE9 { get; set; }
        public string SELN_CODE10 { get; set; }
        public string SELN_CODE11 { get; set; }
        public string SELN_CODE12 { get; set; }
        public string SELN_CODE13 { get; set; }
        public string SELN_CODE14 { get; set; }
        public string SELN_CODE15 { get; set; }
        public string SELN_CODE16 { get; set; }
        public string SELN_CODE17 { get; set; }
        public string SELN_CODE18 { get; set; }
        public string SELN_CODE19 { get; set; }
        public string SELN_CODE20 { get; set; }
        public string SINGLE_CCY_IND { get; set; }
        public string SINGLE_CCY_TYPE { get; set; }
        public string SINGLE_CCY_CODE { get; set; }
        public string SINGLE_EXCH_RATE_TBL_NM { get; set; }
        public string SELN_TYPE21 { get; set; }
        public string SELN_TYPE22 { get; set; }
        public string SELN_TYPE23 { get; set; }
        public string SELN_TYPE24 { get; set; }
        public string SELN_TYPE25 { get; set; }
        public string SELN_TYPE26 { get; set; }
        public string SELN_TYPE27 { get; set; }
        public string SELN_TYPE28 { get; set; }
        public string SELN_TYPE29 { get; set; }
        public string SELN_TYPE30 { get; set; }
        public string SELN_TYPE31 { get; set; }
        public string SELN_TYPE32 { get; set; }
        public string SELN_TYPE33 { get; set; }
        public string SELN_TYPE34 { get; set; }
        public string SELN_TYPE35 { get; set; }
        public string SELN_TYPE36 { get; set; }
        public string SELN_TYPE37 { get; set; }
        public string SELN_TYPE38 { get; set; }
        public string SELN_TYPE39 { get; set; }
        public string SELN_TYPE40 { get; set; }
        public string SELN_CODE21 { get; set; }
        public string SELN_CODE22 { get; set; }
        public string SELN_CODE23 { get; set; }
        public string SELN_CODE24 { get; set; }
        public string SELN_CODE25 { get; set; }
        public string SELN_CODE26 { get; set; }
        public string SELN_CODE27 { get; set; }
        public string SELN_CODE28 { get; set; }
        public string SELN_CODE29 { get; set; }
        public string SELN_CODE30 { get; set; }
        public string SELN_CODE31 { get; set; }
        public string SELN_CODE32 { get; set; }
        public string SELN_CODE33 { get; set; }
        public string SELN_CODE34 { get; set; }
        public string SELN_CODE35 { get; set; }
        public string SELN_CODE36 { get; set; }
        public string SELN_CODE37 { get; set; }
        public string SELN_CODE38 { get; set; }
        public string SELN_CODE39 { get; set; }
        public string SELN_CODE40 { get; set; }
    }
}
