//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRCOM_ADDRESS_REF
    {
        public int ADDRESS_CODE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_STATE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string POST_CODE { get; set; }
        public string TELEPHONE_1 { get; set; }
        public string TELEPHONE_2 { get; set; }
        public string TELEPHONE_3 { get; set; }
        public string FACSIMILE_1 { get; set; }
        public string FACSIMILE_2 { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string DPID_NBR { get; set; }
        public string MOBILE_PHONE_2 { get; set; }
        public string EMAIL_ADDRESS_2 { get; set; }
    }
}
