//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREEN_EMPLENT_ACCR
    {
        public int ID_NUMBER { get; set; }
        public decimal PAY_COMPONENT_REF { get; set; }
        public Nullable<decimal> ACCRUAL_HOURS { get; set; }
        public Nullable<decimal> ACCRUAL_PRORATA { get; set; }
        public Nullable<decimal> ACCRUAL_TAKEN { get; set; }
        public Nullable<int> DURATION_OF_SERVCE { get; set; }
        public Nullable<int> NUMBER_OF_ACCRUALS { get; set; }
        public Nullable<System.DateTime> LAST_ACCRUAL_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PRORATA_DATE { get; set; }
        public Nullable<System.DateTime> LAST_TAKEN_DATE { get; set; }
        public Nullable<System.DateTime> DUR_OF_SERV_DATE { get; set; }
        public int ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<decimal> ACCR_PRORATA_ELGBL { get; set; }
        public Nullable<decimal> ACCR_PRORATA_AMT { get; set; }
        public Nullable<decimal> INIT_DUR_OF_SERV { get; set; }
        public Nullable<decimal> INIT_WAGES_ALL { get; set; }
        public Nullable<decimal> INIT_WAGES_CRUSH { get; set; }
        public Nullable<decimal> LSL_TAKEN_PRIOR_78 { get; set; }
        public Nullable<decimal> LSL_TAKEN_BW_78_93 { get; set; }
        public Nullable<decimal> LSL_TK_BW_93_LIVE { get; set; }
        public Nullable<decimal> PNG_LSL_TAKEN_PRE_93 { get; set; }
        public Nullable<decimal> PNG_LSL_TAKEN_93_TOLIVE { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> ACCRUAL_START_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PROC_DATE { get; set; }
        public string LEAVE_MATRIX_NAME { get; set; }
    }
}
