//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HREEN_EMPL_ENT_DTL
    {
        public int ID_NUMBER { get; set; }
        public int ENT_TECH_KEY { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public decimal PAY_COMPONENT_REF { get; set; }
        public Nullable<int> PAY_COMPONENT_DEF { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string ENT_POS_TITLE { get; set; }
        public string EMPLOYMENT_COND { get; set; }
        public Nullable<decimal> ENTITLEMENT_AMOUNT { get; set; }
        public string PAY_PERIOD_TYPE { get; set; }
        public Nullable<decimal> UNITS_PER_PERIOD { get; set; }
        public string PAY_PERIOD_UNIT { get; set; }
        public string DISB_CODE { get; set; }
        public string LDG_CODE { get; set; }
        public string ACCNBRI { get; set; }
        public string CLR_LDG_CODE { get; set; }
        public string CLR_ACCNBRI { get; set; }
        public string RATE_TYPE { get; set; }
        public string RATE_CODE { get; set; }
        public Nullable<short> PRIORITY_SEQUENCE { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string SERVICE_RATE_TYPE { get; set; }
        public string SERVICE_RATE_CODE { get; set; }
        public string EFF_HIER_COND_KEY { get; set; }
        public string AMOUNT_SCRIPT_NAME { get; set; }
        public string REFERENCE_NBR { get; set; }
        public string DEDUCTION_TYPE { get; set; }
    }
}
