//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_EMPLISS_DTL
    {
        public int ID_NUMBER { get; set; }
        public string ISSUE_TYPE { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public Nullable<System.DateTime> RETURNED_DATE { get; set; }
        public string RETURNABLE_IND { get; set; }
        public string ISSUE_REASON { get; set; }
        public string ISSUE_DESCR { get; set; }
        public Nullable<decimal> ISSUE_QTY { get; set; }
        public Nullable<decimal> ISSUE_VALUE { get; set; }
        public string ISSUE_ID_NMBR { get; set; }
        public Nullable<decimal> PAY_COMPONENT_REF { get; set; }
        public string TECHONE_FIELD_1 { get; set; }
        public string TECHONE_FIELD_2 { get; set; }
        public string TECHONE_FIELD_3 { get; set; }
        public string TECHONE_FIELD_4 { get; set; }
        public string TECHONE_FIELD_5 { get; set; }
        public string TECHONE_FIELD_6 { get; set; }
        public string TECHONE_FIELD_7 { get; set; }
        public Nullable<int> TECHONE_FIELD_8 { get; set; }
        public string TECHONE_FIELD_9 { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATE { get; set; }
        public Nullable<int> CRTIME { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATE { get; set; }
        public Nullable<int> LAST_MOD_TIME { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
    }
}
