//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_EMPL_REF
    {
        public int ID_NUMBER { get; set; }
        public string FAMILY_NAME { get; set; }
        public string GIVEN_NAME { get; set; }
        public string OTHER_GIVEN_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string ALIAS_NAME { get; set; }
        public string MARITAL_STATUS_CDE { get; set; }
        public string GENDER_CODE { get; set; }
        public Nullable<int> ADDRSS_POSTAL_CODE { get; set; }
        public Nullable<int> ADDRSS_STREET_CODE { get; set; }
        public string ID_CLASS { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string REHIRE_IND { get; set; }
        public string ACTIVE_IND { get; set; }
        public string EMPL_NATIONALITY { get; set; }
        public string ETHNIC_GROUP { get; set; }
        public string MAIN_LANGUAGE { get; set; }
        public string EMPL_DISABILITY { get; set; }
        public string EMPL_ID_CODE { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> ENT_TECH_KEY { get; set; }
        public string REEMPL_CODE { get; set; }
        public Nullable<System.DateTime> LAST_TERM_DATEI { get; set; }
        public string SALUTATION { get; set; }
        public string PREVIOUS_NAME { get; set; }
        public string RESIDENT_STATUS { get; set; }
        public string VISA_TYPE { get; set; }
        public string PREVIOUS_GIVEN_NAME { get; set; }
        public string PREVIOUS_OTHER_GIVEN_NAME { get; set; }
        public Nullable<System.DateTime> NEXT_EMPLPLAN_START_DATE { get; set; }
        public Nullable<int> LAST_EMPLAPPRS_ID { get; set; }
        public Nullable<System.DateTime> LAST_EMPLAPPRS_START_DATE { get; set; }
        public Nullable<System.DateTime> LAST_EMPLAPPRS_END_DATE { get; set; }
        public string TLT_MGT_SYSTEM_CODE { get; set; }
        public string RATING_PROFILE_CODE { get; set; }
        public string LAST_RATING_CODE { get; set; }
        public Nullable<decimal> LAST_RATING_CALC_SCORE { get; set; }
    }
}
