//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_EMPL_JOB_POS
    {
        public int ID_NUMBER { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public string POSITION_CODE { get; set; }
        public string POSITION_TYPE_IND { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string JOB_POS_TITLE { get; set; }
        public string REASON_TYPE { get; set; }
        public string REASON_DESCR { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public Nullable<int> ID_NUMBER_SUPERVSR { get; set; }
        public string WORK_GROUP { get; set; }
        public string WORK_LOCATION { get; set; }
        public string EMPL_COND_AWARD { get; set; }
        public string EMPL_COND_GRADE { get; set; }
        public string EMPL_COND_LEVEL { get; set; }
        public Nullable<int> ENT_TECH_KEY { get; set; }
        public string TRADE_CODE { get; set; }
        public string UNION_CODE { get; set; }
        public Nullable<int> SEASON_STATUS { get; set; }
        public string SUPERVISOR_IND { get; set; }
        public string TRADESMAN_IND { get; set; }
        public Nullable<int> TMC_SEQUENCE_NO { get; set; }
        public string TMC_CALC_METHOD { get; set; }
        public string TMC_LEAVE_RULE { get; set; }
        public string RECOV_ITEM_TYPE { get; set; }
        public string RECOV_ITEM_CODE { get; set; }
        public string ONCRECOV_ITEM_TYPE { get; set; }
        public string ONCRECOV_ITEM_CODE { get; set; }
        public string COST_TYPE { get; set; }
        public string COST_CODE { get; set; }
        public string TS_SYSTEM_NAME { get; set; }
        public string TS_FMT_NAME { get; set; }
        public string TS_ENTRY_IND { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string ORG_UNIT_CODE { get; set; }
        public string POSITION_SUPERVSR { get; set; }
        public Nullable<decimal> FULL_TIME_EQUIVALENT { get; set; }
        public string INCREMENT_IND { get; set; }
        public string HOME_COST_CENTRE { get; set; }
        public string DISB_CODE { get; set; }
        public string SECURITY_PROFILE_NAME { get; set; }
    }
}
