//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_USR_FLD
    {
        public int ID_NUMBER { get; set; }
        public string SELN_CD1 { get; set; }
        public string SELN_CD2 { get; set; }
        public string SELN_CD3 { get; set; }
        public string SELN_CD4 { get; set; }
        public string SELN_CD5 { get; set; }
        public string SELN_CD6 { get; set; }
        public string SELN_CD7 { get; set; }
        public string SELN_CD8 { get; set; }
        public string SELN_CD9 { get; set; }
        public string SELN_CD10 { get; set; }
        public string SELN_CD11 { get; set; }
        public string SELN_CD12 { get; set; }
        public string SELN_CD13 { get; set; }
        public string SELN_CD14 { get; set; }
        public string SELN_CD15 { get; set; }
        public string SELN_CD16 { get; set; }
        public string SELN_CD17 { get; set; }
        public string SELN_CD18 { get; set; }
        public string SELN_CD19 { get; set; }
        public string SELN_CD20 { get; set; }
        public string VAL_ALPHA1 { get; set; }
        public string VAL_ALPHA2 { get; set; }
        public string VAL_ALPHA3 { get; set; }
        public string VAL_ALPHA4 { get; set; }
        public string VAL_ALPHA5 { get; set; }
        public string VAL_ALPHA6 { get; set; }
        public string VAL_ALPHA7 { get; set; }
        public string VAL_ALPHA8 { get; set; }
        public string VAL_ALPHA9 { get; set; }
        public string VAL_ALPHA10 { get; set; }
        public string VAL_ALPHA11 { get; set; }
        public string VAL_ALPHA12 { get; set; }
        public string VAL_ALPHA13 { get; set; }
        public string VAL_ALPHA14 { get; set; }
        public string VAL_ALPHA15 { get; set; }
        public string VAL_ALPHA16 { get; set; }
        public string VAL_ALPHA17 { get; set; }
        public string VAL_ALPHA18 { get; set; }
        public string VAL_ALPHA19 { get; set; }
        public string VAL_ALPHA20 { get; set; }
        public Nullable<decimal> VAL_NUM1 { get; set; }
        public Nullable<decimal> VAL_NUM2 { get; set; }
        public Nullable<decimal> VAL_NUM3 { get; set; }
        public Nullable<decimal> VAL_NUM4 { get; set; }
        public Nullable<decimal> VAL_NUM5 { get; set; }
        public Nullable<decimal> VAL_NUM6 { get; set; }
        public Nullable<decimal> VAL_NUM7 { get; set; }
        public Nullable<decimal> VAL_NUM8 { get; set; }
        public Nullable<decimal> VAL_NUM9 { get; set; }
        public Nullable<decimal> VAL_NUM10 { get; set; }
        public Nullable<decimal> VAL_NUM11 { get; set; }
        public Nullable<decimal> VAL_NUM12 { get; set; }
        public Nullable<decimal> VAL_NUM13 { get; set; }
        public Nullable<decimal> VAL_NUM14 { get; set; }
        public Nullable<decimal> VAL_NUM15 { get; set; }
        public Nullable<decimal> VAL_NUM16 { get; set; }
        public Nullable<decimal> VAL_NUM17 { get; set; }
        public Nullable<decimal> VAL_NUM18 { get; set; }
        public Nullable<decimal> VAL_NUM19 { get; set; }
        public Nullable<decimal> VAL_NUM20 { get; set; }
        public Nullable<System.DateTime> VAL_DATE1 { get; set; }
        public Nullable<System.DateTime> VAL_DATE2 { get; set; }
        public Nullable<System.DateTime> VAL_DATE3 { get; set; }
        public Nullable<System.DateTime> VAL_DATE4 { get; set; }
        public Nullable<System.DateTime> VAL_DATE5 { get; set; }
        public Nullable<System.DateTime> VAL_DATE6 { get; set; }
        public Nullable<System.DateTime> VAL_DATE7 { get; set; }
        public Nullable<System.DateTime> VAL_DATE8 { get; set; }
        public Nullable<System.DateTime> VAL_DATE9 { get; set; }
        public Nullable<System.DateTime> VAL_DATE10 { get; set; }
        public Nullable<System.DateTime> VAL_DATE11 { get; set; }
        public Nullable<System.DateTime> VAL_DATE12 { get; set; }
        public Nullable<System.DateTime> VAL_DATE13 { get; set; }
        public Nullable<System.DateTime> VAL_DATE14 { get; set; }
        public Nullable<System.DateTime> VAL_DATE15 { get; set; }
        public Nullable<System.DateTime> VAL_DATE16 { get; set; }
        public Nullable<System.DateTime> VAL_DATE17 { get; set; }
        public Nullable<System.DateTime> VAL_DATE18 { get; set; }
        public Nullable<System.DateTime> VAL_DATE19 { get; set; }
        public Nullable<System.DateTime> VAL_DATE20 { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATEI { get; set; }
        public Nullable<int> CLOSED_TIMEI { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public Nullable<short> VERS { get; set; }
    }
}
