//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_EMPL_JOB_CTL
    {
        public int ID_NUMBER { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public string JOB_DTL_TITLE { get; set; }
        public string REASON_TYPE { get; set; }
        public string REASON_DESCR { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public Nullable<System.DateTime> DATE_HIRED { get; set; }
        public Nullable<System.DateTime> PROBATN_PERIOD_END { get; set; }
        public Nullable<System.DateTime> NEXT_REVIEW_DATE { get; set; }
        public string EMPL_TYPE_CODE { get; set; }
        public string EMPL_CLASS { get; set; }
        public string HOLIDAY_CTGY { get; set; }
        public string PAY_BASIS_CODE { get; set; }
        public string PAY_DOC_TYPE { get; set; }
        public string PAY_PERIOD_TYPE { get; set; }
        public string PAY_LOCATION { get; set; }
        public string PAYADV_TRANS_METH { get; set; }
        public string PAYADV_ADDRESS { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string INCREMENT_IND { get; set; }
        public string PAYROLL_TAX_STATE { get; set; }
        public string WORKCOVER_TAX_STATE { get; set; }
        public string REGION_CODE { get; set; }
        public string ID_CLASS { get; set; }
        public string TLT_MGT_SYSTEM_CODE { get; set; }
        public string APPRS_CYCLE_CODE { get; set; }
        public string PROBATN_GENERATE_IND { get; set; }
        public string PROBATN_POSITION_PROFILE { get; set; }
        public Nullable<System.DateTime> PROBATN_PERIOD_START { get; set; }
        public Nullable<int> PROBATN_EMPLPLAN_ID { get; set; }
        public string PROBATN_COMP_IND { get; set; }
        public string PROBATN_OTCM_CODE { get; set; }
        public string PROBATN_TLT_MGT_SYSTEM { get; set; }
        public string PROBATN_APPRS_METH_CODE { get; set; }
    }
}
