//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_EMPLQUAL_DTL
    {
        public int ID_NUMBER { get; set; }
        public string QUAL_CODE { get; set; }
        public Nullable<System.DateTime> QUAL_ISSUE_DATE { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> QUAL_CANCEL_DATE { get; set; }
        public string EXTEND_QUAL_DESC { get; set; }
        public string QUAL_LEVEL { get; set; }
        public Nullable<int> YEAR_GRADUATED { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string STATUS { get; set; }
        public string SOURCE_TYPE { get; set; }
        public string SOURCE_ID { get; set; }
        public Nullable<System.DateTime> QUAL_EXPIRY_DATEI { get; set; }
        public Nullable<System.DateTime> QUAL_TARGET_DATEI { get; set; }
        public Nullable<int> INST_COMPANY_CODE { get; set; }
        public int EMPLQUAL_SEQ_NO { get; set; }
        public string SUPERSEDED_IND { get; set; }
        public string EMPLQUAL_STATUS { get; set; }
        public string EMPLQUAL_CANCEL_STATUS { get; set; }
        public string CANCEL_SOURCE_TYPE { get; set; }
        public string WRKFLW_SYSTEM { get; set; }
        public string WRKFLW_NAME { get; set; }
        public string CANCEL_WRKFLW_SYSTEM { get; set; }
        public string CANCEL_WRKFLW_NAME { get; set; }
        public Nullable<int> ORIGINAL_ID_NUMBER { get; set; }
    }
}
