//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRHMN_QUAL_REF
    {
        public string QUAL_CODE { get; set; }
        public string QUAL_DESC { get; set; }
        public string ISSUING_INSTITUTON { get; set; }
        public string COUNTRY_CODE { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string QUAL_TYPE { get; set; }
        public string EXPIRY_TYPE { get; set; }
        public Nullable<decimal> EXPIRY_PERIOD { get; set; }
        public string COMMENTS { get; set; }
        public string QUAL_CATEGORY { get; set; }
        public Nullable<int> EMPL_EXPIRING_ALERT_DAYS { get; set; }
        public Nullable<int> MGR_EXPIRING_ALERT_DAYS { get; set; }
        public Nullable<int> HR_EXPIRING_ALERT_DAYS { get; set; }
    }
}
