//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRLVE_LEAVE_CTL
    {
        public int LEAVE_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string REQUEST_TYPE { get; set; }
        public Nullable<decimal> PAY_COMPONENT_REF { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public string HISTORICAL_IND { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string PART_DAY_IND { get; set; }
        public Nullable<decimal> PART_DAY_UNITS { get; set; }
        public string COMMENTS { get; set; }
        public string POSITION_CODE { get; set; }
        public string PAY_IN_ADVANCE_IND { get; set; }
        public string EXTERNAL_REFERENCE { get; set; }
        public Nullable<decimal> WORK_DAYS { get; set; }
        public Nullable<decimal> PUBLIC_HOLIDAYS { get; set; }
        public Nullable<int> PARENT_LEAVE_ID { get; set; }
        public Nullable<int> ORIGINAL_LEAVE_ID { get; set; }
        public string WRKFLW_SYSTEM { get; set; }
        public string WRKFLW_NAME { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public string APPROVAL_USER_ID { get; set; }
        public Nullable<int> VERS { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
    }
}
