//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_PAYITEMS_SUMMPMNT
    {
        public int COMPANY_CODE { get; set; }
        public System.DateTime PAY_PERIOD_ENDDATE { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public decimal PAY_COMPONENT_REF { get; set; }
        public string SUPER_FUND_CODE { get; set; }
        public string UNIT_TYPE { get; set; }
        public Nullable<decimal> NUMBER_OF_UNITS { get; set; }
        public Nullable<decimal> YTD_OPENING_AMOUNT { get; set; }
        public Nullable<decimal> PERIOD_AMOUNT { get; set; }
        public Nullable<decimal> YTD_CLOSING_AMOUNT { get; set; }
        public Nullable<decimal> PREV_AMOUNT { get; set; }
        public Nullable<decimal> PAY_COMPONENT_DEF { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string TAXABLE_IND { get; set; }
        public string BANK_CODE { get; set; }
        public string BANK_BRANCH_NUMBER { get; set; }
        public string BANK_ACCOUNT_NUMBER { get; set; }
        public string BANK_ACCOUNT_NAME { get; set; }
        public string SUPER_INSTITUTE_CODE { get; set; }
        public string SUPER_MEMBER_NUMBER { get; set; }
        public string SUPER_CONTRIBUTION_TYPE { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
    }
}
