//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_LVE_TKN_DTL
    {
        public string SOURCE_IND { get; set; }
        public int ID_NUMBER { get; set; }
        public System.DateTime DOCUMENT_DATE { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public int DOCUMENT_NBR { get; set; }
        public int SEQUENCE_NBR { get; set; }
        public int ITEM_NBR { get; set; }
        public decimal PAY_COMPONENT_REF { get; set; }
        public Nullable<int> PAY_COMPONENT_DEF { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public decimal ACCRL_PAY_COMP_REF { get; set; }
        public Nullable<decimal> NUMBER_UNITS { get; set; }
        public string UNIT_TYPE { get; set; }
        public string PROCESSED_PAY_IND { get; set; }
        public string PROCESSED_TMS_IND { get; set; }
        public string NEG_ACCR_ACTION { get; set; }
        public Nullable<decimal> EXCEEDED_UNITS { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<decimal> AUTH_OVERRIDE { get; set; }
    }
}
