//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_LEAVE_CTL
    {
        public string LEAVE_CTL_TYPE { get; set; }
        public int ID_NUMBER { get; set; }
        public System.DateTime LEAVE_START_DATE { get; set; }
        public Nullable<System.DateTime> LEAVE_END_DATE { get; set; }
        public Nullable<decimal> PAY_COMPONENT_REF { get; set; }
        public Nullable<System.DateTime> PAY_PERIOD_DATE { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string DOC_TYPE_CODE { get; set; }
        public Nullable<int> TMC_SEQ_NUMBER { get; set; }
        public Nullable<decimal> NUMBER_OF_WEEKS { get; set; }
        public Nullable<int> ID_NUMBER_APPRVNG { get; set; }
        public string LEAVE_DESCR { get; set; }
        public string ORIG_AUTH_CODE { get; set; }
        public string LAST_AUTH_CODE { get; set; }
        public string REFER_AUTH_CODE { get; set; }
        public Nullable<int> LAST_AUTH_SEQNBR { get; set; }
        public string AUTH_STATUS { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string LEAVE_STATUS { get; set; }
        public string LEAVE_SUB_STATUS { get; set; }
        public string LDG_CODE { get; set; }
        public string ACCNBRI { get; set; }
        public string POSITION_CODE { get; set; }
        public string REFERENCE_NBR { get; set; }
        public string LEAVE_STATUS_USER_ID { get; set; }
        public string LEAVE_STATUS_COMMENT { get; set; }
        public short LEAVE_SEQ_NBR { get; set; }
        public Nullable<short> REVERSING_LEAVE_SEQ_NBR { get; set; }
    }
}
