//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_MASTER_CTL
    {
        public string DOCUMENT_TYPE { get; set; }
        public int COMPANY_CODE { get; set; }
        public int PAY_DOCUMENT_NO { get; set; }
        public Nullable<int> ID_NUMBER { get; set; }
        public Nullable<System.DateTime> PAY_PERIOD_ENDDATE { get; set; }
        public string PAY_PERIOD_TYPE { get; set; }
        public Nullable<decimal> BASE_AMOUNT { get; set; }
        public Nullable<decimal> GROSS_AMOUNT { get; set; }
        public Nullable<decimal> TAXABLE_INCOME { get; set; }
        public Nullable<decimal> TOTAL_TAX_AMOUNT { get; set; }
        public Nullable<decimal> NETT_PAY { get; set; }
        public Nullable<System.DateTime> PAY_CALC_DATE { get; set; }
        public Nullable<System.DateTime> JNL_CREATION_DATE { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<System.DateTime> PAID_DATE { get; set; }
        public Nullable<decimal> NO_OF_PAY_PERIODS { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public Nullable<decimal> PAYMENT_METHOD_PC { get; set; }
        public Nullable<System.DateTime> PAY_PERIOD_STARTDATE { get; set; }
        public string PERIODEND_POSITION_CODE { get; set; }
        public Nullable<System.DateTime> PERIODEND_JOB_EFFDATE { get; set; }
        public Nullable<System.DateTime> PERIODEND_TAX_EFFDATE { get; set; }
    }
}
