//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_PAYITEMS_SUMMACCR
    {
        public int EMPLOYEE_ID { get; set; }
        public System.DateTime ACCRUAL_DATE { get; set; }
        public decimal PAY_COMPONENT_REF { get; set; }
        public Nullable<decimal> PERIOD_ACCRUAL { get; set; }
        public Nullable<decimal> PERIOD_TAKEN { get; set; }
        public string UNIT_TYPE { get; set; }
        public Nullable<decimal> OPEN_ENTITLEMENT { get; set; }
        public Nullable<decimal> OPEN_PRO_RATA { get; set; }
        public Nullable<decimal> OPEN_TAKEN { get; set; }
        public Nullable<decimal> OPEN_BALANCE { get; set; }
        public Nullable<decimal> CLOSE_ENTITLEMENT { get; set; }
        public Nullable<decimal> CLOSE_PRO_RATA { get; set; }
        public Nullable<decimal> CLOSE_TAKEN { get; set; }
        public Nullable<decimal> CLOSE_BALANCE { get; set; }
        public Nullable<decimal> PREV_ENTITLEMENT { get; set; }
        public Nullable<decimal> PREV_PRO_RATA { get; set; }
        public Nullable<decimal> PREV_TAKEN { get; set; }
        public Nullable<decimal> PREV_BALANCE { get; set; }
        public string ACCRUAL_GROUP { get; set; }
        public Nullable<System.DateTime> LAST_ACCRUAL_DATE { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
    }
}
