//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_LEAVE_DTL
    {
        public int ID_NUMBER { get; set; }
        public System.DateTime PAY_PERIOD_DATE { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public string DOC_TYPE_CODE { get; set; }
        public Nullable<System.DateTime> LEAVE_START_DATE { get; set; }
        public Nullable<System.DateTime> LEAVE_END_DATE { get; set; }
        public Nullable<System.DateTime> TERMINATION_DATE { get; set; }
        public Nullable<decimal> HOURLY_RATE { get; set; }
        public string USE_ANNUAL_LEAVE { get; set; }
        public string USE_LSL { get; set; }
        public Nullable<decimal> AL_93_HRS_ACCRUED { get; set; }
        public Nullable<decimal> AL_93_HRS_ACCRUAL { get; set; }
        public Nullable<decimal> AL_93_AMOUNT { get; set; }
        public Nullable<decimal> AL_93_TAX { get; set; }
        public Nullable<decimal> AL_HOURS_ACCRUED { get; set; }
        public Nullable<decimal> AL_HOURS_ACCRUAL { get; set; }
        public Nullable<decimal> AL_HOURS_PRORATA { get; set; }
        public Nullable<decimal> AL_AMOUNT { get; set; }
        public Nullable<decimal> TT_HOURS_ACCRUED { get; set; }
        public Nullable<decimal> TT_HOURS { get; set; }
        public Nullable<decimal> TT_HOURS_PRORATA { get; set; }
        public Nullable<decimal> TT_AMOUNT { get; set; }
        public Nullable<decimal> CONT_CRUSH_HOURS { get; set; }
        public Nullable<decimal> CONT_CRUSH_AMOUNT { get; set; }
        public Nullable<decimal> RDO_HOURS { get; set; }
        public Nullable<decimal> RDO_AMOUNT { get; set; }
        public Nullable<decimal> ADO_HOURS { get; set; }
        public Nullable<decimal> ADO_AMOUNT { get; set; }
        public Nullable<decimal> PUBLIC_HOLIDAY_HRS { get; set; }
        public Nullable<decimal> PUBLIC_HOLIDAY_AMT { get; set; }
        public Nullable<decimal> SICK_PAY_HOURS { get; set; }
        public Nullable<decimal> SICK_PAY_AMOUNT { get; set; }
        public Nullable<decimal> ALL_AMOUNT { get; set; }
        public Nullable<decimal> ALL_AMOUNT_YTD { get; set; }
        public Nullable<decimal> EXTRA_AMOUNTS { get; set; }
        public Nullable<decimal> TOTAL_LEAVE_AMNTS { get; set; }
        public Nullable<decimal> LSL_TTL_HRS_ACCRD { get; set; }
        public Nullable<decimal> LSL_TTL_AMOUNT { get; set; }
        public Nullable<decimal> LSL_TTL_TAX { get; set; }
        public Nullable<decimal> LSL_78_HOURS_ACCRD { get; set; }
        public Nullable<decimal> LSL_78_HOURS_ACCRL { get; set; }
        public Nullable<decimal> LSL_78_AMOUNT { get; set; }
        public Nullable<decimal> LSL_78_TAX { get; set; }
        public Nullable<decimal> LSL_93_HOURS_ACCRD { get; set; }
        public Nullable<decimal> LSL_93_HOURS_ACCRL { get; set; }
        public Nullable<decimal> LSL_93_AMOUNT { get; set; }
        public Nullable<decimal> LSL_93_TAX { get; set; }
        public Nullable<decimal> LSL_HOURS_ACCRUED { get; set; }
        public Nullable<decimal> LSL_HOURS_ACCRUAL { get; set; }
        public Nullable<decimal> LSL_HOURS_PRORATA { get; set; }
        public Nullable<decimal> LSL_AMOUNT { get; set; }
        public Nullable<decimal> CURRENT_GROSS_AMNT { get; set; }
        public Nullable<decimal> CURRENT_GROSS_TAX { get; set; }
        public Nullable<decimal> LSP_AMOUNT { get; set; }
        public Nullable<decimal> LSP_TAX { get; set; }
        public Nullable<decimal> LSP_TAXABLE { get; set; }
        public Nullable<decimal> TOTAL_TAX { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<decimal> HOURLY_RATE_SLACK { get; set; }
        public string USE_LSL_FIRST { get; set; }
        public Nullable<decimal> LSL_DAYS { get; set; }
        public Nullable<decimal> LSL_DAYS_SLACK { get; set; }
        public Nullable<decimal> LSL_HOURS_SLACK { get; set; }
        public Nullable<decimal> LSL_AMOUNT_SLACK { get; set; }
        public Nullable<decimal> AL_HOURS_SLACK { get; set; }
        public Nullable<decimal> AL_AMOUNT_SLACK { get; set; }
        public Nullable<decimal> TT_HOURS_SLACK { get; set; }
        public Nullable<decimal> TT_AMOUNT_SLACK { get; set; }
        public Nullable<decimal> PH_HOURS_SLACK { get; set; }
        public Nullable<decimal> PH_AMOUNT_SLACK { get; set; }
        public Nullable<decimal> TTL_WORKDAYS { get; set; }
        public Nullable<decimal> TTL_WORKDAYS_SLACK { get; set; }
        public Nullable<int> NUMBER_OF_WEEKS { get; set; }
    }
}
