//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPAY_PAYITEMS_DTL
    {
        public string DOCUMENT_TYPE { get; set; }
        public int COMPANY_CODE { get; set; }
        public int PAY_DOCUMENT_NO { get; set; }
        public string PAY_COMPONENT_DEF1 { get; set; }
        public string PAY_COMPONENT_REF1 { get; set; }
        public int SEQUENCE_NO { get; set; }
        public string MODULE_ID { get; set; }
        public Nullable<decimal> NUMBER_UNITS { get; set; }
        public string PAY_PERIOD_UNIT { get; set; }
        public Nullable<decimal> PAY_ITEM_RATE { get; set; }
        public Nullable<decimal> PAY_ITEM_AMOUNT { get; set; }
        public string TAXABLE { get; set; }
        public string PAYMENT { get; set; }
        public string CALBYDAYSWORKED { get; set; }
        public string ACCTS_PAYABLE_REF { get; set; }
        public string ACCOUNT_MUMBER { get; set; }
        public string BONUS_CODE { get; set; }
        public Nullable<System.DateTime> PAY_CALC_DATE { get; set; }
        public string PAY_ITEM_EXPL { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string TRANS_ACCNT_NO { get; set; }
        public Nullable<int> ROW_STATUS { get; set; }
        public string CLOSED_USER { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public Nullable<int> CLOSED_TIME { get; set; }
        public string CLOSED_TERM { get; set; }
        public string CLOSED_WINDOW { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public Nullable<System.DateTime> ACCRUAL_DATE { get; set; }
        public Nullable<System.DateTime> ACCRUAL_DATE_PREV { get; set; }
        public Nullable<decimal> ACCRUAL_AMT_PREV { get; set; }
        public Nullable<int> PAY_COMPONENT_DEF { get; set; }
        public decimal PAY_COMPONENT_REF { get; set; }
        public Nullable<int> NO_ACCRUALS_PREV { get; set; }
        public Nullable<int> NO_ACCRUALS { get; set; }
        public string PAY_ITEM_TYPE { get; set; }
        public string DISB_CODE { get; set; }
        public string LDG_CODE { get; set; }
        public string ACCNBRI { get; set; }
        public string CLR_LDG_CODE { get; set; }
        public string CLR_ACCNBRI { get; set; }
        public string DISBURSED_IND { get; set; }
        public Nullable<int> ID_NUMBER { get; set; }
        public Nullable<System.DateTime> PAY_PERIOD_ENDDATE { get; set; }
        public string PAY_PERIOD_TYPE { get; set; }
        public string POSTED_IND { get; set; }
        public string PGRP_NAME { get; set; }
        public Nullable<short> PERIOD { get; set; }
        public string LDG_NAME { get; set; }
        public Nullable<decimal> TRANS_NBR { get; set; }
        public string CLR_LDG_NAME { get; set; }
        public Nullable<decimal> CLR_TRANS_NBR { get; set; }
        public string EMPL_COND_AWARD { get; set; }
        public string EMPL_COND_GRADE { get; set; }
        public string EMPL_COND_LEVEL { get; set; }
        public string POSTING_IND { get; set; }
        public string EMPL_DEBTOR_IND { get; set; }
        public string CALC_TYPE { get; set; }
        public string TECHONE_FLD1 { get; set; }
        public string TECHONE_FLD2 { get; set; }
        public string TECHONE_FLD3 { get; set; }
        public string TECHONE_FLD4 { get; set; }
        public string POSITION_CODE { get; set; }
        public Nullable<System.DateTime> ITEM_START_DATEI { get; set; }
        public Nullable<System.DateTime> ITEM_END_DATEI { get; set; }
        public Nullable<System.DateTime> WORKED_PAY_PERIOD_ENDDATE { get; set; }
        public string IMPACT_STATUS { get; set; }
        public Nullable<short> FUND_NBR { get; set; }
        public string FUND_TRANS_CLASS { get; set; }
        public string FUND_LDG_NAME { get; set; }
        public string FUND_ACCNBRI { get; set; }
        public string FUNDS_CTL_IND { get; set; }
        public string FUNDS_CTL_IND_CLR { get; set; }
        public Nullable<short> FUND_NBR_CLR { get; set; }
        public string FUND_TRNS_CLSS_CLR { get; set; }
        public string FUND_LDG_NAME_CLR { get; set; }
        public string FUND_ACCNBRI_CLR { get; set; }
        public string REFERENCE_NBR { get; set; }
    }
}
