//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrpcm_paycomp_def
    {
        public string pay_component_def1 { get; set; }
        public string pay_component_desc { get; set; }
        public string payment_deduction { get; set; }
        public string taxable { get; set; }
        public string calc_days_worked { get; set; }
        public string autoinclude { get; set; }
        public Nullable<int> row_status { get; set; }
        public string closed_user { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public Nullable<int> closed_time { get; set; }
        public string closed_term { get; set; }
        public string closed_window { get; set; }
        public string cruser { get; set; }
        public Nullable<System.DateTime> crdatei { get; set; }
        public Nullable<int> crtimei { get; set; }
        public string crterm { get; set; }
        public string crwindow { get; set; }
        public string last_mod_user { get; set; }
        public Nullable<System.DateTime> last_mod_datei { get; set; }
        public Nullable<int> last_mod_timei { get; set; }
        public string last_mod_term { get; set; }
        public string last_mod_window { get; set; }
        public Nullable<int> vers { get; set; }
        public int pay_component_def { get; set; }
        public string posting_type_ind { get; set; }
        public string use_in_other_pos { get; set; }
        public string default_to_primary { get; set; }
    }
}
