//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrpcm_paycomp_ref
    {
        public string pay_component_def1 { get; set; }
        public string pay_component_ref1 { get; set; }
        public Nullable<System.DateTime> pay_comp_eff_date { get; set; }
        public string pay_comp_ref_desc { get; set; }
        public string payment_deduction { get; set; }
        public string taxable { get; set; }
        public string calcbydaysworked { get; set; }
        public string etp_type_payment { get; set; }
        public string control_method { get; set; }
        public string pay_period_type { get; set; }
        public Nullable<decimal> units_per_period { get; set; }
        public string pay_period_unit { get; set; }
        public string accrual_marker { get; set; }
        public Nullable<int> row_status { get; set; }
        public string closed_user { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public Nullable<int> closed_time { get; set; }
        public string closed_term { get; set; }
        public string closed_window { get; set; }
        public string cruser { get; set; }
        public Nullable<System.DateTime> crdatei { get; set; }
        public Nullable<int> crtimei { get; set; }
        public string crterm { get; set; }
        public string crwindow { get; set; }
        public string last_mod_user { get; set; }
        public Nullable<System.DateTime> last_mod_datei { get; set; }
        public Nullable<int> last_mod_timei { get; set; }
        public string last_mod_term { get; set; }
        public string last_mod_window { get; set; }
        public Nullable<int> vers { get; set; }
        public string dep_pay_comp_def1 { get; set; }
        public string dep_pay_comp_ref1 { get; set; }
        public Nullable<decimal> component_amount { get; set; }
        public string use_season_status { get; set; }
        public string accrl_paycomp_ref1 { get; set; }
        public string usedbyroster { get; set; }
        public Nullable<int> pay_component_def { get; set; }
        public decimal pay_component_ref { get; set; }
        public Nullable<int> dep_pay_comp_def { get; set; }
        public Nullable<decimal> dep_pay_comp_ref { get; set; }
        public Nullable<decimal> accrl_pay_comp_ref { get; set; }
        public Nullable<decimal> amount_minimum { get; set; }
        public Nullable<decimal> amount_maximum { get; set; }
        public Nullable<decimal> units_minimum { get; set; }
        public Nullable<decimal> units_maximum { get; set; }
        public string posting_ind { get; set; }
        public Nullable<decimal> techone_fld1 { get; set; }
        public Nullable<decimal> techone_fld2 { get; set; }
        public Nullable<decimal> techone_fld3 { get; set; }
        public Nullable<decimal> techone_fld4 { get; set; }
        public Nullable<System.DateTime> techone_fld5 { get; set; }
        public Nullable<System.DateTime> techone_fld6 { get; set; }
        public Nullable<System.DateTime> techone_fld7 { get; set; }
        public Nullable<System.DateTime> techone_fld8 { get; set; }
        public string techone_fld9 { get; set; }
        public string techone_fld10 { get; set; }
        public string techone_fld11 { get; set; }
        public string techone_fld12 { get; set; }
        public string self_service_ind { get; set; }
        public string payslip_print_ind { get; set; }
        public Nullable<short> priority_sequence { get; set; }
        public string tsheet_ind { get; set; }
        public string dep_config_code { get; set; }
        public string trans_depndt_ind { get; set; }
        public Nullable<decimal> percent_multiplier { get; set; }
        public string amount_script_name { get; set; }
        public string dep_script_name { get; set; }
        public string percent_total_ind { get; set; }
        public string payee_code { get; set; }
        public string deduction_type { get; set; }
        public string rpt_group_1 { get; set; }
        public string rpt_group_2 { get; set; }
        public string rpt_group_3 { get; set; }
        public string rpt_group_4 { get; set; }
        public string rpt_group_5 { get; set; }
    }
}
