//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrstc_code
    {
        public string code_type { get; set; }
        public string code_id { get; set; }
        public string code_descr { get; set; }
        public string active_flag { get; set; }
        public Nullable<int> seq_no { get; set; }
        public string modifiable_by_user { get; set; }
        public string able_change_desc { get; set; }
        public string cruser { get; set; }
        public Nullable<System.DateTime> crdatei { get; set; }
        public Nullable<int> crtimei { get; set; }
        public string crterm { get; set; }
        public string crwindow { get; set; }
        public string last_mod_user { get; set; }
        public Nullable<System.DateTime> last_mod_datei { get; set; }
        public Nullable<int> last_mod_timei { get; set; }
        public string last_mod_term { get; set; }
        public string last_mod_window { get; set; }
        public Nullable<int> vers { get; set; }
    }
}
