//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrsys_usrseln_dtl
    {
        public string entity_type { get; set; }
        public int unique_nbr { get; set; }
        public string entity_key_1 { get; set; }
        public string entity_key_2 { get; set; }
        public string entity_key_3 { get; set; }
        public string entity_key_4 { get; set; }
        public string entity_key_5 { get; set; }
        public string entity_key_6 { get; set; }
        public string entity_key_7 { get; set; }
        public string entity_key_8 { get; set; }
        public string entity_key_9 { get; set; }
        public string entity_key_10 { get; set; }
        public string seln_code1 { get; set; }
        public string seln_code2 { get; set; }
        public string seln_code3 { get; set; }
        public string seln_code4 { get; set; }
        public string seln_code5 { get; set; }
        public string seln_code6 { get; set; }
        public string seln_code7 { get; set; }
        public string seln_code8 { get; set; }
        public string seln_code9 { get; set; }
        public string seln_code10 { get; set; }
        public string seln_code11 { get; set; }
        public string seln_code12 { get; set; }
        public string seln_code13 { get; set; }
        public string seln_code14 { get; set; }
        public string seln_code15 { get; set; }
        public string seln_code16 { get; set; }
        public string seln_code17 { get; set; }
        public string seln_code18 { get; set; }
        public string seln_code19 { get; set; }
        public string seln_code20 { get; set; }
        public string val_alpha1 { get; set; }
        public string val_alpha2 { get; set; }
        public string val_alpha3 { get; set; }
        public string val_alpha4 { get; set; }
        public string val_alpha5 { get; set; }
        public string val_alpha6 { get; set; }
        public string val_alpha7 { get; set; }
        public string val_alpha8 { get; set; }
        public string val_alpha9 { get; set; }
        public string val_alpha10 { get; set; }
        public string val_alpha11 { get; set; }
        public string val_alpha12 { get; set; }
        public string val_alpha13 { get; set; }
        public string val_alpha14 { get; set; }
        public string val_alpha15 { get; set; }
        public string val_alpha16 { get; set; }
        public string val_alpha17 { get; set; }
        public string val_alpha18 { get; set; }
        public string val_alpha19 { get; set; }
        public string val_alpha20 { get; set; }
        public Nullable<decimal> val_num1 { get; set; }
        public Nullable<decimal> val_num2 { get; set; }
        public Nullable<decimal> val_num3 { get; set; }
        public Nullable<decimal> val_num4 { get; set; }
        public Nullable<decimal> val_num5 { get; set; }
        public Nullable<decimal> val_num6 { get; set; }
        public Nullable<decimal> val_num7 { get; set; }
        public Nullable<decimal> val_num8 { get; set; }
        public Nullable<decimal> val_num9 { get; set; }
        public Nullable<decimal> val_num10 { get; set; }
        public Nullable<decimal> val_num11 { get; set; }
        public Nullable<decimal> val_num12 { get; set; }
        public Nullable<decimal> val_num13 { get; set; }
        public Nullable<decimal> val_num14 { get; set; }
        public Nullable<decimal> val_num15 { get; set; }
        public Nullable<decimal> val_num16 { get; set; }
        public Nullable<decimal> val_num17 { get; set; }
        public Nullable<decimal> val_num18 { get; set; }
        public Nullable<decimal> val_num19 { get; set; }
        public Nullable<decimal> val_num20 { get; set; }
        public Nullable<System.DateTime> val_date1 { get; set; }
        public Nullable<System.DateTime> val_date2 { get; set; }
        public Nullable<System.DateTime> val_date3 { get; set; }
        public Nullable<System.DateTime> val_date4 { get; set; }
        public Nullable<System.DateTime> val_date5 { get; set; }
        public Nullable<System.DateTime> val_date6 { get; set; }
        public Nullable<System.DateTime> val_date7 { get; set; }
        public Nullable<System.DateTime> val_date8 { get; set; }
        public Nullable<System.DateTime> val_date9 { get; set; }
        public Nullable<System.DateTime> val_date10 { get; set; }
        public Nullable<System.DateTime> val_date11 { get; set; }
        public Nullable<System.DateTime> val_date12 { get; set; }
        public Nullable<System.DateTime> val_date13 { get; set; }
        public Nullable<System.DateTime> val_date14 { get; set; }
        public Nullable<System.DateTime> val_date15 { get; set; }
        public Nullable<System.DateTime> val_date16 { get; set; }
        public Nullable<System.DateTime> val_date17 { get; set; }
        public Nullable<System.DateTime> val_date18 { get; set; }
        public Nullable<System.DateTime> val_date19 { get; set; }
        public Nullable<System.DateTime> val_date20 { get; set; }
        public string cruser { get; set; }
        public Nullable<System.DateTime> crdatei { get; set; }
        public Nullable<int> crtimei { get; set; }
        public string crterm { get; set; }
        public string crwindow { get; set; }
        public string last_mod_user { get; set; }
        public Nullable<System.DateTime> last_mod_datei { get; set; }
        public Nullable<int> last_mod_timei { get; set; }
        public string last_mod_term { get; set; }
        public string last_mod_window { get; set; }
        public Nullable<short> vers { get; set; }
    }
}
