//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrsys_hiereff_mst
    {
        public int company_code { get; set; }
        public string hierarchy_type { get; set; }
        public string hierarchy_code { get; set; }
        public System.DateTime effective_datei { get; set; }
        public string security_role_code { get; set; }
        public string comments { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> end_datei { get; set; }
        public Nullable<decimal> ftes_per_position { get; set; }
        public Nullable<decimal> default_fte { get; set; }
        public string empl_type_code { get; set; }
        public string empl_class { get; set; }
        public string pay_location { get; set; }
        public string pay_basis_code { get; set; }
        public string pay_period_type { get; set; }
        public string pay_doc_type { get; set; }
        public string holiday_ctgy { get; set; }
        public string department_code { get; set; }
        public string org_unit_code { get; set; }
        public string work_group { get; set; }
        public string work_location { get; set; }
        public string trade_code { get; set; }
        public string union_code { get; set; }
        public Nullable<int> season_status { get; set; }
        public Nullable<int> mst_company_code { get; set; }
        public string empl_cond_award { get; set; }
        public string min_empl_cond_grade { get; set; }
        public string max_empl_cond_grade { get; set; }
        public string ts_system_name { get; set; }
        public string ts_fmt_name { get; set; }
        public string position_supervsr { get; set; }
        public string asco_code { get; set; }
        public Nullable<int> vers { get; set; }
        public string techone_fld1 { get; set; }
        public string techone_fld2 { get; set; }
        public Nullable<decimal> techone_fld3 { get; set; }
        public Nullable<decimal> techone_fld4 { get; set; }
        public Nullable<System.DateTime> techone_fld5 { get; set; }
        public string cruser { get; set; }
        public Nullable<System.DateTime> crdatei { get; set; }
        public Nullable<int> crtimei { get; set; }
        public string crterm { get; set; }
        public string crwindow { get; set; }
        public string last_mod_user { get; set; }
        public Nullable<System.DateTime> last_mod_datei { get; set; }
        public Nullable<int> last_mod_timei { get; set; }
        public string last_mod_term { get; set; }
        public string last_mod_window { get; set; }
        public string min_empl_cond_level { get; set; }
        public string max_empl_cond_level { get; set; }
        public string disb_code { get; set; }
        public string security_profile_name { get; set; }
        public string pos_profile_code { get; set; }
        public string pos_profile_ovr_ind { get; set; }
        public string bus_critical_ind { get; set; }
        public string tlt_mgt_system_code { get; set; }
        public string perf_apprs_meth_code { get; set; }
        public string perf_goals_apprs_ind { get; set; }
        public Nullable<int> perf_goals_weight { get; set; }
        public Nullable<int> perf_goals_min_nbr { get; set; }
        public string competencies_apprs_ind { get; set; }
        public Nullable<int> competencies_weight { get; set; }
        public Nullable<int> competencies_min_nbr { get; set; }
        public string skills_apprs_ind { get; set; }
        public Nullable<int> skills_weight { get; set; }
        public Nullable<int> skills_min_nbr { get; set; }
        public string duties_apprs_ind { get; set; }
        public Nullable<int> duties_weight { get; set; }
        public Nullable<int> duties_min_nbr { get; set; }
        public string dev_goals_apprs_ind { get; set; }
        public Nullable<int> dev_goals_weight { get; set; }
        public Nullable<int> dev_goals_min_nbr { get; set; }
        public Nullable<System.DateTime> last_publish_date { get; set; }
    }
}
