//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSYS_HIERARCH_ITM
    {
        public Nullable<int> COMPANY_CODE { get; set; }
        public string HIERARCHY_TYPE { get; set; }
        public string HIERARCHY_CODE { get; set; }
        public string PARENT_TYPE { get; set; }
        public string PARENT_NODE { get; set; }
        public string TREE_INDEX { get; set; }
        public string PARENT_INDEX { get; set; }
        public Nullable<int> CURRENT_LEVEL { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public Nullable<int> VERS { get; set; }
        public string ORG_KEY { get; set; }
        public Nullable<int> SEQ_NUM { get; set; }
        public int PARENT_NUM { get; set; }
    }
}
