//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_t1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRTIM_TSHEET_ENTRY
    {
        public int TSHEET_ENTRY_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<System.DateTime> TIMESHEET_DATE { get; set; }
        public Nullable<System.DateTime> TS_END_DATE { get; set; }
        public string POSITION_CODE { get; set; }
        public string SYSTEM_NAME { get; set; }
        public string FORMAT_NAME { get; set; }
        public Nullable<short> ENTRY_TYPE_ID { get; set; }
        public string ENTRY_TYPE { get; set; }
        public string AUTHORISED_IND { get; set; }
        public string HISTORICAL_IND { get; set; }
        public Nullable<decimal> UNITS { get; set; }
        public string UNIT_TYPE { get; set; }
        public Nullable<int> CLOCK_IN { get; set; }
        public Nullable<int> CLOCK_OUT { get; set; }
        public string COMMENTS { get; set; }
        public string LDG_CODE { get; set; }
        public string ACCNBRI { get; set; }
        public Nullable<decimal> PAY_COMPONENT_REF { get; set; }
        public string PAYROLL_COND_AWARD { get; set; }
        public string PAYROLL_COND_GRADE { get; set; }
        public string PAYROLL_COND_LEVEL { get; set; }
        public Nullable<decimal> PAYROLL_RATE { get; set; }
        public Nullable<int> LEAVE_ID { get; set; }
        public string LEAVE_ALT_UNIT_TYPE { get; set; }
        public Nullable<decimal> LEAVE_ALT_UNITS { get; set; }
        public Nullable<int> PARENT_TSHEET_ENTRY_ID { get; set; }
        public string PLANT_ITEM_TYPE { get; set; }
        public string PLANT_ITEM_CODE { get; set; }
        public string PLANT_ASSNBRI { get; set; }
        public string PLANT_ASSET_REG_NAME { get; set; }
        public string PLANT_RATE_TYPE { get; set; }
        public string PLANT_RATE_CODE { get; set; }
        public Nullable<decimal> PLANT_METER1_READ_UNITS { get; set; }
        public Nullable<decimal> PLANT_METER2_READ_UNITS { get; set; }
        public Nullable<decimal> PLANT_METER3_READ_UNITS { get; set; }
        public Nullable<decimal> PLANT_METER4_READ_UNITS { get; set; }
        public string PAID_IND { get; set; }
        public string POSTED_IND { get; set; }
        public string APPROVAL_TYPE { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATETIME { get; set; }
        public string APPROVAL_USER_ID { get; set; }
        public string SELN_TYPE_CODE1 { get; set; }
        public string SELN_TYPE_CODE2 { get; set; }
        public string SELN_TYPE_CODE3 { get; set; }
        public string SELN_TYPE_CODE4 { get; set; }
        public string SELN_TYPE_CODE5 { get; set; }
        public string SELN_TYPE_CODE6 { get; set; }
        public string SELN_TYPE_CODE7 { get; set; }
        public string SELN_TYPE_CODE8 { get; set; }
        public string SELN_TYPE_CODE9 { get; set; }
        public string SELN_TYPE_CODE10 { get; set; }
        public string SELN_TYPE_CODE11 { get; set; }
        public string SELN_TYPE_CODE12 { get; set; }
        public string USER_FLD1 { get; set; }
        public string USER_FLD2 { get; set; }
        public string USER_FLD3 { get; set; }
        public string USER_FLD4 { get; set; }
        public string USER_FLD5 { get; set; }
        public string USER_FLD6 { get; set; }
        public string USER_FLD7 { get; set; }
        public string USER_FLD8 { get; set; }
        public string USER_FLD9 { get; set; }
        public string USER_FLD10 { get; set; }
        public string USER_FLD11 { get; set; }
        public string USER_FLD12 { get; set; }
        public Nullable<System.DateTime> USER_DATEI1 { get; set; }
        public Nullable<System.DateTime> USER_DATEI2 { get; set; }
        public Nullable<System.DateTime> USER_DATEI3 { get; set; }
        public Nullable<System.DateTime> USER_DATEI4 { get; set; }
        public Nullable<System.DateTime> USER_DATEI5 { get; set; }
        public Nullable<System.DateTime> USER_DATEI6 { get; set; }
        public Nullable<System.DateTime> USER_DATEI7 { get; set; }
        public Nullable<System.DateTime> USER_DATEI8 { get; set; }
        public Nullable<System.DateTime> USER_DATEI9 { get; set; }
        public Nullable<System.DateTime> USER_DATEI10 { get; set; }
        public Nullable<System.DateTime> USER_DATEI11 { get; set; }
        public Nullable<System.DateTime> USER_DATEI12 { get; set; }
        public Nullable<decimal> USER_NUM1 { get; set; }
        public Nullable<decimal> USER_NUM2 { get; set; }
        public Nullable<decimal> USER_NUM3 { get; set; }
        public Nullable<decimal> USER_NUM4 { get; set; }
        public Nullable<decimal> USER_NUM5 { get; set; }
        public Nullable<decimal> USER_NUM6 { get; set; }
        public Nullable<decimal> USER_NUM7 { get; set; }
        public Nullable<decimal> USER_NUM8 { get; set; }
        public Nullable<decimal> USER_NUM9 { get; set; }
        public Nullable<decimal> USER_NUM10 { get; set; }
        public Nullable<decimal> USER_NUM11 { get; set; }
        public Nullable<decimal> USER_NUM12 { get; set; }
        public Nullable<int> VERS { get; set; }
        public string CRUSER { get; set; }
        public Nullable<System.DateTime> CRDATEI { get; set; }
        public Nullable<int> CRTIMEI { get; set; }
        public string CRTERM { get; set; }
        public string CRWINDOW { get; set; }
        public string LAST_MOD_USER { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATEI { get; set; }
        public Nullable<int> LAST_MOD_TIMEI { get; set; }
        public string LAST_MOD_TERM { get; set; }
        public string LAST_MOD_WINDOW { get; set; }
        public string RES_ACTY_CODE { get; set; }
    }
}
