//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANGCARE_IFR
    {
        public int ANGCARE_ID { get; set; }
        public string ANGPolNo { get; set; }
        public string PersonRespNotif { get; set; }
        public Nullable<bool> AHNotif { get; set; }
        public string AHContactedBy { get; set; }
        public Nullable<System.DateTime> AHContactedDate { get; set; }
        public Nullable<bool> PHNotif { get; set; }
        public string PHContactedBy { get; set; }
        public Nullable<System.DateTime> PHContactedDate { get; set; }
        public Nullable<bool> ACATNotif { get; set; }
        public string ACATContactedBy { get; set; }
        public Nullable<System.DateTime> ACATContactedDate { get; set; }
        public string EntBehalfOfPos { get; set; }
        public string ACShiftSupervisor { get; set; }
        public string ACWhoReportName { get; set; }
        public string ACWhoReportPosition { get; set; }
        public string ACReportBehalfPosition { get; set; }
        public string OthersInvolvedRECID { get; set; }
        public string OthersInvolvedPrevRECID { get; set; }
        public string InjuryType { get; set; }
        public Nullable<bool> ClientMedicalRequired { get; set; }
        public string MedAttType { get; set; }
        public string CorActWhyNot { get; set; }
        public Nullable<bool> InvInit { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<bool> InvestComp { get; set; }
        public Nullable<System.DateTime> InvestCompDate { get; set; }
        public string CustomerSite { get; set; }
        public Nullable<bool> IndigenousState { get; set; }
        public Nullable<bool> IncSeen { get; set; }
        public Nullable<System.DateTime> FirstInformedDate { get; set; }
        public Nullable<System.DateTime> FirstInformedTime { get; set; }
        public string MedAttName { get; set; }
        public string IncStatus { get; set; }
        public string InjuryActivity { get; set; }
        public string CustService { get; set; }
        public string InjuryOth { get; set; }
        public string Wing { get; set; }
    }
}
