//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_IFR
    {
        public int CH_ID { get; set; }
        public string PCARECID { get; set; }
        public string PCAPrevRECID { get; set; }
        public Nullable<bool> CHReportBehalf { get; set; }
        public string CHReportWho { get; set; }
        public string CHExpYrs { get; set; }
        public string CHWhereEventOccur { get; set; }
        public Nullable<bool> CHStaffTraining { get; set; }
        public Nullable<bool> CHPrevActReq { get; set; }
        public Nullable<bool> OHSAltDuty { get; set; }
        public Nullable<bool> HasHSRNot { get; set; }
        public string CHLocalGovtMethod { get; set; }
        public string CHLocalGovtContact { get; set; }
        public string CHDHSMethod { get; set; }
        public string CHDHSContact { get; set; }
        public string CHDoHAMethod { get; set; }
        public string CHDoHAContact { get; set; }
        public string CHPhysLocOther { get; set; }
        public Nullable<System.DateTime> CHWorkStartTime { get; set; }
        public string CreatComp { get; set; }
        public string SiteAdd { get; set; }
        public string OthService { get; set; }
        public string OthCustSite { get; set; }
        public string OthSite { get; set; }
        public Nullable<bool> IncRelChild { get; set; }
        public Nullable<int> ComplaintID { get; set; }
        public string ContFactOth { get; set; }
        public string RiskCatFactOth { get; set; }
        public string SafeWorkOth { get; set; }
    }
}
