//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_riskman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class extract_riskmanContainer : DbContext
    {
        public extract_riskmanContainer()
            : base("name=extract_riskmanContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IncidentClassificationsIFR> IncidentClassificationsIFRs { get; set; }
        public virtual DbSet<IncidentsForReview> IncidentsForReviews { get; set; }
        public virtual DbSet<ANGCARE_IFR> ANGCARE_IFR { get; set; }
        public virtual DbSet<CH_IFR> CH_IFR { get; set; }
        public virtual DbSet<FRM_BATCH> FRM_BATCH { get; set; }
        public virtual DbSet<FRM_DATA> FRM_DATA { get; set; }
        public virtual DbSet<FRM_RECORD> FRM_RECORD { get; set; }
    }
}
