//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRM_DATA
    {
        public int DataID { get; set; }
        public int BatchID { get; set; }
        public string FieldName { get; set; }
        public string ValueString { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<double> ValueNumber { get; set; }
        public Nullable<bool> ValueBit { get; set; }
        public bool Active { get; set; }
    }
}
