//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingWarehouse.models.dwhb.extract_riskman
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRM_BATCH
    {
        public int BatchID { get; set; }
        public int RecordID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string SavedBy { get; set; }
    }
}
