
---------------------------------------
-- Extract
---------------------------------------

insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLTERM_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLTERM_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRSYS_HIERARCH_CTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRSYS_HIERARCH_CTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRSYS_HIERARCH_ITM' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRSYS_HIERARCH_ITM' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRSYS_HIERARCH_LVL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRSYS_HIERARCH_LVL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPL_JOB_CTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPL_JOB_CTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPL_JOB_POS' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPL_JOB_POS' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPL_REF' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPL_REF' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLTERM_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLTERM_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_QUAL_REF' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_QUAL_REF' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLQUAL_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLQUAL_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_PAYITEMS_SUMMACCR' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_PAYITEMS_SUMMACCR' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_PAYITEMS_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_PAYITEMS_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_PAYITEMS_SUMMPMNT' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_PAYITEMS_SUMMPMNT' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_MASTER_CTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_MASTER_CTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_LEAVE_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_LEAVE_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_LEAVE_CTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_LEAVE_CTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPCM_PAYCOMP_DEF' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPCM_PAYCOMP_DEF' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPCM_PAYCOMP_REF' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPCM_PAYCOMP_REF' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'F1_USER_PROFILE' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'F1_USER_PROFILE' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRLVE_LEAVE_CTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRLVE_LEAVE_CTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRPAY_LVE_TKN_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRPAY_LVE_TKN_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1, 'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HREEN_EMPLENT_ACCR' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HREEN_EMPLENT_ACCR' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRSTC_CODE' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRSTC_CODE' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLJOB_CRW' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLJOB_CRW' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRSYS_HIEREFF_MST' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRSYS_HIEREFF_MST' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRSYS_USRSELN_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRSYS_USRSELN_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_USR_FLD' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_USR_FLD' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HREEN_EMPL_ENT_CTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HREEN_EMPL_ENT_CTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HREEN_EMPL_ENT_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HREEN_EMPL_ENT_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLISS_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLISS_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'GLF_SELN_CODE' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'GLF_SELN_CODE' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRCOM_ADDRESS_REF' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRCOM_ADDRESS_REF' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRTIM_TSHEET_ENTRY' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRTIM_TSHEET_ENTRY' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'F1TIM_FMT_LNE' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'F1TIM_FMT_LNE' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'GLF_LDG_ACCT_DESC1' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'GLF_LDG_ACCT_DESC1' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRRST_ROSTER_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRRST_ROSTER_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRRST_ROSTER_REF' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRRST_ROSTER_REF' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLCONT_DTL' and [schema] = 'dbo' and [system] = 'HRIS-T1'), 'YES', (select table_key from [management].[table_dim] where table_name = 'HRHMN_EMPLCONT_DTL' and [schema] = 'extract' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');

---------------------------------------
-- delivery: facts
---------------------------------------
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_RECRUITMENT_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_RECRUITMENT_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_TERMINATION_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_TERMINATION_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_ACCREDITATION_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_ACCREDITATION_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_POSITION_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_POSITION_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_CONTRACT_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_CONTRACT_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_PROFILE_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_PROFILE_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'LABOUR_TURNOVER_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'LABOUR_TURNOVER_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_TAKEN_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_TAKEN_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_BOOKED_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_BOOKED_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_RENUMERATION_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_RENUMERATION_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_TIMESHEET_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_TIMESHEET_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_SNAPSHOT_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_SNAPSHOT_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_PAYMENT_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_PAYMENT_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_BOOKED_TXN_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_BOOKED_TXN_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'WORK_PATTERN_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'WORK_PATTERN_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_ACCRUED_FACT' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_LEAVE_ACCRUED_FACT' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'timesheet_validation_fact' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'timesheet_validation_fact' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'employee_payment_summary_fact' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'employee_payment_summary_fact' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');


---------------------------------------
-- delivery: dimensions
---------------------------------------

insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'ACCREDITATION_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'ACCREDITATION_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_BENEFIT_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_BENEFIT_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_PAYMENT_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'EMPLOYEE_PAYMENT_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'ITEM_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'ITEM_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'LEAVE_TYPE_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'LEAVE_TYPE_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'ORGANISATION_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'ORGANISATION_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'PORTFOLIO_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'PORTFOLIO_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'POSITION_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'POSITION_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'PROGRAM_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'PROGRAM_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'SALARY_CODE_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'SALARY_CODE_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'SERVICE_STREAM_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'SERVICE_STREAM_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'ACCOUNT_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'ACCOUNT_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'PAYMENT_TYPE_DIM' and [schema] = 'conform'), 'YES', (select table_key from [management].[table_dim] where table_name = 'PAYMENT_TYPE_DIM' and [schema] = 'hris'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');
