-- comcare -> DWHB.extract_comcare 
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fc_transaction_type' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fc_transaction_type' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fc_transaction' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fc_transaction' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fc_account' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fc_account' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fc_client_contract' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fc_client_contract' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'client' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'client' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'pt_program' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'pt_program' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'person' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'person' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'period_of_residency' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'period_of_residency' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'address' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'address' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'suburb' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'suburb' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'state' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'state' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');

-- already inserted 18.04.17
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'activity_work_table' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'activity_work_table' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');


insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'provider' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'provider' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'provider_contract' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'provider_contract' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'task_type' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'task_type' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'indirect_activity_type' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'indirect_activity_type' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fc_account_type' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fc_account_type' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fb_client_contract_billed_to' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fb_client_contract_billed_to' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fb_client_contract_billing' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fb_client_contract_billing' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'fb_client_cb_split' and [schema] = 'dbo' and [system] = 'comcare'), 'YES', (select table_key from [management].[table_dim] where table_name = 'fb_client_cb_split' and [schema] = 'extract_comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'EXTRACT' and sub_system = 'Extract system'),1,'daily');

-- DWHB.conform -> DWHF.comcare (Dimensions)
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'customer_dim' and [schema] = 'conform_comcare' and [system] = 'dwh'), 'YES', (select table_key from [management].[table_dim] where table_name = 'customer_dim' and [schema] = 'comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'transaction_type_dim' and [schema] = 'conform_comcare' and [system] = 'dwh'), 'YES', (select table_key from [management].[table_dim] where table_name = 'transaction_type_dim' and [schema] = 'comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'program_dim' and [schema] = 'conform_comcare' and [system] = 'dwh'), 'YES', (select table_key from [management].[table_dim] where table_name = 'program_dim' and [schema] = 'comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'date_dim' and [schema] = 'conform_comcare' and [system] = 'dwh'), 'YES', (select table_key from [management].[table_dim] where table_name = 'date_dim' and [schema] = 'comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'responsible_party_dim' and [schema] = 'conform_comcare' and [system] = 'dwh'), 'YES', (select table_key from [management].[table_dim] where table_name = 'responsible_party_dim' and [schema] = 'comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),1,'daily');

-- DWHB.conform -> DWHF.comcare (Facts)
insert into [management].[job_control] values ((select table_key from [management].[table_dim] where table_name = 'customer_transactions_fact' and [schema] = 'conform_comcare' and [system] = 'dwh'), 'YES', (select table_key from [management].[table_dim] where table_name = 'customer_transactions_fact' and [schema] = 'comcare' and [system] = 'dwh'), (select package_key from [management].[package_dim] where package_name = 'DELIVERY' and sub_system = 'Delivery system'),2,'daily');